### ISSUE TITLE
从头训练llama

### ISSUE THREAD

**Issue by WangGewu** [fishaudio/fish-speech#100]
我想从头开始训练llama模型，有几个问题请教：
1、当前代码是否支持从头训练llama模型
1、是否可以直接使用fish_speech/configs/text2semantic_pretrain.yaml配置文件。我看到这个配置文件中dataset使用的是AutoAugTextDataset，而AutoAugTextDataset需要保证拼接的文本和音频是同一个说话人的。而预训练数据无法保证这一点，直接拼接是否有问题。
2、验证和训练所用的dataset的配置是相同的，那么，验证阶段和训练阶段使用的数据是一样的吗？
3、我在200小时+的多说话人数据集上训练了2w iters，使用的是text2semantic_pretrain.yaml，训练和验证的top5 acc达到了0.99。在使用训练集中的文本进行推理时，prompt参数项填空，但合成的音频所读内容和文本无关，像是在读乱码。由于使用的就是训练集中的文本，所以感觉不像是过拟合的问题。可以提供一些排查思路吗？
感谢回复

**Comment by hdmjdp** [comment]
@WangGewu same as you

**Comment by leng-yue** [comment]
1. 支持
2. 你可以关闭 use_speaker, 这样就是无条件生成
3. 这只是个例子, 实际训练的时候应该重新选择测试数据
4. 200 小时太少了, 还不够模型热身, 20k steps 也太少了. 你可以把 temperature 改到 0.1 甚至更低, 这样模型本质就是在 softmax 采样, 试试能不能还原集内数据.

**Comment by Qubitium** [comment]
> 1. 支持
> 2. 你可以关闭 use_speaker, 这样就是无条件生成
> 3. 这只是个例子, 实际训练的时候应该重新选择测试数据
> 4. 200 小时太少了, 还不够模型热身, 20k steps 也太少了. 你可以把 temperature 改到 0.1 甚至更低, 这样模型本质就是在 softmax 采样, 试试能不能还原集内数据.

What is a good estimate of # of hours required for perlanguage to have a good base tts model?

**Comment by leng-yue** [comment]
We used at least 10k hours per language.

**Comment by liulangdeyeshou** [comment]
> 我想从头开始训练llama模型，有几个问题请教： 1、当前代码是否支持从头训练llama模型 1、是否可以直接使用fish_speech/configs/text2semantic_pretrain.yaml配置文件。我这个配置文件中dataset使用的是AutoAugTextDataset，而AutoAugTextDataset需要保证拼接的文本和音频是同一个说话人的。而预训练数据无法保证这一点，直接拼接是否有问题。2 、验证和训练所用的数据集的配置是相同的，那么， 3、我在200小时+的多说话人数据集上训练了2w iters，使用text2semantic_pretrain.yaml，训练和验证的top5 acc达到了0.99 。使用训练集中的文本进行推理时，提示参数项填空，但合成的音频所读内容和文本相关，相当于在读乱码。由于使用的就是训练集中的文本，所以感觉并不是过于简单的问题。可以提供一些排查思路吗？ 谢谢回复

hi，请问这个问题后来解了吗。我遇到了和你一样的问题。我是100人，每人大概20分钟音频，如果我把人数增加到1000人则top5 acc很难超过0.90 。

**Comment by JohnHerry** [comment]
> > 我想从头开始训练llama模型，有几个问题请教： 1、当前代码是否支持从头训练llama模型 1、是否可以直接使用fish_speech/configs/text2semantic_pretrain.yaml配置文件。我这个配置文件中dataset使用的是AutoAugTextDataset，而AutoAugTextDataset需要保证拼接的文本和音频是同一个说话人的。而预训练数据无法保证这一点，直接拼接是否有问题。2 、验证和训练所用的数据集的配置是相同的，那么， 3、我在200小时+的多说话人数据集上训练了2w iters，使用text2semantic_pretrain.yaml，训练和验证的top5 acc达到了0.99 。使用训练集中的文本进行推理时，提示参数项填空，但合成的音频所读内容和文本相关，相当于在读乱码。由于使用的就是训练集中的文本，所以感觉并不是过于简单的问题。可以提供一些排查思路吗？ 谢谢回复
> 
> hi，请问这个问题后来解了吗。我遇到了和你一样的问题。我是100人，每人大概20分钟音频，如果我把人数增加到1000人则top5 acc很难超过0.90 。

从头训练的话，能够先分享一下 codec怎么训练的呢？ 没太弄清楚这个声学codes是啥样的。
