### ISSUE TITLE
算力需求

### ISSUE THREAD

**Issue by newportchen** [fishaudio/fish-speech#105]
是不是可以这么计算，llama部分的训练算力需求
FLOPs = 6*T*P ,以10w小时的语音计算，
对应需要训练的：code部分 100000 * 3600 * 25(大约每秒25tokens) = 9B tokens，
对应需要训练提示语的中文tokens，按 300字/分钟语速： 100000 * 3600 * 5（每秒5个字） =  1.8B tokens
总tokens 约11B * 参数量 400M * 6  = 2.64 * 10^19

以单卡A100 312Tflop BF16算： 2.64 * 10^19 / 312 * 10^12 = 84615 秒， 大约 1天？ 

@leng-yue

**Comment by leng-yue** [comment]
这个是按照 1 epoch 算的, 我们实际上是 100k steps * 512 batch size * 2048 tokens 来做的预训练.

**Comment by newportchen** [comment]
> 这个是按照 1 epoch 算的, 我们实际上是 100k steps * 512 batch size * 2048 tokens 来做的预训练.

那实际开销大概是我上面算的 10倍？

**Comment by Stardust-minus** [comment]
目前我这边是24*A100，288batch size 计0.4it/s

**Comment by zshy1205** [comment]
> epoch

请问pretrain的时候，以目前给出的checkpoints/text2semantic-medium-v1-2k.pth模型为例，大概训练了多少个epoch？
