### ISSUE TITLE
有发现多字少字的问题吗？如何解决呢？

### ISSUE THREAD

**Issue by gandolfxu** [fishaudio/fish-speech#107]
用自有数据预训练+微调

输入文本：
几乎每个人都有颈椎错位，有的人症状轻，有的人症状重，即使自我感觉不明显，越早纠正也越好。

合成音频对应的文本：

几乎每个人都有颈椎错位，有的人症状轻，有的人症状轻，有的人症状轻，有的人症状重，即使自我感觉不明显，越早纠正也越好。

**Comment by wac81** [comment]
是的，llm带来的问题

**Comment by wac81** [comment]
改改参数

**Comment by exceedzhang** [comment]
@wac81 改哪个参数？
