### ISSUE TITLE
加载模型时提示找不到config.json，请问怎么解决呢？

### ISSUE THREAD

**Issue by FLH1030** [fishaudio/fish-speech#115]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / log**
If applicable, add screenshots / logs to help explain your problem.

**Additional context**

**Comment by leng-yue** [comment]
请提供更多信息...
