### ISSUE TITLE
OSError: We couldn't connect to 'https://huggingface.co' to load this file

### ISSUE THREAD

**Issue by FLH1030** [fishaudio/fish-speech#119]
执行
python tools/llama/generate.py \
    --text "要转换的文本" \
    --prompt-text "你的参考文本" \
    --prompt-tokens "fake.npy" \
    --checkpoint-path "checkpoints/text2semantic-400m-v0.2-4k.pth" \
    --num-samples 2 \
    --compile
报错：    
resolved_config_file = cached_file(
  File "/data/workpace/fish-speech/.conda/lib/python3.10/site-packages/transformers/utils/hub.py", line 441, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like fishaudio/speech-lm-v1 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
尝试从huggingface下载config.json文件到本地，但是模型下面没有看到有config.json
请问如何解决呢？

**Comment by leng-yue** [comment]
可以下载 `fishaudio/speech-lm-v1` 并手动指定 `--tokenizer` 为本地文件夹.
