### ISSUE TITLE
OSError: ./checkpoints does not appear to have a file named config.json.

### ISSUE THREAD

**Issue by FLH1030** [fishaudio/fish-speech#120]
下载 了fishaudio/speech-lm-v1 并手动指定 --tokenizer 为本地文件夹，提示找不到config.json，下载的文件里面也确实没有config.json，在huggingface上也没有找到config.json，请问如何解决呢？
   raise EnvironmentError(
OSError: ./checkpoints does not appear to have a file named config.json. Checkout 'https://huggingface.co/./checkpoints/tree/None' for available files.

**Comment by Edisonwei54** [comment]
同样的问题，有解决的办法吗？

**Comment by Edisonwei54** [comment]
> 同样的问题，有解决的办法吗？

--tokenizer /home/lafei/edison/fish-speech/checkpoints
我添加这个参数就可以运行了

**Comment by 188140040** [comment]
@Edisonwei54  在哪个位置添加 --tokenizer /home/lafei/edison/fish-speech/checkpoints  ？

**Comment by Hardwell99** [comment]
去Huggingface下载tokenizer.json、tokenizer_config.json到checkpoints目录下
[fish speech](https://huggingface.co/fishaudio/fish-speech-1/tree/main)
