### ISSUE TITLE
ImportError：undefined symbol: _ZN2at4_ops10select_int4callERKNS_6TensorEll

### ISSUE THREAD

**Issue by amateur12138** [fishaudio/fish-speech#122]
<img width="408" alt="52a3534adf8e54c1526e52a312b8b4d" src="https://github.com/fishaudio/fish-speech/assets/152724134/dbc9004c-ec3e-45a9-afea-6a11881e780c">
ImportError: /root/miniconda3/envs/myconda/lib/python3.10/site-packages/MultiScaleDeformableAttention-1.0-py3.10-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops10select_int4callERKNS_6TensorEll

my environment：
ubuntu20.04
python 3.10
cuda11.8
pytorch2.1.1
mmdet2.7.0
How to solve this error？Thanks！
<img width="404" alt="9e85bf04c628b0c6094233fe2d6f2b5" src="https://github.com/fishaudio/fish-speech/assets/152724134/964ccff4-52bd-4a43-89f4-a80000e61d0d">

**Comment by leng-yue** [comment]
This seems to be a dino issue, we are not using that anyway...
