### ISSUE TITLE
[Feature]  The usage of Llama positional encoding.

### ISSUE THREAD

**Issue by hertz-pj** [fishaudio/fish-speech#130]
In the implementation of Fishspeech, LLAMA is used as the LM model to generate semantic tokens. I have some doubts about the usage of LLAMA position embedding here. The position embedding in this case combines text and semantic tokens together for encoding. However, theoretically, there should be no relative positional relationship between text and semantic tokens (the distance between a semantic token and a text token is theoretically meaningless). So, would it be more reasonable to refer to the implementation of VALLE and encode the positions of text and semantic tokens separately?

**Comment by hertz-pj** [comment]
I previously saw that a new version of the model would be released in other issues which would address many problems present in the previous model. I am wondering if it has been released yet.

**Comment by leng-yue** [comment]
The relative positional relationship does matter for our case.  
It's plan to release at under of April, we obersved siginificant better performance.
