### ISSUE TITLE
[BUG]不管是选择cpu还是gpu加载模型的时候报错

### ISSUE THREAD

**Issue by Telanx** [fishaudio/fish-speech#132]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**
看代码里没有对设置分支进行判断，而直接执行`torch.cuda.synchronize()`,导致没有cuda显卡的电脑报错
```python
# api_server.py 第86行
self.model_size = sum(
            p.numel() for p in self.model.parameters() if p.requires_grad
        )
torch.cuda.synchronize()
logger.info(f"Time to load model: {time.time() - self.t0:.02f} seconds")
```

**Expected behavior**
可以支持CPU推理

**Comment by leng-yue** [comment]
CPU 推理真的很慢... 晚点我改下

**Comment by leng-yue** [comment]
该问题应该在最新版本修复了, 你看看?

**Comment by Hoshino-Yumetsuki** [comment]
> 该问题应该在最新版本修复了, 你看看?

![image](https://github.com/fishaudio/fish-speech/assets/147403913/19be8f84-1c48-452e-a0a1-a4ef4a24a3da)
目前依然存在此问题

**Comment by wuye901126** [comment]
![微信图片_20240515164806](https://github.com/fishaudio/fish-speech/assets/24641901/dd9d31e5-613f-4738-b380-bff00496e70e)
遇到同样的问题了

**Comment by leng-yue** [comment]
试下制定 --device cpu?

**Comment by wuye901126** [comment]
不能使用CUDA吗

**Comment by leng-yue** [comment]
你都没装带 cuda 的 torch

**Comment by Hoshino-Yumetsuki** [comment]
> 不能使用CUDA吗

默认安装的torch是cpu的，你得指定安装cuda版本的torch，在更新版本之前记得把原来的torch卸载掉

**Comment by wuye901126** [comment]
使用api_server  启动 
![1715847448053](https://github.com/fishaudio/fish-speech/assets/24641901/8b16a856-9cc9-4d94-952a-6369ce5f1463)

**Comment by wuye901126** [comment]
> > 不能使用CUDA吗？
> 
> 默认安装的torch是cpu的，你得指定安装cuda版本的torch，在更新版本之前记得把原来的torch卸载掉
改成了cuda版本的torch  但是现在启动提示缺少文件 
![1715847509635](https://github.com/fishaudio/fish-speech/assets/24641901/b08a3ed3-7351-414d-9859-0817bac3f25f)

**Comment by AnyaCoder** [comment]
更新吧。

**Comment by linuxhub** [comment]
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu 
 启动时加上 --device cpu  
 CPU 奇慢

**Comment by leng-yue** [comment]
CPU 本来就慢啊.. 不然为啥要买 GPU
