### ISSUE TITLE
webui推理出错

### ISSUE THREAD

**Issue by WuerLei** [fishaudio/fish-speech#136]
ubuntu 23.10

驱动版本：cuda12.3

torch信息：
pytorch-lightning           2.2.3
pytorch-triton              3.0.0+45fff310c8
torch                       2.4.0.dev20240423+cu121
torchaudio                  2.2.0.dev20240423+cu121
torchmetrics                1.3.2
torchvision                 0.19.0.dev20240423+cu121

报错信息见下面附图

<img width="1284" alt="20240425154736" src="https://github.com/fishaudio/fish-speech/assets/17868974/16ed7466-d00f-4330-bbd3-b25e2d16d950">
<img width="1904" alt="20240425154751" src="https://github.com/fishaudio/fish-speech/assets/17868974/c1580828-6e2c-4a54-a98b-94c8ed462e81">

<img width="1866" alt="20240425154811" src="https://github.com/fishaudio/fish-speech/assets/17868974/7a6f5817-f076-4cc7-beda-113035aed864">

用命令行能成功，另外咨询下”参考文本“，” --prompt-text“参数啥含义，ui上手动修改了还显示默认的

**Comment by leng-yue** [comment]
要降级 einx, 他们前两天更新了一堆 bug, 可以参考 dev 的 dependency

**Comment by fferflo** [comment]
升级到最新的einx版本后，这个问题应该会解决。如果使用该库出现任何问题，请随时提交问题或标记我。我会尽快解决问题。

**Comment by leng-yue** [comment]
感谢您的迅速回复, 我们在最新版测试该问题已经修复了.
