### ISSUE TITLE
[BUG]ModuleNotFoundError: No module named 'tools.llama'

### ISSUE THREAD

**Issue by Pevernow** [fishaudio/fish-speech#147]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**
pip3 install -e .成功

运行webui失败

**To Reproduce**
git clone仓库

pip3 install -e .

python -m tools.webui \
    --llama-checkpoint-path "checkpoints/text2semantic-sft-large-v1-4k.pth" \
    --llama-config-name dual_ar_2_codebook_large \
    --vqgan-checkpoint-path "checkpoints/vq-gan-group-fsq-2x1024.pth"

**Expected behavior**
正常运行

**Screenshots / log**
![image](https://github.com/fishaudio/fish-speech/assets/29888010/890b32e3-4d8d-460d-8b6c-ba7b89b5f4d1)

**Additional context**
就算直接调用webui.py也没用

**Comment by leng-yue** [comment]
很显然 python -m tools.webui 和 python tools/webui 不是一回事...  不过这个我优化下
