### ISSUE TITLE
只传入text时，如何固定说话人？

### ISSUE THREAD

**Issue by wac81** [fishaudio/fish-speech#148]
payload = {
                "text": text,
                "reference_text": None,
                "reference_audio": None,
                "max_new_tokens": 0,
                "chunk_length": 30,
                "top_k": 0,
                "top_p": 0.7,
                "repetition_penalty": 1.5,
                "temperature": 0.7,
                "speaker": "纳西妲",
                "format": "wav"

    }
    
    这样请求还是会有不同说话人的声音，要求：不传入原始音频，仅传入text，固定某一个说话人(女声)

**Comment by leng-yue** [comment]
目前不支持, 还在改. 最简单的方案是单说话人 LoRA 微调

**Comment by wuye901126** [comment]
有个问题 传入了参考音频，感觉没起到作用

**Comment by lonngxiang** [comment]
音色有哪些人可以选择呢？

**Comment by yc930401** [comment]
> 有个问题 传入了参考音频，感觉没起到作用

遇到了同样的问题，api启动的不生效。
