### ISSUE TITLE
add feature support VITS2 training like dataset format

### ISSUE THREAD

**Issue by luohao123** [fishaudio/fish-speech#15]
We are coming from Bert-VITS2, its a very good project, and we already have many dataset which using vits like format:

```
aaa.wav|Jake|ZH|我来了
```

is there a way to suppor this format as well?

**Comment by leng-yue** [comment]
@Stardust-minus Maybe we can introduce a data converter to convert Bert-VITS2 format into protos?

**Comment by Stardust-minus** [comment]
> We are coming from Bert-VITS2, its a very good project, and we already have many dataset which using vits like format:
> 
> ```
> aaa.wav|Jake|ZH|我来了
> ```
> 
> is there a way to suppor this format as well?

#18

**Comment by luohao123** [comment]
@Stardust-minus @leng-yue  thank u so much.

As a rookie, wanna consult 2 questions:

1. Does the vits data can be directly used to train the vqgan? does there any other operation need to do;
2. I finetune on my custom data, the llama part shouldn't change right? It at least can support Chinese and English out of box?

**Comment by leng-yue** [comment]
For 1, yes.  
For 2, I am not sure that you mean. You can finetune llama for better quality, and if you use g2p mode (enabled by default), yes, it supports Chinese and English out of box.

**Comment by leng-yue** [comment]
VITS format docs updated.

**Comment by luohao123** [comment]
@leng-yue training llama and vqgan, the data is same right?

**Comment by leng-yue** [comment]
audio + text

**Comment by luohao123** [comment]
I think for llama, the gt should be codebook + text?

**Comment by leng-yue** [comment]
Yes, basically semantic tokens + text.

**Comment by luohao123** [comment]
how's the pretrained model trained? Is it using Genius Dataset? 元神

**Comment by leng-yue** [comment]
The data used for current model are shown [here](https://github.com/fishaudio/fish-speech/blob/main/fish_speech/configs/data/pretrain.yaml).

**Comment by luohao123** [comment]
@leng-yue  Is there any convenient way to finetune on my existed Bertvits2 data?

Just like `train_ms.py` and then webui to verify the result
