### ISSUE TITLE
[BUG]soundfile.LibsndfileError: Error opening Format not recognised.

### ISSUE THREAD

**Issue by Pevernow** [fishaudio/fish-speech#151]
**Describe the bug**
![image](https://github.com/fishaudio/fish-speech/assets/29888010/accf4e31-fb39-4337-aeaf-ba40cbf9c257)
如图，选好并启用打标。
报错
![image](https://github.com/fishaudio/fish-speech/assets/29888010/6ac6280c-bd82-485b-85c9-069d95fdc8e4)
原文件是1.wav
似乎会尝试再生成一份1-0.wav，但是大小是零字节
然后报错
soundfile.LibsndfileError: Error opening 'D:\\备份\\Kx_Li\\1-0.wav': Format not recognised.
**To Reproduce**
同上

**Expected behavior**
别一直报错了。

**Screenshots / log**
在上面

**Additional context**
环境是huggingface上下载的fish speechv1的win整合包

**Comment by AnyaCoder** [comment]
这个是windows的`soundfile`后端处理“非单声道”的问题，你需要通过在根目录下打开控制台，输入以下命令来使得所有音频转换为单声道。
请在项目目录下创建一个`convert_wav_mono.bat`文件：
```bat
@echo off
setlocal enabledelayedexpansion

set "source_folder=D:\备份\Kx_Li"
set "output_folder=D:\备份\Kx_Li_mono"

if not exist "%output_folder%" mkdir "%output_folder%"

for %%a in ("%source_folder%\*.mp3" "%source_folder%\*.wav" "%source_folder%\*.flac") do (
    set "filename=%%~na"
    set "extension=%%~xa"
    ffmpeg -i "%%a" -ac 1 "%output_folder%\!filename!_mono!extension!"
)
echo 转换为单声道完成.
pause
```

然后到`D:\备份\Kx_Li_mono`目录下查看转换好的单声道音频。

**Comment by AnyaCoder** [comment]
这里是最新的整合包（最上面的最新）
[整合包链接](https://github.com/fishaudio/fish-speech/actions/workflows/build-windows-package.yml)
