### ISSUE TITLE
[BUG]RuntimeError: Cannot load audio from file: `ffprobe` not found. Please install `ffmpeg` in your system to use non-WAV audio file formats and make sure `ffprobe` is in your PATH.

### ISSUE THREAD

**Issue by Pevernow** [fishaudio/fish-speech#152]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**
用huggingface上的win整合环境
使用mp3参考音频报这个错

**Expected behavior**
......这个整合包完全没测试过就发布了吗？

**Comment by AnyaCoder** [comment]
不好意思，可能没有提前说明清楚。参考音频要选择单声道的`.wav`文件。
