### ISSUE TITLE
[Feature] text2semantic loss range?

### ISSUE THREAD

**Issue by BridgetteSong** [fishaudio/fish-speech#157]
I try to test different VQ models for text2semantic training, but I find semantic losses in some VQ model are a bit larger(about 3.2).
For my best VQ model, I can get semantic loss about 1.5 and top one Accuracy is 55%, but my worst semantic loss is about 4.2.

so I want to know, in the training stage, what are semantic loss range of text2semantic and top_k(egs. top 5) Accuracy?  
Does A larger semantic loss mean worse inference performance? 
What is a normal  semantic loss range for stable inference?

**Comment by leng-yue** [comment]
The semantic loss and accuracy totally depends on your VQ model, for our 2x1024 codebooks, it's expected to have a top-5 accuracy around 30%.
