### ISSUE TITLE
[BUG]微调后为什么checkpoints文件下只有ckpt 的文件没有pth文件？

### ISSUE THREAD

**Issue by kingslyChen** [fishaudio/fish-speech#163]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / log**
If applicable, add screenshots / logs to help explain your problem.

**Additional context**
微调后为什么checkpoints文件下只有ckpt 的文件没有pth文件？

**Comment by aixiaodewugege** [comment]
Hi 你是微调的gan还是llama？效果怎么样呢？

**Comment by kingslyChen** [comment]
补充一些信息，是lama的微调，训练的时候只有text2semantic_finetune_dual_ar的checkpoints下有ckpt文件，\text2semantic_finetune checkpoints 下没有pth文件

**Comment by aixiaodewugege** [comment]
用ckpt，也能推理，我试了但是效果不行，感觉比bertvits2 和 gptsovits 都要差一下

**Comment by kingslyChen** [comment]
> 用ckpt，也能推理，我试了但是效果不行，感觉比bertvits2 和 gptsovits 都要差一下

我的也是效果不行，但是看别人的视频效果就还行，不知道问题在哪

**Comment by leng-yue** [comment]
目前推理需要带参考音频

**Comment by aixiaodewugege** [comment]
> > 用ckpt，也能推理，我试了但是效果不行，感觉比bertvits2 和 gptsovits 都要差一下
> 
> 我的也是效果不行，但是看别人的视频效果就还行，不知道问题在哪

老哥要不加一下 微信互通一下有无？我是  wushuchenpp

**Comment by kingslyChen** [comment]
> 目前推理需要带参考音频, ckpt 和 pth 没有区别.

你好，推理的时候也带了参考音频了

**Comment by leng-yue** [comment]
你现在是韵律不行, 还是音色不像?

**Comment by kingslyChen** [comment]
> 你现在是韵律不行, 还是音色不像?

音色可以听出来有一点像，但是生成的语音读字都读不准，还有漏字的问题，是否也和数据集有关？

**Comment by aixiaodewugege** [comment]
> > 你现在是韵律不行, 还是音色不像?
> 
> 音色可以听出来有一点像，但是生成的语音读字都读不准，还有漏字的问题，是否也和数据集有关？

和我情况一样，我使用的是7分钟的数据

**Comment by leng-yue** [comment]
音色微调 VQGAN, 韵律微调 LLAMA.  
口胡是双码本的问题, 目前在最新版本 (1.1) 基本解决了. 相关 VITS Decoder 权重会在今天发布.

**Comment by aixiaodewugege** [comment]
> 音色微调 VQGAN, 韵律微调 LLAMA. 口胡是双码本的问题, 目前在最新版本 (1.1) 基本解决了. 相关 VITS Decoder 权重会在今天发布.

试了demo， 缺字情况有大幅改善！

**Comment by leng-yue** [comment]
vqgan 权重没更新, 可以试试 VITS Decoder
