### ISSUE TITLE
'float' object cannot be interpreted as an integer [BUG]

### ISSUE THREAD

**Issue by GKCsdfsGKC** [fishaudio/fish-speech#164]
![image](https://github.com/fishaudio/fish-speech/assets/20057251/acc66f21-5b93-4236-a0f2-a08e0944465d)

**To Reproduce**
python tools/vqgan/inference.py -i "test.wav"

**Comment by leng-yue** [comment]
Can you attach the full traceback?

**Comment by GKCsdfsGKC** [comment]
![image](https://github.com/fishaudio/fish-speech/assets/20057251/850f8263-cdc5-450b-a462-df0ff7a08af8)

**Comment by leng-yue** [comment]
I have no idea, please double check dependency version, or check docker container.

**Comment by unlimit999** [comment]
我跟你一樣是報這個錯，可以嘗試改一下這個參數
trainer.precision=bf16-mixed

我是改完之後就正常了

**Comment by leng-yue** [comment]
Fixed
