### ISSUE TITLE
在AutoDL上用fish-speech-v2微调VQGAN，tensorboard中，loss_vq恒为0

### ISSUE THREAD

**Issue by Scau-Guang** [fishaudio/fish-speech#165]
这样是否影响了训练效果

**Comment by Scau-Guang** [comment]
![image](https://github.com/fishaudio/fish-speech/assets/65593421/c90387aa-259e-426e-a7d1-a1990c79be90)

**Comment by leng-yue** [comment]
不影响, 这是正常的. 不过我看你 loss mel 一路狂掉, 小心过拟合.
