### ISSUE TITLE
从头训练vqgan，loss_vq 为0，生成mel 不收敛

### ISSUE THREAD

**Issue by Naminwang** [fishaudio/fish-speech#171]
从头训练vqgan，发现代码里的fsq部分没有返回vq loss，vq_loss一直为0，且模型不收敛。
能否给一个从头训练vqgan的教程。
![image](https://github.com/fishaudio/fish-speech/assets/17474851/ede17f00-5a7b-4d20-a90f-ec70f98c66a4)

**Comment by leng-yue** [comment]
vq loss 为 0 是正常现象, 目测你的 loss 在正常区间.

**Comment by Naminwang** [comment]
> vq loss 为 0 是正常现象, 目测你的 loss 在正常区间.

训练了50k步，mel无法正常生成，麻烦帮忙看一下
![image](https://github.com/fishaudio/fish-speech/assets/17474851/b931c751-d2fb-49e7-832b-525fe6e85766)
