### ISSUE TITLE
[BUG] No module named tools.webui

### ISSUE THREAD

**Issue by TanZhili** [fishaudio/fish-speech#172]
"pip3 install -e ." succeed:
<img width="529" alt="image" src="https://github.com/fishaudio/fish-speech/assets/36952796/5438b5f6-19eb-4e17-a833-e92019d6ff99">

But "python -m tools.webui" failed:
No module named tools.webui

If directly run "python -m tools/webui.py", also failed:
ModuleNotFoundError: No module named 'tools.api'

Using "PYTHONPATH=./" doesn't help in both cases.

Environment:
CentOS, python3.10

**Comment by leng-yue** [comment]
You can run `python tools/webui.py` directly.

**Comment by TanZhili** [comment]
> You can run `python tools/webui.py` directly.

Sorry typo. If directly run "python tools/webui.py", also failed:
ModuleNotFoundError: No module named 'tools.api'

**Comment by leng-yue** [comment]
Are you using the latest code? We have pyrootutils built in

**Comment by sipie800** [comment]
+1
