### ISSUE TITLE
Wrong linked example

### ISSUE THREAD

**Issue by SebastianBodza** [fishaudio/fish-speech#174]
The example in: 
https://github.com/fishaudio/fish-speech/blob/6bcd4efc8d30b9ba744a0e61fae05df8279fbd67/docs/en/samples.md?plain=1#L158C49-L158C105
is linked wrong. Does not seem to be english.

**Comment by leng-yue** [comment]
Updating doc today

**Comment by leng-yue** [comment]
Done.
