### ISSUE TITLE
合成别的语言，比如藏语[Feature]

### ISSUE THREAD

**Issue by zazachao** [fishaudio/fish-speech#183]
这个是一个很棒的工作！我试过VALL-E-X，发现fish-speech的效果在中英文上表现更好，请问，我该如何微调能实现一些小语种语言的语音合成。是进行phonemizer的修改等一系列工作吗。再次感谢您的工作！

**Comment by Stardust-minus** [comment]
Fish-Speech不存在g2p环节，您只需要准备尽可能多的数据然后直接训练即可
