### ISSUE TITLE
Has anyone successfully run on macos?

### ISSUE THREAD

**Issue by Lynds-007** [fishaudio/fish-speech#187]

**Comment by leng-yue** [comment]
You may try CPU inference, no plan for mac accelerate support for now tho.

**Comment by leng-yue** [comment]
Hope #259 fixed this

**Comment by bookandlover** [comment]
Succefully start docker in MacOS, but it need GPU to train and inference.

**Comment by leng-yue** [comment]
Not sure if you can access mps in docker

**Comment by fast01** [comment]
there is a try that can run on win and  mac.  Try this :  https://blog.csdn.net/weixin_43935971/article/details/144435437
