### ISSUE TITLE
[BUG] create_train_split.py create wrong path when FT VITS

### ISSUE THREAD

**Issue by AliceNavigator** [fishaudio/fish-speech#189]
微调VITS时使用`python tools/vqgan/create_train_split.py data`创建的`vq_train_filelist.txt`内部路径类似
`data\Yanfei\vo_YFLQ001_11_yanfei_02.wav`
然而实际使用的路径是
`Yanfei\vo_YFLQ001_11_yanfei_02.wav`

如果直接使用分割脚本创建的路径会在Sanity Check时报错：
`RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.`

**Comment by leng-yue** [comment]
你是不是移动了 filelist? filelist 中的路径默认是音频与 filelist.parent 的相对位置.

**Comment by qianyoo** [comment]
> 微调VITS时使用`python tools/vqgan/create_train_split.py data`创建的`vq_train_filelist.txt`内部路径类似 `data\Yanfei\vo_YFLQ001_11_yanfei_02.wav` 然而实际使用的路径是 `Yanfei\vo_YFLQ001_11_yanfei_02.wav`
> 
> 如果直接使用分割脚本创建的路径会在Sanity Check时报错： `RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.`

大佬这个问题解决了吗，遇到相同问题了
