### ISSUE TITLE
可以进行前端干预吗？

### ISSUE THREAD

**Issue by wumingxiaozu103** [fishaudio/fish-speech#195]
在合成以下文本时，多音字的发音不够准确，想通过前端干预的方式指定发音，但是fish speech是字节建模，没有办法进行干预。

合成文本：人要是行，干一行，行一行。一行行，行行行；要是不行，干一行，不行一行。一行不行，行行不行。

有什么好的办法可以解决这个问题吗？

**Comment by leng-yue** [comment]
目前没办法.
