### ISSUE TITLE
[BUG] 使用prompt推理时，prompt和text的拼接方式存疑

### ISSUE THREAD

**Issue by WangGewu** [fishaudio/fish-speech#196]
![image](https://github.com/fishaudio/fish-speech/assets/35912578/f7ea89de-32ed-4500-b553-d8b34cd6f1ba)
encoded_prompts是prompt_text_token+prompt_semantic_token
partial_encoded是text_token
两者相加后：prompt_text_token+prompt_semantic_token+text_token，非prompt_text_token+text_token+prompt_semantic_token，与训练不一致。

**Comment by Stardust-minus** [comment]
应该不会导致特别大的问题。
cc@leng-yue

**Comment by leng-yue** [comment]
你开个 debugger 看看? 我验证过是没问题的

**Comment by WangGewu** [comment]
debug过，结论和我上面描述一致。我使用generate.py进行zero shot推理，生成的音频是有问题的。

**Comment by WangGewu** [comment]
> debug过，结论和我上面描述一致。我使用generate.py进行zero shot推理，生成的音频是有问题的。

按照0.1版本的generate修改encode_token函数后，就没问题了
![image](https://github.com/fishaudio/fish-speech/assets/35912578/3dcf1e9f-2db6-49f6-8b29-706b7f00330b)

**Comment by Stardust-minus** [comment]
> > debug过，结论和我上面描述一致。我使用generate.py进行zero shot推理，生成的音频是有问题的。
> 
> 按照0.1版本的generate修改encode_token函数后，就没问题了 ![image](https://private-user-images.githubusercontent.com/35912578/330339579-3dcf1e9f-2db6-49f6-8b29-706b7f00330b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODU1MDUsIm5iZiI6MTcxNTY4NTIwNSwicGF0aCI6Ii8zNTkxMjU3OC8zMzAzMzk1NzktM2RjZjFlOWYtMmRiNi00OWY2LThiMjktNzA2YjdmMDAzMzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDExMTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0OGJkZjQyOTljOGZmMzc5N2YyNTM0MGUwOWU4ZDZhZTA0ZjBiOTBkNWNjNzIxOTViZjgwZjU5ZjZhNmZjOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eanIDyQa09CyXjw4Al1aZf1913YbG7FIDolmfd3RAz4)

单纯修改此处没有观察到明显的推理差异

**Comment by leng-yue** [comment]
我重新确认了, global_encoded 和 [encoded_prompts] 是不 overlap 的, 其中 encoded_prompts 只来自 prompt 部分, 并且包含了完整的 text 和 semantic token. 不是特别理解您描述的问题在哪.

**Comment by WangGewu** [comment]
> 我重新确认了, global_encoded 和 [encoded_prompts] 是不 overlap 的, 其中 encoded_prompts 只来自 prompt 部分, 并且包含了完整的 text 和 semantic token. 不是特别理解您描述的问题在哪.

我意思是说，训练的时候，输入的拼接顺序是：text_token + semantic_token。在进行zero shot克隆推理时，输入的拼接顺序是否应该与训练保持一致，即：prompt_text_token+text_token+prompt_semantic_token；而非：prompt_text_token+prompt_semantic_token+text_token？

**Comment by leng-yue** [comment]
训练的时候是 text_token + semantic_token + text_token + semantic_token ... 这样的, 可以参考数据集 iterative 部分.
