### ISSUE TITLE
[Feature] why use a GroupVQ not a simple VQ ?

### ISSUE THREAD

**Issue by BridgetteSong** [fishaudio/fish-speech#197]
Can you try to compress mels to a token seq of shape [L, 1] by a simple VQ like VQ-VAE or FSQ not a GroupVQ? if some results you had made, what are reasons for using GVQ?

**Comment by leng-yue** [comment]
GVQ can include more info than naive one.

**Comment by BridgetteSong** [comment]
To keep more info in VQ, we can increase codebook size, egs from 1024 to 8192 like Tortoise, because a token seq of [L, 1] is easy for LM training and optimization. Have you tried to a simple VQ for FishSpeech training? Or in the beginning only GVQ is used?

**Comment by leng-yue** [comment]
Two 1024 codebooks = one 1024 * 1024 ~ 1M codebooks. It's not equal to a single codebook with 2048.
