### ISSUE TITLE
please add support for hindi language or documents 

### ISSUE THREAD

**Issue by iamjamilkhan** [fishaudio/fish-speech#203]
Hi any plan to add support for hindi language ?

**Comment by leng-yue** [comment]
Adding more languages is on our todos.

**Comment by MithrilMan** [comment]
what is needed to have an Italian voice?

**Comment by iamjamilkhan** [comment]
Added hindi support ?

**Comment by AnyaCoder** [comment]
not yet, please link us some resources :)

**Comment by tahercoolguy** [comment]
For hindi dataset i found 3K hours data . Is it sufficient to train . How much data is required for it .

**Comment by leng-yue** [comment]
Hindi is a very diversed language, likely at least 50k hours are required.
