### ISSUE TITLE
[Feature] Support Text dataset w/ and w/o spk

### ISSUE THREAD

**Issue by didadida-r** [fishaudio/fish-speech#205]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Is your feature request related to a problem? Please describe.**
Hi,
In text dataset, a group is only for a specifc speaker, a limited constrain to train the model. because there are still many data without speaker info, which can be used to train. 

1. Can the text dataset and gpt training & decoding support this feature.
2. In gpt training[pretrain stage], the spk info is not used, but only sentence with the same spk will be concated. So can i mix random spk data in a group and train the model.  Or is it necessary to pack same spk in a group?
3. Will the timber change very large even in finetuning stage with spk info if i train the model in mix spk way.

Many Thanks

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by leng-yue** [comment]
Based on our experiment, you can put all data in one group, and then use sft to recover the speaker following info.
