### ISSUE TITLE
How to train other ar model

### ISSUE THREAD

**Issue by didadida-r** [fishaudio/fish-speech#208]
Hi,

May I ask if i want to train other VQs, such as ar4 or ar8, do i only need to modify the config in vqgan?. Or do i need to modify the training and decoding code or config in gpt as well?

Thanks

**Comment by leng-yue** [comment]
Yes, if you want to change number of codebooks, you need to change the config in both vqgan and ar.

**Comment by didadida-r** [comment]
Thanks, So if the ar is 4, then the codebook size will be 1024^4, and the training data should be becoming rapidly larger? is that right
