### ISSUE TITLE
[BUG] inference load path

### ISSUE THREAD

**Issue by didadida-r** [fishaudio/fish-speech#209]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**

path load will fail in vqgan infer, convert Path to str

audio, sr = torchaudio.load(input_path) -> audio, sr = torchaudio.load(str(input_path))

https://github.com/fishaudio/fish-speech/blob/0df704bf9b187fa150a1e77c38741a1cb03da2d0/tools/vqgan/inference.py#L72

**To Reproduce**

**Expected behavior**

**Screenshots / log**
If applicable, add screenshots / logs to help explain your problem.

**Additional context**

**Comment by leng-yue** [comment]
What;s the version of torchaudio you are using?

**Comment by didadida-r** [comment]
the version is 
```
torch                     2.2.0
torchaudio                2.2.0
```
