### ISSUE TITLE
Optimize chinese text normalization

### ISSUE THREAD

**Issue by faceair** [fishaudio/fish-speech#21]
The current logic of `text_normalize` is not capable of correctly processing scenarios involving years.

```python
def text_normalize(text):
    numbers = re.findall(r"\d+(?:\.?\d+)?", text)
    for number in numbers:
        text = text.replace(number, cn2an.an2cn(number), 1)
    return text
```

If you plan to continue using `cn2an`, you should consider using the [transform](https://github.com/Ailln/cn2an?tab=readme-ov-file#33-%E5%8F%A5%E5%AD%90%E8%BD%AC%E5%8C%96) method.

Alternatively, consider using [WeTextProcessing](https://github.com/wenet-e2e/WeTextProcessing) for processing. From my perspective, it seems like WeTextProcessing appears to be [more professional](https://github.com/wenet-e2e/WeTextProcessing/tree/master/tn).

**Comment by faceair** [comment]
`WeTextProcessing` does not process phonemes, it only deals with raw text.

**Comment by leng-yue** [comment]
Cool, can you make a PR? We can evaluate that.

**Comment by leng-yue** [comment]
Thanks for your contribution. Tested and merged.

**Comment by leng-yue** [comment]
I found that cn2an has another function that process year correctly, considering using it as fallback for windows users. #45
