### ISSUE TITLE
when I train vits_decoder_fintune, error occurs

### ISSUE THREAD

**Issue by caiduoduo12138** [fishaudio/fish-speech#212]
llama finetune  works fine, but vits_decoder_fintune seems has some error. If possible, give me some advice
![image](https://github.com/fishaudio/fish-speech/assets/55495912/7f1069b4-b57f-4d23-ad8c-4eedae962ed4)

**Comment by wblgers** [comment]
It seems the data path is not correct.

**Comment by caiduoduo12138** [comment]
> It seems the data path is not correct.
![image](https://github.com/fishaudio/fish-speech/assets/55495912/2fc84c10-028b-4d3e-ba2a-4f3a98cbf125)
![image](https://github.com/fishaudio/fish-speech/assets/55495912/2fce8e9a-72cf-4b15-aa9f-e4a653d7bb76)

**Comment by caiduoduo12138** [comment]
> > It seems the data path is not correct.
here is my dataset path
> > ![image](https://private-user-images.githubusercontent.com/55495912/331106810-2fc84c10-028b-4d3e-ba2a-4f3a98cbf125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDY3MjAsIm5iZiI6MTcxNTg0NjQyMCwicGF0aCI6Ii81NTQ5NTkxMi8zMzExMDY4MTAtMmZjODRjMTAtMDI4Yi00ZDNlLWJhMmEtNGYzYTk4Y2JmMTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA4MDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0Yjk3MTg3NjZkNGIzY2UxNzVlMWQxMTQ3MDc3YTBlOTNjNDk1ZTBlY2I2YjVkZDVmZjM1MWMyYTU5MzI4NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GV5OKhf11oC3E7HIwptkLAWDWnWUrBMCLVb1VUOQJBs)
> > ![image](https://private-user-images.githubusercontent.com/55495912/331106951-2fce8e9a-72cf-4b15-aa9f-e4a653d7bb76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDY3MjAsIm5iZiI6MTcxNTg0NjQyMCwicGF0aCI6Ii81NTQ5NTkxMi8zMzExMDY5NTEtMmZjZThlOWEtNzJjZi00YjE1LWFhOWYtZTRhNjUzZDdiYjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA4MDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNjIwYjVmN2Y3ODdhODM0YzhlY2Y4MTMxNjM5YzM2MjljYmUyZmFkYTY4NDY0ZTJkNWFjZGZiZmExNTQyNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BF9e_eSYdH1MdlH7IQC8hNXtWF9yj3Myvx0GPmszGZE)

**Comment by wblgers** [comment]
I encountered this issue once, and I work around it by add one line code at line 36 of fish_speech/datasets/vits.py:
`root = Path("./")`

You can try this, or you can add some log on line 40 to print out the `path`

**Comment by caiduoduo12138** [comment]
> I encountered this issue once, and I work around it by add one line code at line 36 of fish_speech/datasets/vits.py: `root = Path("./")`
> 
> You can try this, or you can add some log on line 40 to print out the `path`

thanks
