### ISSUE TITLE
hydra.errors.InstantiationException: Error in call to target 'fish_speech.models.vqgan.modules.firefly.FireflyBase': FileNotFoundError(2, 'No such file or directory') full_key: model.vocoder[BUG]

### ISSUE THREAD

**Issue by wuye901126** [fishaudio/fish-speech#213]
hydra.errors.InstantiationException:
Error in call to target 'fish_speech.models.vqgan.modules.firefly.FireflyBase':
FileNotFoundError(2, 'No such file or directory')
full_key: model.vocoder

![1715845222260](https://github.com/fishaudio/fish-speech/assets/24641901/962d36e2-8254-41e2-bf8c-8a12a479f56b)

**Comment by Stardust-minus** [comment]
You need to download firefiygan and place it in checkpoints folder

**Comment by wuye901126** [comment]
![1715935717367](https://github.com/fishaudio/fish-speech/assets/24641901/82ae84e5-a123-4d55-93bd-96f27f6fc257)

**Comment by leng-yue** [comment]
https://github.com/fishaudio/fish-speech/blob/843c128d21ebb9c0b173715f6bbf9c77a86349be/tools/api.py#L369

There is no way it's not defined... Please check if you edit some code.
