### ISSUE TITLE
[BUG] 加入参考音就报错

### ISSUE THREAD

**Issue by 188140040** [fishaudio/fish-speech#215]
![QQ图片20240516222344](https://github.com/fishaudio/fish-speech/assets/31399799/783021b0-f527-4628-a6a3-517c770175e2)
![QQ图片20240516222350](https://github.com/fishaudio/fish-speech/assets/31399799/de00cead-6ec0-4d1f-98d5-e3d3f97294c7)

一直报错无法使用。。

**Comment by SapphireLab** [comment]
稍微定位了一下，原因是 Python 3.12 版本中对其内置的 random 模块的 `randrange()` 函数做了修改：对于非整数的 `stop` 值将会抛出类型错误, 如图中的 `1e7` 就是浮点数类型, 而旧版的会做取整处理, 新版没有.

所以解决方案有:
1. 降低 Python 版本 (推荐, 因为不知道还会不会有别的问题)
2. 报错里倒数第三个文件 `site-packages\vector_quantize_pytorch\residual_fsq.py` 代码里 `random.randint(0, 1e7)` 的 `1e7` 改成 `10_000_000` 或 `int(1e7)`.

**Comment by leng-yue** [comment]
辛苦了, 我给上游提了个 pr, 希望他们尽快合并

**Comment by SapphireLab** [comment]
是没想过的角度(

**Comment by leng-yue** [comment]
他们 merge 了, 我晚点更新下版本
