### ISSUE TITLE
about sft model

### ISSUE THREAD

**Issue by zshy1205** [fishaudio/fish-speech#217]
what is sft model?
in text2semantic_sft.yaml, it have 
"
ckpt_path: checkpoints/text2semantic-medium-v1-2k.pth
resume_weights_only: true
"
What is the difference between sft and without sft?

**Comment by leng-yue** [comment]
For large data, there is no lots of difference. But if your data is less than 1 hour, it's recommend to begin with sft model.

**Comment by matbee-eth** [comment]
> what is sft model? in text2semantic_sft.yaml, it have " ckpt_path: checkpoints/text2semantic-medium-v1-2k.pth resume_weights_only: true " What is the difference between sft and without sft?

"Supervised fine-tuning" is just meaning the dataset is curated and defined in a way that the model is adjusted explicitly. Unsupervised fine tuning means youre just throwing a ton of data at the model and eventually it'll make sense of it.
