### ISSUE TITLE
[Feature]能否提供api的使用文档及示例，比如说对接开源阅读tts之类的例子？

### ISSUE THREAD

**Issue by beavermarine** [fishaudio/fish-speech#222]
作为新手小白看api很痛苦，不知道各位大佬能否提供一些说明文档和使用例子？

**Comment by leng-yue** [comment]
Merge #216

**Comment by leng-yue** [comment]
可以提供一个 python example

**Comment by AnyaCoder** [comment]
这是示例，支持流式或非流式合成：
![image](https://github.com/fishaudio/fish-speech/assets/122108331/4ed3d3a4-9563-44ba-9d49-6a25879441b1)
代码已pr

**Comment by unlimit999** [comment]
阅读的话，我自己是用tool/webui.py那个文件另外改了一个
```python
import argparse
import fastapi
import gc
import gradio
import hashlib
import io
import librosa
import loguru
import numpy
import pathlib
import queue
import soundfile
import tempfile
import torch
import transformers
import urllib
import uvicorn
import wave

# 加載自定義模塊
from tools.api import decode_vq_tokens
from tools.api import encode_reference
from tools.llama.generate import GenerateRequest
from tools.llama.generate import GenerateResponse
from tools.llama.generate import WrappedGenerateResponse
from tools.llama.generate import launch_thread_safe_queue
from tools.vqgan.inference import load_model as load_decoder_model

# 初始化參數
temp_files = {}
app = fastapi.FastAPI()


def wav_chunk_header(sample_rate=44100, bit_depth=16, channels=1):
    buffer = io.BytesIO()

    with wave.open(buffer, "wb") as wav_file:
        wav_file.setnchannels(channels)
        wav_file.setsampwidth(bit_depth // 8)
        wav_file.setframerate(sample_rate)

    wav_header_bytes = buffer.getvalue()
    buffer.close()
    return wav_header_bytes


@torch.inference_mode()
def inference(text, enable_reference_audio, reference_audio, reference_text, max_new_tokens, chunk_length, top_p, repetition_penalty, temperature, speaker, streaming=False, ):

    if args.max_gradio_length > 0 and len(text) > args.max_gradio_length:
        return (None, None, f"文本太长，请将其控制在{args.max_gradio_length}个字符以内。")

    # Parse reference audio aka prompt
    prompt_tokens, reference_embedding = encode_reference(decoder_model=decoder_model, reference_audio=reference_audio, enable_reference_audio=enable_reference_audio, )

    # LLAMA Inference
    request = dict()
    request["tokenizer"]=llama_tokenizer
    request["device"]=decoder_model.device
    request["max_new_tokens"]=max_new_tokens
    request["text"]=text
    request["top_p"]=top_p
    request["repetition_penalty"]=repetition_penalty
    request["temperature"]=temperature
    request["compile"]=args.compile
    request["iterative_prompt"]=chunk_length > 0
    request["chunk_length"]=chunk_length
    request["max_length"]=args.max_length
    request["speaker"]=speaker if speaker else None
    request["prompt_tokens"]=prompt_tokens if enable_reference_audio else None
    request["prompt_text"]=reference_text if enable_reference_audio else None

    response_queue = queue.Queue()
    llama_queue.put(GenerateRequest(request=request, response_queue=response_queue, ))

    if streaming:
        yield wav_chunk_header(), None, None

    segments = []

    while True:
        result: WrappedGenerateResponse = response_queue.get()
        if result.status == "error":
            yield None, None, "build_html_error_message(result.response)"
            break

        result: GenerateResponse = result.response
        if result.action == "next":
            break

        text_tokens = llama_tokenizer.encode(result.text, return_tensors="pt").to(decoder_model.device)

        with torch.autocast(device_type=decoder_model.device.type, dtype=args.precision):
            fake_audios = decode_vq_tokens(decoder_model=decoder_model, codes=result.codes, text_tokens=text_tokens, reference_embedding=reference_embedding, )

        fake_audios = fake_audios.float().cpu().numpy()
        segments.append(fake_audios)

        if streaming:
            yield (fake_audios * 32768).astype(numpy.int16).tobytes(), None, None

    if len(segments) == 0:
        return (None, None, "沒有生成音頻，請檢查輸入的文本。")

    # No matter streaming or not, we need to return the final audio
    audio = numpy.concatenate(segments, axis=0)
    yield None, (decoder_model.sampling_rate, audio), None

    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        gc.collect()


@app.post("/tts")
async def tts(req: fastapi.Request):

    data = await req.json()
    data["text"] = urllib.parse.unquote_plus(data["text"])
    data_hash = hashlib.md5(str(data).encode()).hexdigest()

    if data_hash in temp_files:
        return fastapi.responses.FileResponse(temp_files[data_hash], media_type=f'audio/wav')
    else:
        sr, audio_data = next(inference(text=data["text"], enable_reference_audio=data["enable_reference_audio"], reference_audio=data["reference_audio"], reference_text=data["reference_text"], max_new_tokens=data["max_new_tokens"], chunk_length=data["chunk_length"], top_p=data["top_p"], repetition_penalty=data["repetition_penalty"], temperature=data["temperature"], speaker=data["speaker"], streaming=data["streaming"], ))[1]
        with tempfile.NamedTemporaryFile(delete=False, suffix=".wav") as tmp_file:
            soundfile.write(tmp_file, audio_data, sr, format="wav")
            tmp_file_path = tmp_file.name
            temp_files[data_hash] = tmp_file_path
        return fastapi.responses.FileResponse(tmp_file_path, media_type="audio/wav")


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--llama-checkpoint-path", type=pathlib.Path, default="checkpoints/text2semantic-sft-medium-v1-4k.pth")
    parser.add_argument("--llama-config-name", type=str, default="dual_ar_2_codebook_medium")
    parser.add_argument("--decoder-checkpoint-path", type=pathlib.Path, default="checkpoints/vq-gan-group-fsq-2x1024.pth")
    parser.add_argument("--decoder-config-name", type=str, default="vqgan_pretrain")
    parser.add_argument("--tokenizer", type=str, default="fishaudio/fish-speech-1")
    parser.add_argument("--device", type=str, default="cuda")
    parser.add_argument("--half", action="store_true")
    parser.add_argument("--max-length", type=int, default=2048)
    parser.add_argument("--compile", action="store_true")
    parser.add_argument("--max-gradio-length", type=int, default=0)
    parser.add_argument("--listen", type=str, default="127.0.0.1:8000")
    parser.add_argument("--share-token", type=str, default=None)
    return parser.parse_args()


if __name__ == "__main__":

    args = parse_args()
    args.precision = torch.half if args.half else torch.bfloat16
    llama_tokenizer = transformers.AutoTokenizer.from_pretrained(args.tokenizer)

    loguru.logger.info("正在加载Llama模型...")
    llama_queue = launch_thread_safe_queue(config_name=args.llama_config_name, checkpoint_path=args.llama_checkpoint_path, device=args.device, precision=args.precision, max_length=args.max_length, compile=args.compile, )

    loguru.logger.info("正在加载VQ-GAN模型...")
    decoder_model = load_decoder_model(config_name=args.decoder_config_name, checkpoint_path=args.decoder_checkpoint_path, device=args.device, )

    loguru.logger.info(f"加载完成，服务器已启动:http://{args.listen}")

    listen = args.listen.split(":")
    host=listen[0]
    port=int(listen[1])
    share_url=gradio.networking.setup_tunnel(local_host=host, local_port=port, share_token= args.share_token, share_server_address= None)
    loguru.logger.info(f"加载完成，服务器已启动:{share_url}")
    uvicorn.run(app=app, host=host, port=port)
``` 
把这个另存为"阅读_api.py"，放到此项目的根目录
(跟start.bat同位置


```batchfile
@echo off
cd .\fish-speech

chcp 65001
echo 打开API...
..\pyenv\python "阅读_api.py" ^
--llama-checkpoint-path "checkpoints\text2semantic-sft-large-v1.1-4k.pth" ^
--llama-config-name "dual_ar_2_codebook_large" ^
--decoder-checkpoint-path "checkpoints\vits_decoder_v1.1.ckpt" ^
--decoder-config-name "vits_decoder_finetune" ^
--tokenizer "checkpoints" ^
--device "cuda" ^
--half ^
--max-length 2048 ^
--max-gradio-length 0 ^
--listen "127.0.0.1:8000"
--share-token "这个必须填!!!"
cmd "pause"
``` 
另存为bat档，注意：bat档需要改3处

一、cd .\fish-speech
.\fish-speech改成这个项目的根目录

二、..\pyenv\python "阅读_api.py" ^
..\pyenv修改成自己python安装的位置

三、--share-token "这个必须填!!!"
把字串改成字定义的英数字组合，此为种子，用来生成固定公网域名

其它参数也是可以改的，视自己需求而定，不懂的话就保持不动
然后点开这个bat执行就算是本地部属完毕了


接著在阅读3.0中tts设定：
![朗读引擎](https://github.com/fishaudio/fish-speech/assets/8715419/d5bc92cc-7c15-4143-a542-dc12b85148ab)

遮住的部份每个人不一样，根据你bat里填的种子生成域名
参考音频、参考文本要自己设定

设定完就用了，不用同一区网也可以，用的是gradio提供的免费内网穿透
不过该域名只能保持三天，三天之后要重启伺服器端

**Comment by AnyaCoder** [comment]
不用fastapi, 用官方自带的kui，待会放上示例

**Comment by unlimit999** [comment]
> @unlimit999抱歉，我需要優先確保官方裝備，先刪除，你可以 在 我 後面補充`API_FLAGS.txt`。 ![影像](https://private-user-images.githubusercontent.com/122108331/331851134-a50fbd51-ee2c-4b14-aaed-015eae3a7472.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTEyMTgsIm5iZiI6MTcxNjExMDkxOCwicGF0aCI6Ii8xMjIxMDgzMzEvMzMxODUxMTM0LWE1MGZiZDUxLWVlMmMtNGIxNC1hYWVkLTAxNWVhZTNhNzQ3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwOTI4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMGZhZWRhMTRlZWI2ZDM2YzA5ZmM5OWY3YWJkNjk3YTFkYmQ1NDYyZWNjZjAzMDEwOWMwYTY0NTM3YzMzZWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XA8EOFJ2b0p2M4oGVRl86W4hdBf6xBlS4WwfEPI9EVc)`start.bat` ![影像](https://private-user-images.githubusercontent.com/122108331/331851305-a7f99e90-c85a-4e5f-8504-8eda371e1e60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTEyMTgsIm5iZiI6MTcxNjExMDkxOCwicGF0aCI6Ii8xMjIxMDgzMzEvMzMxODUxMzA1LWE3Zjk5ZTkwLWM4NWEtNGU1Zi04NTA0LThlZGEzNzFlMWU2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwOTI4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTk5MTQxODU1NjliNThlZTk2OTk2MDg0ZGFiMmFlNjU2YWQ0ZDZkYmIwNDUyYzczZmU0MWYzNGUyMTZlNmE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1fhOdrQJ4-QHdlklKoCdlavl7qvcTBYuDDBQtt1Ey5M)
> 
> 然後開啟電腦的網路設定 ![影像](https://private-user-images.githubusercontent.com/122108331/331851156-56176c1b-6342-468d-bb67-edef8e186744.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTEyMTgsIm5iZiI6MTcxNjExMDkxOCwicGF0aCI6Ii8xMjIxMDgzMzEvMzMxODUxMTU2LTU2MTc2YzFiLTYzNDItNDY4ZC1iYjY3LWVkZWY4ZTE4Njc0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwOTI4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjZhNGM4MzNlYjlhOTYzMGMyN2IyZmQ0MTJhZThmODlmMDljYTdhZTI0NDg3ZmI2NjIzYjU4MzU5MDcyZTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y8Dkvzw6ydYMRO7Ngh9MjaFGvWZ5B0UBNqW9IJxVYaE)
> 
> 查詢IP位址 ![影像](https://private-user-images.githubusercontent.com/122108331/331851177-66e80385-6b90-4817-8da3-831ccaac4cc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTEyMTgsIm5iZiI6MTcxNjExMDkxOCwicGF0aCI6Ii8xMjIxMDgzMzEvMzMxODUxMTc3LTY2ZTgwMzg1LTZiOTAtNDgxNy04ZGEzLTgzMWNjYWFjNGNjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwOTI4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDg4YWI1ZjY1ZjYzMGYwNGQyMzRhYzg0NzQzZDgzMDUyNWY0OTgzMjI2NjU1NWUwOTdlZTk3ZWE2MTExMDJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qPk45qpKVx9-Ss4F3iymDojrJ8zzL6soyYOhNHc9Eeg)
> 
> 然後開啟「開源閱讀」APP，依照上述IP填寫資訊如下即可開始朗讀。 ![04f671f55491e3d0949cd0130bc59e11](https://private-user-images.githubusercontent.com/122108331/331851101-ba77fb1e-5673-46f0-96cc-3e8f6a1ea251.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTEyMTgsIm5iZiI6MTcxNjExMDkxOCwicGF0aCI6Ii8xMjIxMDgzMzEvMzMxODUxMTAxLWJhNzdmYjFlLTU2NzMtNDZmMC05NmNjLTNlOGY2YTFlYTI1MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwOTI4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDQxNzMwZjc2MzkzNjdlNDJjMWYzYzc5YjVkY2VkOTIyZjY0YWVhNmQ4YjBmZGMwNThiODUyNmE5ODRmZThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WWEtOJU1sHj3LOTdhZ8411rUY606-7nQy5p2LEa_1jA)

我照这个设置了后，阅读发送请求的时候，伺服器端那边是有正常跑，不会报错

但阅读不会念，执行了5次之后显示
"TTS伺服器连续5次错误，已停止阅读"

**Comment by AnyaCoder** [comment]
<img width="867" alt="4b437fb836e3498f72e9ef6302c5753" src="https://github.com/fishaudio/fish-speech/assets/122108331/720a4f4b-f4bb-45c8-89f0-9bbd1ee957eb">
![729c25df0beea2d3badfb3cb02558c9](https://github.com/fishaudio/fish-speech/assets/122108331/82d07dc4-b16e-49ca-9a26-95ba263d5da0)
经过测试，是没问题的，要对api.py进行一些修改，详情请见最新PR。

**Comment by unlimit999** [comment]
> 
> 经过测试，是没问题的，要对api.py进行一些修改，详情请见最新PR。

刚刚19:45重新拉取了一遍新的pr

照著上面的设置...
![1](https://github.com/fishaudio/fish-speech/assets/8715419/c6bdd51b-2660-4747-8836-150cd5ee7d00)
![2](https://github.com/fishaudio/fish-speech/assets/8715419/20d82588-e264-459a-8361-983b9f9b3261)

然后伺服器端是有正常接收到请求，并且正常推理的
![螢幕擷取畫面 2024-05-19 195938](https://github.com/fishaudio/fish-speech/assets/8715419/ffba68ef-e306-4683-abf9-257e83e5bc91)

但阅读那边还是没声音，连续推理5个段落没声音之后就报错暂停了
难道是阅读版本的问题？  我用的是阅读3.23.110211版本

**Comment by AnyaCoder** [comment]
![image](https://github.com/fishaudio/fish-speech/assets/122108331/0776892b-6740-4b3e-aaee-4418264e6120)
`Content-Type`改成`audio/wav`

**Comment by leng-yue** [comment]
这块用 octet-stream 是保证 swagger 不会显示 audio element, 那个模块是坏的

**Comment by beavermarine** [comment]
> <img alt="4b437fb836e3498f72e9ef6302c5753" width="867" src="https://private-user-images.githubusercontent.com/122108331/331867095-720a4f4b-f4bb-45c8-89f0-9bbd1ee957eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDg1NTQsIm5iZiI6MTcxNjMwODI1NCwicGF0aCI6Ii8xMjIxMDgzMzEvMzMxODY3MDk1LTcyMGE0ZjRiLWY0YmItNDVjOC04OWYwLTliYmQxZWU5NTdlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxNjE3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTAyY2VjNDE2NTlkZmMwODk1M2I4MWJmYmYwOWZjYWU5ZjY3NmNhZTRhMzIyOGY3YzE1OWI4NTQ3NTEwZTM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DXrhkTwTFnxDVqwa3xO3kPuPcPD3AkTpqkKC6IvR2rw">
> 
> 经过测试，是没问题的，要对api.py进行一些修改，详情请见最新PR。

使用阅读能够正常推理并播放，但是随机性过大，请问如何使用参考音频和文本？

**Comment by AnyaCoder** [comment]
使用参考音频和文本时，需要做如下步骤：
0. 更新代码。
1. 项目根目录下创建一个`ref_data`文件夹，然后创建一些角色名命名的文件夹
![image](https://github.com/fishaudio/fish-speech/assets/122108331/f6e980e9-d20c-4d86-90a6-eaac5c6859f9)
2. 给音频的情绪分好类，放到不同的情绪命名的子文件夹中。要求同时有`.lab`标注文件和`.wav`音频文件。
![image](https://github.com/fishaudio/fish-speech/assets/122108331/50c39df5-e58f-4102-9172-eeb9ee68c39d)
3. 点击`run_cmd.bat`, 输入
```python
python tools\gen_ref.py
```
这会产生一个`ref_data.json`文件，里面存放的是用到的音频和标注路径。
5. 将`API_FLAGS.txt`设置如下:
![image](https://github.com/fishaudio/fish-speech/assets/122108331/960ed618-b56d-4193-b061-55fb30a86beb)
6. 点击`start.bat`运行api服务器。
7. 回到开源阅读，配置如下：
配置说明：跟第1步的配置有关。声源：胡桃，情绪：happy。效果：随机选择happy文件夹下的一条音频作为参考。
![31dc947f308dff527bb0d7e98e793c1](https://github.com/fishaudio/fish-speech/assets/122108331/64da75bf-b8ed-4eb5-9b68-ce7dad4a0f3b)
9. Enjoy!
![image](https://github.com/fishaudio/fish-speech/assets/122108331/b57f7f0b-c666-42ee-a3db-b46b34fb6c0d)
