### ISSUE TITLE
[BUG]使用API接口进行推理，参考音频是女生，生成的是男生

### ISSUE THREAD

**Issue by wuye901126** [fishaudio/fish-speech#224]
使用API接口进行推理，参考音频是女生，生成的是男生

**Comment by leng-yue** [comment]
有更多的信息吗? 比如参考音频, 模型版本等.

**Comment by wuye901126** [comment]
都是用的默认的，在webui 上推理正常Api 上面就没效果

**Comment by wuye901126** [comment]
准确来说，应该是设置了参考音频，但是没有生效

**Comment by wuye901126** [comment]
> 还有更多信息吗？例如参考音频、模型版本等。

python -m tools.api --listen 0.0.0.0:8000 --llama-checkpoint-path "checkpoints/text2semantic-sft-medium-v1.1-4k.pth" --llama-config-name dual_ar_2_codebook_medium --decoder-checkpoint-path "checkpoints/vq-gan-group-fsq-2x1024.pth" --decoder-config-name vqgan_pretrain   使用的是这个命令启动的

**Comment by wuye901126** [comment]
> 有更多的信息吗? 比如参考音频, 模型版本等.

添加了参考音频，但是生成出来的音频应该是使用了随机音频

**Comment by AnyaCoder** [comment]
用现在这个api试试？

**Comment by lonngxiang** [comment]
上传参考音频怎么报错？{"statusCode":500,"message":"[Errno 2] No such file or directory: 'C:\\\\Users\\\\loong\\\\Downloads\\\\aa.wav'","error":"Internal Server Error"}
![image](https://github.com/fishaudio/fish-speech/assets/40717349/f85d5dd0-9cf0-4d8e-acc2-2b80b7016fcd)

**Comment by yc930401** [comment]
我也遇到了同样的问题，Api启动，参考音频是女生，每次运行都是不同的男生输出。

**Comment by AnyaCoder** [comment]
用现在这个`inference.ipynb`试试？

**Comment by kqdlx3** [comment]
the most rubbish project i have seen
