### ISSUE TITLE
[Feature] 使用更大的语言模型

### ISSUE THREAD

**Issue by CloudTronUSA** [fishaudio/fish-speech#229]
用上了 LLAMA 1b 模型之后，对比以前的小模型(GPT SOVITS 的 AR) 在读音和语气上有了明显的提升
请问如果没有硬件限制的情况下，使用更大的模型（如7b/13b）会对合成效果有明显提升吗？

**Comment by CloudTronUSA** [comment]
啊，原来是这样
如果要做的话具体来说是需要增加后面微调的数据量，还是Base Model的数据量，还是两个都要呢？

**Comment by leng-yue** [comment]
base 的就行

**Comment by CloudTronUSA** [comment]
请问你们现在的base是用了多少数据呢？

**Comment by wzy0421** [comment]
如果用GPT4不微调直接生成，效果行吗
