### ISSUE TITLE
it can't reproduce demo's result?

### ISSUE THREAD

**Issue by sunnnnnnnny** [fishaudio/fish-speech#23]
i use default code and pretrained models from [https://speech.fish.audio/zh/](url), but i don't generate result that [https://speech.fish.audio/zh/samples/](url);The only difference is that I renamed the file `https://huggingface.co/fishaudio/speech-lm-v1/blob/main/tokenizer_config.json` to `config.json`, and found that the id corresponding to pad_token is 36407, not 32311. The audio it generates has a lot of repetitions.Below is my inference code.
```
text='人间灯火倒映湖中，她的渴望让静水泛起涟漪。若代价只是孤独，那就让这份愿望肆意流淌。流入她所注视的世间，也流入她如湖水般澄澈的目光。'
#<<8
python tools/vqgan/inference.py \
    -i "/tmp/xxx/naxita.wav" \
    --checkpoint-path "/tmp/xxx/fishaudio-speech-lm-v1-pretrained/vqgan-v1.pth"

#8
#<<8
python tools/llama/generate.py \
    --text ${text} \
    --prompt-text ${text}\
    --prompt-tokens "fake.npy" \
    --checkpoint-path "/tmp/xxx/fishaudio-speech-lm-v1-pretrained/text2semantic-400m-v0.2-4k.pth" \
    --tokenizer "/tmp/xxx/fishaudio-speech-lm-v1-pretrained" \
    --num-samples 2 \
    --compile
#8

#<<8
python tools/vqgan/inference.py \
    -i "codes_0.npy" \
    --checkpoint-path "/tmp/xxx/fishaudio-speech-lm-v1-pretrained/vqgan-v1.pth"
#8
```

**Comment by OedoSoldier** [comment]
Use `--speaker` argument when generating mel tokens

**Comment by sunnnnnnnny** [comment]
thank you reply;i do that add `--speaker "纳西妲" for step 2`, but results also have a lot of repetitions;

**Comment by sunnnnnnnny** [comment]
ok; i see it;thanks a lot.

**Comment by Liujingxiu23** [comment]
@leng-yue  我测试一步步 inference vq的时候，有如下错误：
le.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VQGAN:

是不是我configs设置的不对，默认的fish_speech/configs 是可以的吗？ 我看这里面有
vqgan_finetune.yaml   vqgan_pretrain.yaml  vqgan_pretrain_v2.yaml？

**Comment by leng-yue** [comment]
用前面两个. 如果不行, 麻烦把报错信息的 traceback 发全.
