### ISSUE TITLE
RuntimeError: The expanded size of the tensor (2048) must match the existing size (3882) at non-singleton dimension 1.  Target sizes: [3, 2048].  Tensor sizes: [3, 3882][BUG]

### ISSUE THREAD

**Issue by wuye901126** [fishaudio/fish-speech#232]
在使用这个命令的时候 报错python tools/llama/generate.py --text "床前明月光，疑似地上霜。举头望明月，低头思故乡" --prompt-text "1234567" --prompt-tokens "fake.npy" --config-name dual_ar_2_codebook_medium --checkpoint-path "checkpoints/text2semantic-sft-medium-v1.1-4k.pth" --num-samples 2 --compile

**Comment by Json0926** [comment]
有解决方案吗 这个问题
