### ISSUE TITLE
说话人会有概率加入到语音生成出来[BUG]

### ISSUE THREAD

**Issue by only-ns** [fishaudio/fish-speech#233]
![image](https://github.com/fishaudio/fish-speech/assets/42288790/a6a6d92f-15e0-4097-acec-eaab791e26b8)

https://huggingface.co/spaces/fishaudio/fish-speech-1 （webui）
这是推理出来的音频，复现概率很高（这个说话人是为了提高复现概率）
[wav](https://fishaudio-fish-speech-1.hf.space/file=/tmp/gradio/aab5417c350356cafcc24fedf58edcba7be7383a/audio.wav)

**Comment by Stardust-minus** [comment]
这是因为说话人是以token形势嵌入推理序列的。临时的解决办法是不指定说话人，只使用ref

**Comment by leng-yue** [comment]
说话人 OOD 了...

**Comment by Stardust-minus** [comment]
> 说话人 OOD 了...

不认可，集内说话人也有概率
