### ISSUE TITLE
Docker Tutorial

### ISSUE THREAD

**Issue by 10ANT** [fishaudio/fish-speech#238]
I'm humbly requesting a docker tutorial for this, because I'm a noob to docker and I spent several hours trying to figure out how to get the container to run locally via port forwarding, and to no avail I'm still struggling. Thank you

**Comment by leng-yue** [comment]
You may want to check docker document for info about port forwarding...

**Comment by lonngxiang** [comment]
expect

**Comment by monkeyGeek369** [comment]
通过docker成功启动程序，也开启了webui，但是奇怪的是容器内可以访问127.0.0.1:7860但是宿主机无法访问。
1、已经做了端口映射，无效
2、容器采用host模式，无效
3、容器内可以ping通宿主机，但宿主机无法ping通容器ip
