### ISSUE TITLE
about VQ

### ISSUE THREAD

**Issue by zshy1205** [fishaudio/fish-speech#239]
VQ is trained using VQGAN. In fact, VQ contains speaker information. 
I think semantic token should not contain speaker information.

**Comment by leng-yue** [comment]
It's expected for VQ to contain speaker info.

**Comment by zshy1205** [comment]
> It's expected for VQ to contain speaker info.

However, in vits-decoder, there is also reference audio. According to my assumption, if semantic token does not contain speaker information, then during vits-decoder inference, just change ref-wav to get the audio of ref-wav pronunciation. However, the current vq cannot do this because vq itself is bound to the speaker.

**Comment by leng-yue** [comment]
It's hard to disentangle speaker info tho
