### ISSUE TITLE
[Feature] autoDL中，加了很多工具和教程，请问能提供下在自己的机器上如何准备这些么，不太方便用auto DL啊

### ISSUE THREAD

**Issue by chg0901** [fishaudio/fish-speech#240]
B站的教程（https://www.bilibili.com/video/BV1wH4y1373n/）里，看到在autoDL中的镜像，加了很多工具和教程，请问能提供下在自己的机器上如何准备这些的方法么，不太方便用auto DL啊

还有一个问题，https://github.com/fishaudio/fish-speech/blob/main/tools/download_models.py 中的这三个文件‘ffmpeg.exe ffprobe.exe asr-label-win-x64.exe’，可以介绍下使用方法么

语音小白，麻烦介绍下， 谢谢啦

**Comment by AnyaCoder** [comment]
现在可以用一键安装脚本。看文档有教程。
