### ISSUE TITLE
每次推理效果不一样[Feature]

### ISSUE THREAD

**Issue by Ranzige** [fishaudio/fish-speech#243]
作者您好，你的这个项目太棒了，请问相同的模型，相同的参考音频，相同的合成文本，为什么每次合成的音频效果是不一样的，有什么方法能规避此问题吗。

**Comment by Stardust-minus** [comment]
WebUI推理种子随机，想一样的话固定种子即可

**Comment by Ranzige** [comment]
请问固定种子是什么意思，能详细说明吗

**Comment by leng-yue** [comment]
WebUI 暂时不支持, 如果你用命令行生成, 可以指定 --seed 参数, 保证每次推理结果一致.

**Comment by DoiiarX** [comment]
> WebUI 暂时不支持, 如果你用命令行生成, 可以指定 --seed 参数, 保证每次推理结果一致.

后续有考虑支持吗？
