### ISSUE TITLE
[BUG]vits和vqgan在自定义数据集上训练后的效果不佳

### ISSUE THREAD

**Issue by pangr** [fishaudio/fish-speech#248]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / log**
If applicable, add screenshots / logs to help explain your problem.

**Additional context**

我们在自己的数据集上训练了vits和vqgan，但是出来的效果很差，说话人吐字不清，就是有大舌头一样

[fake_6000.zip](https://github.com/fishaudio/fish-speech/files/15452266/fake_6000.zip)
[fake_200000.zip](https://github.com/fishaudio/fish-speech/files/15452304/fake_200000.zip)
请问是什么问题

数据集是小数据集 只有96条

**Comment by Stardust-minus** [comment]
推荐冻结MRTE或增加辅助训练集

**Comment by aixiaodewugege** [comment]
> 推荐冻结MRTE或增加辅助训练集

大佬，有指导如何冻结MRTE的教程吗？辅助训练集是指 别的说话人的数据吗？

**Comment by leng-yue** [comment]
最好是加点别的说话人, 数据太少训练很容易 model collapse 和灾难性遗忘

**Comment by pangr** [comment]
> 最好是加点别的说话人, 数据太少训练很容易 model collapse 和灾难性遗忘

我加了数据集aishell3中的训练集一起训练，并且冻住了MRTE的参数，训练了300000steps，效果还是一样，请问是有什么参数配置需要调整吗
