### ISSUE TITLE
 how many data

### ISSUE THREAD

**Issue by xuducan** [fishaudio/fish-speech#25]
Thank you for the Greate project! May i ask some question. 1, How many data are needed to finetune vqgan and llama?  2, dou you have the experimental result about data size?

**Comment by leng-yue** [comment]
1. 1-2 hours will be good enough. Some ppl also tested 30 minutes. 
2. We are still working on data scaling, we don't have any number / scaling law for now.

**Comment by liusongxiang** [comment]
What is the amount of data for the pre-trained model?

**Comment by leng-yue** [comment]
10k hours chinese, 700 hours english, 300 hours japanese.

**Comment by liusongxiang** [comment]
@leng-yue Thanks for the reply and the great repo! Happy to see the application of group-rvq, LOL.

**Comment by hdmjdp** [comment]
> 10k hours chinese, 700 hours english, 300 hours japanese.

How many epoch for training from scratch?

**Comment by hdmjdp** [comment]
what is the model size of llma in  your fishspeech?
