### ISSUE TITLE
延时比较高

### ISSUE THREAD

**Issue by GwsinTracy** [fishaudio/fish-speech#251]
调用合成函数，字数不多的情况下，延时都能达到3s。Bert-VITS2 v2.3也是差不多。而同样setup的情况下，Bert-VITS2 v2.2延时基本在300ms以内。请问这是因为fish-speech还有Bert-VITS2 v2.3多加了模型的原因吗？
另外有大佬测过fish-speech的streaming模式延时吗？

我是在V100上测的延时。

**Comment by Stardust-minus** [comment]
没遇到过，线上就是V100部署跑的，建议自测本地环境问题

**Comment by GwsinTracy** [comment]
请问有测过单条的latency吗？求教大概是多少？

**Comment by GwsinTracy** [comment]
> 没遇到过，线上就是V100部署跑的，建议自测本地环境问题

请问有测过单条的latency吗？求教大概是多少？
