### ISSUE TITLE
自回归模型幻觉问题

### ISSUE THREAD

**Issue by Wangrui025** [fishaudio/fish-speech#252]
在测试这个模型的过程中，发现一些读音错误。例如APP读成aat，推测是由于llama自回归模型的幻觉问题导致。这个问题是否会在更大的llama模型中得到解决或者更多训练数据是否能解决这个问题？
在一些特定领域的术语中，加入特定术语的数据对llama进行微调是否可以缓解这些特定术语的发音错误问题？

**Comment by leng-yue** [comment]
我们打算后续加入的更多数字和独立字母的数据集.
