### ISSUE TITLE
使用vqgan和vits编码得到的prompt_tokens不一样[BUG]

### ISSUE THREAD

**Issue by 1nlplearner** [fishaudio/fish-speech#253]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**
运行webui，分别使用vqgan和vits编码得到的prompt_tokens不一样，使用vqgan编码的结果和直接运行tools/vqgan/inference.py一致
**To Reproduce**

**Comment by leng-yue** [comment]
您的 vits 编码器是用的开源的 1.1 版本么, 这是比较奇怪的

**Comment by 1nlplearner** [comment]
> 您的 vits 编码器是用的开源的 1.1 版本么, 这是比较奇怪的

是1.1的，你那里可以复现吗
