### ISSUE TITLE
[BUG]'Error(s) in loading state_dict for FireflyBase:\n\tMissing key(s) in state_dict: "head.conv_pre.weight_g"

### ISSUE THREAD

**Issue by Inception41** [fishaudio/fish-speech#254]
Error in call to target 'fish_speech.models.vqgan.modules.firefly.FireflyBase':
RuntimeError('Error(s) in loading state_dict for FireflyBase:\n\tMissing key(s) in state_dict: "head.conv_pre.weight_g", "head.conv_pre.weight_v", "head.ups.0.weight_g", "head.ups.0.weight_v", "head.ups.1.weight_g", "head.ups.1.weight_v", "head.ups.2.weight_g", "head.ups.2.weight_v", "head.ups.3.weight_g", "head.ups.3.weight_v", "head.ups.4.weight_g", "head.ups.4.weight_v", "head.resblocks.0.blocks.0.convs1.0.weight_g", "head.resblocks.0.blocks.0.convs1.0.weight_v",....

已经下载了firefly-gan-base-generator.ckpt
config-name选择vqgan_finetune和vqgan_pretrain都是一样的错误
报错位置是在：inference中的model: LightningModule = instantiate(cfg.model)一行

**Comment by leng-yue** [comment]
有更完整的错误日志么

**Comment by Inception41** [comment]
把firefly中的load state dict的strict改为false后，这个问题不再出现
