### ISSUE TITLE
感觉生成的语音没有ChatTTS的开源小模型流畅，是架构的原因还是数据质量？

### ISSUE THREAD

**Issue by velop559** [fishaudio/fish-speech#267]
感觉生成的语音没有ChatTTS的开源小模型流畅，是架构的原因还是数据质量？

ChatTTS开源的小模型好像训练数据也少一些，但是已经“够用”；fish-speech这边，感觉在流畅性、更“真实”方面还欠缺不少

**Comment by Stardust-minus** [comment]
暂时没有对各种语气做精标。FS更着重于fewshot和音质上的体验，以及后续的e2e audio agent

**Comment by velop559** [comment]
没有完全理解，ChatTTS也没有语气标注吧。

**Comment by Stardust-minus** [comment]
他们在先期的训练数据做了很多标注。FS都是ASR的
