### ISSUE TITLE
[Feature]能否提一个小小的请求

### ISSUE THREAD

**Issue by lanqingxiao1** [fishaudio/fish-speech#270]
能否把文档的内容做一些补充和注释，一些代码让没接触过这类项目的人能看的清楚明白
花了2个晚上，愣是没把这个项目跑起来。。。

比如：
介绍以后是微调？训练呢，我拿着素材，然后看着官方文档，我不知道怎么操作了，，虽然b站也有一些乱七八糟的讲解视频
完了以后，我需要推理了，那肯定看推理部分说明啊。。

< 从我们的 huggingface 仓库下载所需的 vqgan 和 text2semantic 模型。 > 部分写在命令行推理里面，我不需要命令行推理我肯定跳过，比如我需要weiui，那我看webui一段

你可以使用以下命令来启动 WebUI:

python -m tools.webui \
    --llama-checkpoint-path "checkpoints/text2semantic-sft-medium-v1.1-4k.pth" \
    --llama-config-name dual_ar_2_codebook_medium \
    --decoder-checkpoint-path "checkpoints/vq-gan-group-fsq-2x1024.pth" \
    --decoder-config-name vqgan_pretrain

看着这条命了，没有解释，我没看懂，你指定了什么参数，这4个参数分别是干嘛的。。最后还是前后文咬文爵字跟破案似的找线索才明白是什么文件，然。。你还是没写这些文件是必须的底膜还是非必需我可以替换我自己训练的模型。。等等等等
最终，我暂时放弃这个项目

转而研究隔壁隔壁gpt-sovits项目
gpt-sovits项目我一晚上都和我的阅读项目直接对接好了，虽然后续还有点小问题

这也说明了你文档不全前后不搭，让别人来研究你项目的人一头雾水的怎么研究，最后不也只能放弃吗

**Comment by Stardust-minus** [comment]
文档都是经过测试完全可以跑通的。参数的意义请自行参阅代码，另外，我认为这些英文的意义已经很明显了。
多找找自己的原因
