### ISSUE TITLE
[BUG]您好，加载vits模型报错，hydra.errors.InstantiationException: Error in call to target 'fish_speech.models.vits_decoder.modules.models.SynthesizerTrn'

### ISSUE THREAD

**Issue by chwyxy** [fishaudio/fish-speech#278]
![image](https://github.com/fishaudio/fish-speech/assets/65377976/1525b50a-a8e0-4706-89b0-17306435ddba)
按照官方文档启动的，启动为vits模型后报错

**Comment by pengpengzi** [comment]
根据你的日志这是一个索引文件错误，我建议可以首先检查模型是否已经存在，如果存在尝试在根目录运行一下 ：export PYTHONPATH=./  应该能解决报错，如果还为解决，可尝试在配置文件中改为全路径

**Comment by chwyxy** [comment]
谢谢，已经解决了，在加载vits模型的时候也会加载一遍vqgan模型，我加上之后就work了
