### ISSUE TITLE
2 Questions

### ISSUE THREAD

**Issue by francqz31** [fishaudio/fish-speech#28]
Hello, amazing job is done here,

But I had 2 or maybe 3 quick questions!

1- Regarding bertvits2 do you have a sample with normal vits2 then the same sample after bert ?? I would like to hear the actual difference.

2- Why do you guys use Normal bert ? I have seen Png-bert , mp-bert , pl-bert but none of them are being used! is it because the normal bert that is being used is way better than those 3 ?

3-https://speech.fish.audio/en/samples/ i listened to these samples and they are really really realistic and emotional almost like eleven labs , How did you achieve the emotion ? is it only by integrating bert ? i thought bert is for the prosody enhancing only but didn't imagine that it would increase the emotion by that much !

**Comment by leng-yue** [comment]
Hi, here is not the bert-vits2 repo. This repos target SOTA open source TTS quality, it's based on auto regressive model.
