### ISSUE TITLE
[Feature] Add ms-stft and ms-sb-cqt discriminators

### ISSUE THREAD

**Issue by sh-lee-prml** [fishaudio/fish-speech#29]
Thanks for very cool project. 

This is the best and simple LLM-based TTS Implementation I have ever seen!

For audio quality, I highly recommend adding MS-STFT Discriminator of Encodec, and MS-SB-CQT Discriminator (https://arxiv.org/abs/2311.14957).

When using above discriminators, I have experienced a better audio quality for this kind of autoencoder model.

Thanks!

**Comment by leng-yue** [comment]
Hi, we are testing different discriminators in another project, which includes these two discrimiantors and also the loss balancer introduced by encodec. If the experiment shows great improvment, we will definitely merge the updates into this repo.

**Comment by leng-yue** [comment]
Will you suggest keeping mpd and mrd (which uses 4 discriminator) or using ms-stft and ms-sb-cqt only?

**Comment by sh-lee-prml** [comment]
I suggested keeping mpd and msd!

Although some objective metrics could be decreased, MPD is very important for perceptual audio quality.

**Comment by leng-yue** [comment]
In that case, that's basically following Amphion's solution [here](https://github.com/open-mmlab/Amphion/tree/main/egs/vocoder/gan/tfr_enhanced_hifigan).

**Comment by leng-yue** [comment]
Added to: https://github.com/fishaudio/fish-speech/tree/vqgan-v2 Still testing though.

**Comment by lucasjinreal** [comment]
@leng-yue  Consider using RVQ? it shows good performance

**Comment by sh-lee-prml** [comment]
@lucasjinreal
 
RVQ is already used in vq encoder. When I check config, they already utilized 4 codebooks.

**Comment by lucasjinreal** [comment]
@sh-lee-prml thank u for point it out, is that same arch with RVQ?

**Comment by sh-lee-prml** [comment]
@lucasjinreal 

Yes same

You can see the details in this repo
https://github.com/fishaudio/fish-speech/blob/main/fish_speech/models/vqgan/modules/encoders.py
https://github.com/lucidrains/vector-quantize-pytorch/blob/master/vector_quantize_pytorch/residual_vq.py

You can also utilize the GroupedRVQ like HiFi-Codec (https://github.com/yangdongchao/AcademiCodec)

@leng-yue 

I have some questions for this. 

1. Have you compared the performance for RVQ and GroupedRVQ?

2. and I think that although RVQ or GroupedRVQ could improve the audio quality, RVQ could affect the performance of LLM model because the increased sequences make it difficult to predict the next token, and increases the memory and inference speed. So, I do not prefer to use the RVQ for audio codec actually.

Alternatively, the prob. RVQ of CLaM-TTS (https://openreview.net/forum?id=ofzeypWosV) may resolve this issue even with RVQ.

**Comment by leng-yue** [comment]
We observed that GVQ is better than RVQ in this task, we think that's because its codebook doesn't have a residual structure (codebook 0 is most important, 1 is less important, etc). So in the next version of VQ-GAN, we will also use the GVQ with 4 codebooks, but with larger codebook size.

**Comment by lucasjinreal** [comment]
@leng-yue  Does the speed slowered much? Will it runs in reasonable speed on CPU?

**Comment by leng-yue** [comment]
Fish Speech is not designed for CPU.

**Comment by leng-yue** [comment]
We also observed that adding `ms-stft` and `ms-sb-cqt` doesn't bring significant improvment comparing to `mpd` + `mrd` in our objective and subjective tests. Thus, the vqgan-v2 only uses `mpd` and `mrd`.
