### ISSUE TITLE
[BUG] 安装环境时pytorch下载速度慢

### ISSUE THREAD

**Issue by Touch-Night** [fishaudio/fish-speech#291]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**
https://github.com/fishaudio/fish-speech/blob/fbe2e3f030d9a2fe5455e56a7a9abb72161f6d0f/install_env.bat#L251-L256  
上海交大的pytorch镜像反代似乎不再能够加速下载，从之前的10MB/s变成了现在的20-400kb/s。

**Comment by leng-yue** [comment]
+ @AnyaCoder for viz

**Comment by AnyaCoder** [comment]
> Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.
> 
> **Describe the bug**
> 
> https://github.com/fishaudio/fish-speech/blob/fbe2e3f030d9a2fe5455e56a7a9abb72161f6d0f/install_env.bat#L251-L256
> 
> 
> 上海交大的pytorch镜像反代似乎不再能够加速下载，从之前的10MB/s变成了现在的20-400kb/s。
用原版试试，上交大的镜像不是我找的，我也不知道还有什么镜像可以用了。
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`

**Comment by Touch-Night** [comment]
用原版也是这个龟速啊

**Comment by AnyaCoder** [comment]
我现在还有一个想法：把torch stable版放在hf镜像上，然后点击下载。
欢迎补充。

**Comment by Stardust-minus** [comment]
可以尝试将官方的download.pytorch.org通过hosts指向162.247.5.96
这是AWS Cloudfront和中国联通的合作IP，通过中联国际直接连接中国香港。三网均能有很好的下载速度。
