### ISSUE TITLE
[help] vits 微调多少步合适

### ISSUE THREAD

**Issue by leo3349** [fishaudio/fish-speech#296]
vits微调10000步，合成的声音变成蜂鸣声了。
1000步的时候不会。
这是训练配置：

![1719540278485](https://github.com/fishaudio/fish-speech/assets/13692249/eed17b01-bbe9-4364-883b-679aaccbc4b4)

音频时长：28分钟

**Comment by leo3349** [comment]
还是因为数据量比较少，
只用了28分钟的音频

**Comment by trackcan** [comment]
你这个训练的页面哪来的？好像没找到
