### ISSUE TITLE
what's the target of this project?

### ISSUE THREAD

**Issue by deyituo** [fishaudio/fish-speech#3]

**Comment by leng-yue** [comment]
Implement an open source multilingual TTS system based on LLM, that can match commercial software.

**Comment by faceair** [comment]
This project, along with bert-vits2, falls under the FishAudio organization. What distinguishes your objectives from theirs ?

**Comment by leng-yue** [comment]
Bert-VITS2 is using VITS tech stack, while fish-speech is relying on large language models. We want to see the potential of data scaling and model scaling by switching to LLM solution.

**Comment by faceair** [comment]
Compared to the bert-vits project, what differences do you anticipate in this project?

For example:
1. higher accuracy in prosody prediction ?
2. faster fine-tuning of timbre with higher similarity ? support cross-language transfer ?
3. will the inference speed be slower ? Will it require more computational resources ?

**Comment by leng-yue** [comment]
I will say phonemizer free (which means better language understanding and accuracy), faster fine-tuning (also support zero-shot), multi-lingual (in-domain), and potentially cross-language (out-of-domain). The inference speed is expected to be slower, but I think it's still acceptable (15 secs generated per second).

**Comment by faceair** [comment]
Thank you for your response. This is a promising project, and I will continue to follow your progress.

**Comment by luohao123** [comment]
Plus one point, this solution didn't suitable for CPU deployment, I get it decoding very slow on my mac M1, but vits2 get a resonable speed even on CPU.

**Comment by leng-yue** [comment]
Since we are basically using Llama model, probably you can take a look at Llama.cpp, which provides better acceleration on m-series CPUs. Looking for your updates.
