### ISSUE TITLE
[BUG] Just try new model 1.2 

### ISSUE THREAD

**Issue by mrwill84** [fishaudio/fish-speech#311]
Hi Guys , Good Project; 

I just found some issue about doc ; 
1. 
huggingface-cli download fishaudio/fish-speech-1.2 firefly-gan-vq-fsq-4x1024-42hz-generator.pth --local-dir checkpoints
huggingface-cli download fishaudio/fish-speech-1.2 model.pth --local-dir checkpoints 
model should be in checkpoints/model.pth and firefly-gan-vq-fsq-4x1024-42hz-generator , no prefix fish-speech-1.2 
2.  
python -m tools.webui \
    --llama-checkpoint-path "checkpoints/model.pth" \
    --llama-config-name dual_ar_4_codebook_medium \
    --decoder-checkpoint-path "checkpoints/fish-speech-1.2/firefly-gan-vq-fsq-4x1024-42hz-generator.pth" \
    --decoder-config-name firefly_gan_vq 
    the path is wrong 
    
3. after I'm tryinging webui , but it failed
webui.py: error: unrecognized arguments: --llama-config-name dual_ar_4_codebook_medium 
how to use this config file
hope you all good

**Comment by mrwill84** [comment]
fixed by clone HF repo ; 
how do it support Chinese? seem only works with English

**Comment by AnyaCoder** [comment]
see [new PR](https://github.com/fishaudio/fish-speech/pull/313)
