### ISSUE TITLE
[BUG]No module named 'stream_service'

### ISSUE THREAD

**Issue by nistudyc** [fishaudio/fish-speech#315]
我在 macos 的终端运行python3 run.py的时候，他提示报错
Traceback (most recent call last):
  File "/Users/nick/fish-speech-main/run.py", line 9, in <module>
    from stream_service import FishAgentPipeline
ModuleNotFoundError: No module named 'stream_service'
我参照官网的叫成来操作的，想问下是哪里没有设置对吗？

**Comment by leng-yue** [comment]
run.py 是个我们忘了删掉的测试文件... 您可以重新看下官网的文档
