### ISSUE TITLE
[Feature] Add ASR utils

### ISSUE THREAD

**Issue by leng-yue** [fishaudio/fish-speech#32]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Integrate Whisper and Fun ASR.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by leng-yue** [comment]
We were discussing this issue in #27 .

**Comment by faceair** [comment]
Both Whisper and Fun ASR offer timestamp and punctuation annotation features. I suggest integrating audio segment splitting based on textual semantics into the ASR tool, rather than relying on silence detection, to ensure greater sentence completeness. Specifically, for longer sentences, we can also incorporate duration assessment to ensure each segment is between 3 to 15 seconds.

**Comment by faceair** [comment]
Additionally, we could integrate [Demucs](https://github.com/adefossez/demucs) for audio denoising. However, it could be implemented as a separate script.

**Comment by XierHacker** [comment]
Great job, can I ask you a few questions.
1. For the details of the pre-training model, how many hours of voice data will be used?
2. How can I train a model from scratch? Is there any documentation on this?

**Comment by leng-yue** [comment]
> Great job, can I ask you a few questions.
> 
> 1. For the details of the pre-training model, how many hours of voice data will be used?
> 2. How can I train a model from scratch? Is there any documentation on this?

Please check related issues. There is no document for pretraining yet.

**Comment by leng-yue** [comment]
> Additionally, we could integrate [Demucs](https://github.com/adefossez/demucs) for audio denoising. However, it could be implemented as a separate script.

My current workflow is: demucs -> activity detection -> asr. Writing another script sounds good to me.

**Comment by Honst211** [comment]
I read what you discussed. The main problem at present is that the docker image does not have **torchaudio**, but we need **torchaudio** to run **modelscope**.
I read the source code of **modelscope**, in which they did exception handling for **torchaudio** and **librosa**, but it did not take effect, causing a **ModuleNotFoundError**. We can inherit the class pipeline code of **modelscope** **funasr** to make it take effect. We'd better submit this issue to them.

This is their source code, they import **torchaudio** and **librosa** in the file header
<img width="375" alt="image" src="https://github.com/fishaudio/fish-speech/assets/50348812/488e987e-f45c-4f5c-9cb7-909a31af0804">

**Comment by leng-yue** [comment]
That will be a good solution.

**Comment by Honst211** [comment]
This warehouse was modified by me so that I can use FunASR without **torchaudio**. The test showed that there is no problem.
Check to see if you need to replace the official FunASR.

https://github.com/Honst211/FunASR

**Comment by leng-yue** [comment]
Did you make a pr to the official repo?

**Comment by Honst211** [comment]
No, I asked the official about the PR of this requirement, and they said that the code of this warehouse will no longer be maintained. . . , let me pay attention to the new FunASR

**Comment by luohao123** [comment]
@Honst211 what does new FunASR update?
