### ISSUE TITLE
[BUG] 使用docker安装，使用webui测试发现的问题

### ISSUE THREAD

**Issue by fallbernana123456** [fishaudio/fish-speech#322]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**
我使用了一段64个字正常14秒说完的文本测试，使用generate生成，生成的结果随机性太大，有时男声，有时女生，有时有1秒的。有时6秒的。有时说2个字停顿再说几个字的。测试调整参数，那结果更是五花八门。是只有我这样吗？
**To Reproduce**

**Expected behavior**

**Screenshots / log**
If applicable, add screenshots / logs to help explain your problem.
![image](https://github.com/fishaudio/fish-speech/assets/45087694/f22a1a09-e3c9-4dbd-bf89-3d92c324d2a2)
![image](https://github.com/fishaudio/fish-speech/assets/45087694/9e664283-389d-4a25-bb13-a96fc140f32c)

**Additional context**

**Comment by PoTaTo-Mika** [comment]
请点Reference Audio，然后勾选启用参考音频，之后上传你的参考音频。

**Comment by fallbernana123456** [comment]
> 请点Reference Audio，然后勾选启用参考音频，之后上传你的参考音频

使用了Reference Audio,提供了一段10秒的音频后音色没有问题，能保持跟提供的音频一致。
但是问题还是有一些，比较突出的比如 缺字缺词，换气的时候有明显的不连贯，有拖长音导致的变声。而且同样的条件每次生成的都不一样。稳定性不好。
![image](https://github.com/fishaudio/fish-speech/assets/45087694/e9a70225-8dcb-4964-b060-9f61c0dbafbc)

可以看到每次的token值都不一样。音频传不了。你们的样例为什么效果好？
能把参数的说明写详细点吗？

**Comment by lonngxiang** [comment]
https://hub.docker.com/r/lengyue233/fish-speech   docker下载了怎么运行和使用呢

**Comment by suchaunzhi** [comment]
> > 请点Reference Audio，然后勾选启用参考音频，之后上传你的参考音频
> 
> 使用了Reference Audio,提供了一段10秒的音频后音色没有问题，能保持跟提供的音频一致。 但是问题还是有一些，比较突出的比如 缺字缺词，换气的时候有明显的不连贯，有拖长音导致的变声。而且同样的条件每次生成的都不一样。稳定性不好。 ![image](https://private-user-images.githubusercontent.com/45087694/345979804-e9a70225-8dcb-4964-b060-9f61c0dbafbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjY2ODksIm5iZiI6MTcyMDE2NjM4OSwicGF0aCI6Ii80NTA4NzY5NC8zNDU5Nzk4MDQtZTlhNzAyMjUtOGRjYi00OTY0LWIwNjAtOWY2MWMwZGJhZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA3NTk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0ZWM0NDJjNGFmNDhlZTIxZDY0ZjYxMWFiYmNlM2UyYzRkMTg4YmYxZjFjYzg3NDAyZDQ2ZmYwNDhiMTgyYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EHnQ7qSyw5-vuusj0hWwTaWnQ9cDC96i1jyiOrXtTCs)
> 
> 可以看到每次的token值都不一样。音频传不了只能看这个图了。你们的样例为什么效果好？ 能把参数的说明写详细点吗？


我这也是这个问题。音色克隆很像没有问题，但是停顿和流畅度明显没有官网上那个好。

**Comment by monkeyGeek369** [comment]
请问docker安装使用了什么特殊的网络设置吗？我这边通过docker安装，程序也正常跑起来，但是就是无法在宿主机访问
通过docker成功启动程序，也开启了webui，但是奇怪的是容器内可以访问127.0.0.1:7860但是宿主机无法访问。
1、已经做了端口映射，无效
2、容器采用host模式，无效
3、容器内可以ping通宿主机，但宿主机无法ping通容器ip

**Comment by fallbernana123456** [comment]
> 请问docker安装使用了什么特殊的网络设置吗？我这边通过docker安装，程序也正常跑起来，但是就是无法在宿主机访问 通过docker成功启动程序，也开启了webui，但是奇怪的是容器内可以访问127.0.0.1:7860但是宿主机无法访问。 1、已经做了端口映射，无效 2、容器采用host模式，无效 3、容器内可以ping通宿主机，但宿主机无法ping通容器ip

docker run -itd -v ./:/exp -p 7860:7860 --gpus all --name fish-speech-1.0 fish-speech-main-fish-speech:1.0

如何在主机能访问到服务：https://speech.fish.audio/inference/#webui 里有说明，你可以使用 Gradio 环境变量, 如 GRADIO_SHARE, GRADIO_SERVER_PORT, GRADIO_SERVER_NAME 来配置 WebUI. GRADIO_SERVER_NAME  改为"0.0.0.0"，或者直接修改tools.webui 文件 ，添加 server_name="0.0.0.0" 参数。具体查看gradio说明
