### ISSUE TITLE
[Copyright] about undocumented `i18n` codes that from RVC

### ISSUE THREAD

**Issue by fumiama** [fishaudio/fish-speech#324]
### Problem

We noticed that there's an `i18n` folder in the `fish_speech` directory without any documentation.
These files initially come from [RVC](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI). According to its MIT license, you can use the code, but you should point out the copyright (which means the source and the author) at the significant position of those files.

Of course, you have mentioned [GPT-SoVITS](https://github.com/RVC-Boss/GPT-SoVITS) at your README, which also includes the `i18n` folder. But unfortunately, the uploader `RVC-Boss` is not the original author of those files. You can see the commit history of the `i18n` folder in `GPT-SoVITS` [here](https://github.com/RVC-Boss/GPT-SoVITS/tree/630bbbcf7cd59531f2677acd3d2130f9fa7af707/i18n). The date is Jan 16, 2024, which is younger than [this commit](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/commit/72d37119de5803fc6372258cee9c4555fa111780) in RVC on Apr 12, 2023.

### Solution

There're two solutions.

1. Delete the `i18n` folder, then you don't need to mention it.
2. Or, mention the original authors and sources of the files at their beginning as below.

#### fish_speech/i18n/core.py
1. Related code from RVC
  https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/83d6a64e675d9bbd6e92ee450c5f807ed2bb54d8/i18n/i18n.py
2. Initial commit
  https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/pull/35
3. Initial author
  @L4Ph

#### fish_speech/i18n/scan.py
1. Related code from RVC
  https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/83d6a64e675d9bbd6e92ee450c5f807ed2bb54d8/i18n/scan_i18n.py
2. Initial commit
  https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/pull/1058
3. Initial author
  @towzeur

**Comment by Stardust-minus** [comment]
Assign @AnyaCoder

**Comment by Stardust-minus** [comment]
Fixed. See #325

**Comment by fumiama** [comment]
Thank you for your fast response. 👍
