### ISSUE TITLE
[BUG] In latest v1.2: tools/llama/generate.py how to specify a speaker used during fine-tuning?

### ISSUE THREAD

**Issue by TianduoWang** [fishaudio/fish-speech#326]

**Comment by PoTaTo-Mika** [comment]
There's no need to use the param --speaker in 1.2 version.

**Comment by TianduoWang** [comment]
Thanks for your reply! What if I  consider several speakers during my fine-tuning, and I want to specify one of them during inference, how should I do it?

**Comment by PoTaTo-Mika** [comment]
Just use the reference audio to specify the person you want to infer.

**Comment by TianduoWang** [comment]
Thanks a lot!

By the way, I found that the "speaker" argument is still recommended in this page: https://speech.fish.audio/inference/#1-prompt
