### ISSUE TITLE
现在最多支持多少个字符输入呢。稍微长一点就提示超过Text too long

### ISSUE THREAD

**Issue by zhouhounan** [fishaudio/fish-speech#329]
还有我在语音合成时，里面有夹杂一些英语，英语的朗读就不够好。麻烦管理看看
目前腾讯的微众银行已经构建了能够支撑和服务金融业务的场景化生成式AI Agent Store（人工智能业务助理矩阵）；农业银行也推出了自已的金融AI大模型应用ChatABC；兴业银行推出了一个叫做反洗钱可疑报告智能生成领域运用的大模型……

**Comment by AnyaCoder** [comment]
现在支持任意长。
