### ISSUE TITLE
Support for More Languages

### ISSUE THREAD

**Issue by AnitaLiu98** [fishaudio/fish-speech#331]
I would like to extend support for more languages. To better understand the current state, I have a few questions about the tokenizer:

**1. What kind of corpus or datasets were used to build the current tokenizer?**
**2. How does the system handle polyphonic characters in Chinese?**

If there are any documents or resources that provide more insight into the tokenizer’s construction and capabilities, please share them.

Thank you!

**Comment by AnyaCoder** [comment]
see README.md
