### ISSUE TITLE
执行命令python build_dataset.py报错

### ISSUE THREAD

**Issue by LayBrick** [fishaudio/fish-speech#333]
![image](https://github.com/fishaudio/fish-speech/assets/91247260/e4369d60-890b-406e-9921-ed40e519c490)
这里读取npy文件，为何要用utf-8，为什么要读取npy文件

**Comment by LayBrick** [comment]
![image](https://github.com/fishaudio/fish-speech/assets/91247260/4e92a73c-7f11-42aa-b154-ee6e9d71e2ea)
这里是报错文件

**Comment by AnyaCoder** [comment]
你用了啥命令呀？
