### ISSUE TITLE
[Feature]可以支持法语吗？

### ISSUE THREAD

**Issue by xeoshow** [fishaudio/fish-speech#336]
看例子有中文、英文、日语，是否可以支持法语呢？谢谢

**Comment by PoTaTo-Mika** [comment]
计划支持

**Comment by xeoshow** [comment]
有大概的计划时间吗？非常感谢~

**Comment by sekkit** [comment]
韩语希望也可以加入，谢谢

**Comment by Stardust-minus** [comment]
Planned. Maybe v1.3/v1.4 milestone.

**Comment by xeoshow** [comment]
Hi @Stardust-minus ,

刚看到最新的1.4版本发布了，这个版本可以支持法语了吗？谢谢

**Comment by Stardust-minus** [comment]
> Hi @Stardust-minus ,
> 
> 刚看到最新的1.4版本发布了，这个版本可以支持法语了吗？谢谢

已经支持了。
