### ISSUE TITLE
安装后启动失败[BUG]

### ISSUE THREAD

**Issue by crowdedplus** [fishaudio/fish-speech#339]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**
修改了环境安装参数
set USE_MIRROR=false
set INSTALL_TYPE=stable
安装，启动时提示error loading   "....\fish-speech-1.1.2\fishenv\env\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**To Reproduce**
win10系统
尝试安装了VC_redist，但是没有解决问题

**Expected behavior**

**Screenshots / log**
If applicable, add screenshots / logs to help explain your problem.

**Additional context**

**Comment by AnyaCoder** [comment]
stable的下载地址确实是有误的，不久后会修复。
不嫌麻烦，INSTALL_TYPE=preview的a,b,c三个步骤都做一遍能够解决该问题。

**Comment by crowdedplus** [comment]
> stable的下载地址确实是有误的，不久后会修复。 不嫌麻烦，INSTALL_TYPE=preview的a,b,c三个步骤都做一遍能够解决该问题。

  我需要把已经下载好的内容删了重来吗

**Comment by AnyaCoder** [comment]
不需要，做那3个步骤就好。

**Comment by crowdedplus** [comment]
> 不需要，做那3个步骤就好。

以防万一问一下，执行start.bat的时候下载了一大堆东西，这是正常的吧

**Comment by AnyaCoder** [comment]
正常的，不放心你可以看bat源码。

**Comment by crowdedplus** [comment]
> 正常的，不放心你可以看bat源码。

谢谢，本地成功启动了，但是还不怎么会用

**Comment by AnyaCoder** [comment]
webui有指示的，摸索一下就会了。只输入一个音频文件夹路径就行。
