### ISSUE TITLE
[BUG]在本地部署推理过程中遇到的两个问题：

### ISSUE THREAD

**Issue by runningto** [fishaudio/fish-speech#343]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / log**
If applicable, add screenshots / logs to help explain your problem.

**Additional context**

**Comment by runningto** [comment]
1. 短文本推理最后一个字吞字或者不自然的很快的结束掉
2. 较长的文本推理会吞掉中间的话，不能完整生成

**Comment by PoTaTo-Mika** [comment]
大模型固有幻觉问题，请多次推理自行选择最好结果。

**Comment by runningto** [comment]
有时候还会碰到合成出来的声音是唱歌的

**Comment by AnyaCoder** [comment]
试着lora微调一下
