### ISSUE TITLE
How many epoch for training from scratch?

### ISSUE THREAD

**Issue by hdmjdp** [fishaudio/fish-speech#35]
> 10k hours chinese, 700 hours english, 300 hours japanese.

How many epoch for training from scratch?

_Originally posted by @hdmjdp in https://github.com/fishaudio/fish-speech/issues/25#issuecomment-1865737131_

**Comment by leng-yue** [comment]
Current model is in fact a draft model, it only take 10k steps.

**Comment by hdmjdp** [comment]
> Current model is in fact a draft model, it only take 100k steps.
Does training only up to 100k steps result in good performance for GPT and no issues with synthesized audio?

**Comment by leng-yue** [comment]
As you see, there is no major issue in generation. And this is a draft model, we plan to train longer with more data.

**Comment by hdmjdp** [comment]
> 10k hours chine
StarRail1.5_CN.7z 这个数据有1w小时吗

**Comment by leng-yue** [comment]
没有... https://github.com/fishaudio/fish-speech/blob/main/fish_speech/configs/data/pretrain.yaml
我其实不是很建议你们自己 pretrain, 尤其是对 llm 不熟悉的情况下...

**Comment by hdmjdp** [comment]
大佬，有啥坑吗？不得不预训练啊

**Comment by Liujingxiu23** [comment]
有预训练模型吗？没有看到呢
