### ISSUE TITLE
[QUESTION] Support on MacOS apple silicon

### ISSUE THREAD

**Issue by limingchina** [fishaudio/fish-speech#356]
I saw the doc only mentions installation on Windows and Linux. Wonder if anyone has tried MacOS? I have an MacBook M3 pro and wonder if I can setup the lib and run the web UI.

_Originally posted by @limingchina in https://github.com/fishaudio/fish-speech/discussions/351_

**Comment by PoTaTo-Mika** [comment]
Mac is not supported for training/Inferring.

**Comment by muyiou** [comment]
when this project can support macos？

**Comment by limingchina** [comment]
What's the technical difficulties of supporting Mac? Some of the dependencies? Many libs should support the "mps" torch device for hardware accelearation.

**Comment by AnyaCoder** [comment]
We've supported the inference for mps devices

**Comment by limingchina** [comment]
Does it mean on MacOS, the inference would work out of the box? What about the CPU type? Does it matter if it's intel chip or Apple silicon?

**Comment by AnyaCoder** [comment]
Theoretically any cpu device will work.

**Comment by amirvenus** [comment]
> We've supported the inference for mps devices

Are there any instructions to run it on macOS?

**Comment by AnyaCoder** [comment]
You can see here : https://speech.fish.audio/zh/#macos

**Comment by fast01** [comment]
there is a try that can run on win and  mac.  Try this :  https://blog.csdn.net/weixin_43935971/article/details/144435437
