### ISSUE TITLE
[BUG]windows部署后点击开始训练没有反应

### ISSUE THREAD

**Issue by Rex-Akira-Lau** [fishaudio/fish-speech#361]
如图所示，跟着文档一步步来的，是不是哪个地方没做对？
![image](https://github.com/fishaudio/fish-speech/assets/86335228/d4b5f280-2393-47ea-8480-a4831554850d)

**Comment by AnyaCoder** [comment]
你需要将音频和标注文本放到一个文件夹里，再将这个文件夹放到data下，点击文件预处理之后，到训练配置页面下的LLAMA才能点击训练。

**Comment by Rex-Akira-Lau** [comment]
> 你需要将音频和标注文本放到一个文件夹里，再将这个文件夹放到data下，点击文件预处理之后，到训练配置页面下的LLAMA才能点击训练。
![image](https://github.com/fishaudio/fish-speech/assets/86335228/dd6cbc49-8d46-4015-9250-26c2f90ea086)
谢谢大佬，后续遇到了这个报错，就把这个path做了下str转换，实测可以将就用
