### ISSUE TITLE
[Feature]V1.2相对于之前做了哪些优化

### ISSUE THREAD

**Issue by lidingke** [fishaudio/fish-speech#369]
我看v1.2只有firefly-gan-vq这个模型了，没有之前的vit模型了。具体做了哪些优化呢，感觉对英文短语的输出没什么提升。

**Comment by Stardust-minus** [comment]
fewshot性能的大幅提升和咬字上的优化。decoder部分换为firefly-gan-vq解码。LLAMA部分增加数据，码本换为4码本。
