### ISSUE TITLE
[FINETUNE]

### ISSUE THREAD

**Issue by kunci115** [fishaudio/fish-speech#371]
I want to finetune it with around 30mins of english singaporean accent data, but when the models was merge with lora after trained, i test the model with "hello my name is laura", but the model generate longer than that with french language, can anyone tell what happen ?

this is to train following https://speech.fish.audio/en/finetune/
``
python fish_speech/train.py --config-name text2semantic_finetune project=$project +lora@model.model.lora_config=r_8_alpha_16

**Comment by PoTaTo-Mika** [comment]
30mins' data is so little for finetune, we recommend you to finetune with data more than 10 hours.

**Comment by kunci115** [comment]
ok so the bare minimum to fitune is 11 hours I assume ?

**Comment by leng-yue** [comment]
The text in dataset should be `hello world` directly.
