### ISSUE TITLE
请问多音字在api接口内，怎么干预[BUG]

### ISSUE THREAD

**Issue by zhusy09** [fishaudio/fish-speech#372]
**请问多音字在api接口内，怎么干预[BUG]**

**Comment by PoTaTo-Mika** [comment]
暂时无法解决，建议换成同音字，虽然看着别扭但是最后效果能符合预期。

**Comment by leng-yue** [comment]
目前的 split 算法需要一些优化, 下个版本修复后可以用: `<|phoneme_start|>ni2<|phoneme_end|>` 这种形式.
