### ISSUE TITLE
WSL2 Ubuntu安装的，怎么启动项目呀？

### ISSUE THREAD

**Issue by ganwt** [fishaudio/fish-speech#373]
**Describe the bug**
```
(fish-speech) ganwt@OMEN:~/fish-speech$ ls
API_FLAGS.txt  docker-compose.dev.yml  fish_speech           install_env.bat  pyrightconfig.json  tools
LICENSE        dockerfile              fish_speech.egg-info  mkdocs.yml       run_cmd.bat
README.md      docs                    inference.ipynb       pyproject.toml   start.bat
(fish-speech) ganwt@OMEN:~/fish-speech$ . start.bat
Command '@echo' not found, did you mean:
  command 'echo' from deb coreutils (8.32-4.1ubuntu1)
Try: sudo apt install <deb name>
chcp: too few arguments
setlocal: command not found
-bash: start.bat: line 14: syntax error near unexpected token `('
-bash: start.bat: line 14: `if "%USE_MIRROR%" == "true" ('
```

`.bat`文件好像是Windows环境执行的。我是Windows11 的WSL 中的Ubuntu环境。
请问，需要怎么做才能像大家那样打开webUI窗口呀？

**Comment by AnyaCoder** [comment]
不用wsl环境，用windows环境

**Comment by PoTaTo-Mika** [comment]
ubuntu建议你直接执行命令行tools/webui.py

**Comment by ganwt** [comment]
> 不用wsl环境，用windows环境

谢谢你的答复。
已经安装在wsl环境里了，想尝试着跑起来。

**Comment by ganwt** [comment]
> ubuntu建议你直接执行命令行tools/webui.py

谢谢你的答复。
我尝试着执行了一下，报了下列的错误。提示说缺少文件`'checkpoints/fish-speech-1.2'`，请问你可以教我一下，怎么解决这个问题吗？
```
(fish-speech) ganwt@OMEN:~/fish-speech$ python tools/webui.py
2024-07-12 17:40:02.215 | INFO     | __main__:<module>:451 - Loading Llama model...
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "/home/ganwt/miniconda3/envs/fish-speech/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ganwt/miniconda3/envs/fish-speech/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ganwt/fish-speech/tools/llama/generate.py", line 557, in worker
    model, decode_one_token = load_model(
  File "/home/ganwt/fish-speech/tools/llama/generate.py", line 342, in load_model
    model: Union[NaiveTransformer, DualARTransformer] = BaseTransformer.from_pretrained(
  File "/home/ganwt/fish-speech/fish_speech/models/text2semantic/llama.py", line 324, in from_pretrained
    config = BaseModelArgs.from_pretrained(str(path))
  File "/home/ganwt/fish-speech/fish_speech/models/text2semantic/llama.py", line 75, in from_pretrained
    with open(path, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/fish-speech-1.2'
```

**Comment by LLLYF** [comment]
> > ubuntu建议你直接执行命令行tools/webui.py
> 
> 谢谢你的答复。 我尝试着执行了一下，报了下列的错误。提示说缺少文件`'checkpoints/fish-speech-1.2'`，请问你可以教我一下，怎么解决这个问题吗？
> 
> ```
> (fish-speech) ganwt@OMEN:~/fish-speech$ python tools/webui.py
> 2024-07-12 17:40:02.215 | INFO     | __main__:<module>:451 - Loading Llama model...
> Exception in thread Thread-2 (worker):
> Traceback (most recent call last):
>   File "/home/ganwt/miniconda3/envs/fish-speech/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "/home/ganwt/miniconda3/envs/fish-speech/lib/python3.10/threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/ganwt/fish-speech/tools/llama/generate.py", line 557, in worker
>     model, decode_one_token = load_model(
>   File "/home/ganwt/fish-speech/tools/llama/generate.py", line 342, in load_model
>     model: Union[NaiveTransformer, DualARTransformer] = BaseTransformer.from_pretrained(
>   File "/home/ganwt/fish-speech/fish_speech/models/text2semantic/llama.py", line 324, in from_pretrained
>     config = BaseModelArgs.from_pretrained(str(path))
>   File "/home/ganwt/fish-speech/fish_speech/models/text2semantic/llama.py", line 75, in from_pretrained
>     with open(path, "r", encoding="utf-8") as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/fish-speech-1.2'
> ```

因为你缺少对应的底模，需要到推理的介绍里面https://speech.fish.audio/inference/  命令行推理 -> 下载模型 复制任意一个指令去下载模型，再执行就可以了

**Comment by moyutegong** [comment]
运行python tools/download_models.py 下载模型

**Comment by ganwt** [comment]
> 运行python tools/download_models.py 下载模型

成功了。谢谢你！
