### ISSUE TITLE
音色不错，不过性能很一般，我机器上用了2070-8g的显卡，竟然不必上gpt-sovits在cpu上的运行速度

### ISSUE THREAD

**Issue by jasonzhang761213** [fishaudio/fish-speech#375]
音色不错，不过性能很一般，我机器上用了2070-8g的显卡，竟然不必上gpt-sovits在cpu上的运行速度
fish-speed
2070的游戏本，windows10

gpt-sovits
macbook-pro 2013，windows11 ，cpu环境

**Comment by Stardust-minus** [comment]
请更换Linux环境，并启用compile，可获得5-10倍性能提升。
