### ISSUE TITLE
无法建立连接

### ISSUE THREAD

**Issue by wcr369** [fishaudio/fish-speech#376]
当我执行python -m tools.post_api \
    --text "Hello everyone, I am an open-source text-to-speech model developed by Fish Audio." \
    --reference_audio "..." \
    --reference_text "..." \
    --streaming True
的时候，遇到如下报错，请问应当如何解决
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/invoke (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd02d8a1570>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by AnyaCoder** [comment]
你开api server 了吗?
