### ISSUE TITLE
[Feature] use text to describe and control the sound style

### ISSUE THREAD

**Issue by chunping-xt** [fishaudio/fish-speech#377]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Is your feature request related to a problem? Please describe.**
I got my great finetuned checkpoint , but I'm a bit greedy and wish I could use text to describe and control the sound style. I even want some words to be controlled in pitch or length.

**Describe the solution you'd like**
eg:  input text to model
"control: deep male voice, slow speaking, sad... | text: ..."

**Describe alternatives you've considered**

**Additional context**
Style control feature similar to Bark, Parler TTS but your model is excellent timbre with VQGAN, very high quality sound.

**Comment by johnwick123f** [comment]
@chunping-xt Did you find a solution to this?

**Comment by matbee-eth** [comment]
it looks like this solves it: https://github.com/fishaudio/fish-speech/blob/main/docs/en/inference.md#1-create-a-ref_data-folder-in-the-root-directory-of-the-project

**Comment by johnwick123f** [comment]
@matbee-eth that seems to just randomly choose one of the audio file from the folder and use that. I was looking for something similar to the prompting chunping-xt was describing like "a deep male voice slowly speaking in a sad voice"
