### ISSUE TITLE
[BUG] epoch number not displayed correctly

### ISSUE THREAD

**Issue by chunping-xt** [fishaudio/fish-speech#379]
**Describe the bug**
I tried training with 20 files (<15s) with batch=4, the training process always shows Epcho 0 and also no total number of steps needed to train. eg:
Epoch 0: | | 544/? [05:54<00:00,  1.53it/s, v_num=0, train/loss=0.0354, train/to^C

**Comment by leng-yue** [comment]
This is an expected behavior, it uses infinity stream + iterable dataset. If you only have 20 files, with bs=4, it should only take 5 steps to finish 1 epoch.
