### ISSUE TITLE
[BUG] Generated speech is unclear

### ISSUE THREAD

**Issue by faceair** [fishaudio/fish-speech#38]
**Describe the bug**

Is the unclear pronunciation caused by the "half" parameter breaking something?

[fake.wav.zip](https://github.com/fishaudio/fish-speech/files/13757879/fake.wav.zip)

Another question is how should I fill in the "prompt-text"? I noticed in the code that "prompt-text" is eventually concatenated with "text", so is it okay if I don't write anything for it?

**To Reproduce**

Here is the command I used.
```shell
python tools/vqgan/inference.py \
    -i "胡子v1_0.wav" \
    --checkpoint-path "checkpoints/vqgan-v1.pth"

python tools/llama/generate.py \
    --text "要转换的文本" \
    --prompt-text "你的参考文本" \
    --prompt-tokens "fake.npy" \
    --checkpoint-path "checkpoints/text2semantic-400m-v0.2-4k.pth" \
    --compile \
    --half

python tools/vqgan/inference.py \
    -i "codes_0.npy" \
    --checkpoint-path "checkpoints/vqgan-v1.pth"
```

**Comment by AnyaCoder** [comment]
`prompt-text ` is the transcription of the wav file, type: `str`.

**Comment by faceair** [comment]
Thank you, it works. I think I understand now. Using prompt-text and prompt-tokens as input, the LLM predicts the corresponding tokens based on the input text as output.
