### ISSUE TITLE
[Frature] Does it support Cantonese/Cantonese?

### ISSUE THREAD

**Issue by macauhome** [fishaudio/fish-speech#380]
現有模型很少支持粵語/廣東話, 若支持,相信fish-speech 比 PaddleSpeech 會好太多

**Comment by PoTaTo-Mika** [comment]
方言相关需要至少1000小时的数据进行微调，可以自行尝试科研，LLM对多语言有较强的泛化能力。

**Comment by Stardust-minus** [comment]
https://github.com/fishaudio/fish-speech/issues/515 Change title to English.
