### ISSUE TITLE
按照For Test的流程执行，生成出来的wav全是杂音或者不说话

### ISSUE THREAD

**Issue by wcr369** [fishaudio/fish-speech#381]
这是我的执行流程：

python tools/vqgan/inference.py \
-i "/home/i-wangchenrun/Data/mpy/钟离/为安全起见，最好找人打听一下。.wav" \
--checkpoint-path "checkpoints/fish-speech-1.2/firefly-gan-vq-fsq-4x1024-42hz-generator.pth"

python tools/llama/generate.py \
--text "你好，很高兴见到你" \
--prompt-text "为安全起见，最好找人打听一下。" \
--prompt-tokens "fake.npy" \
--checkpoint-path "checkpoints/fish-speech-1.2" \
--num-samples 5

python tools/vqgan/inference.py \
-i "codes_4.npy" \
--checkpoint-path "checkpoints/fish-speech-1.2/firefly-gan-vq-fsq-4x1024-42hz-generator.pth"

每一步都顺利执行，最后生成的fake.wav都是杂音或者空白

**Comment by wcr369** [comment]
而且我只执行第一步，生成的fake.wav也都是杂音，不是原来的prompt wav

**Comment by AnyaCoder** [comment]
我这测试是没有问题的，可能是你gpu的问题。
试着用这个命令, 启用半精度：
```bash
python tools/llama/generate.py \
  --text "你好，很高兴见到你" \
  --prompt-text "为安全起见，最好找人打听一下。" \
  --prompt-tokens "fake.npy" \
  --checkpoint-path "checkpoints/fish-speech-1.2" \
  --num-samples 5 \
  --half
```

**Comment by wcr369** [comment]
> 我这测试是没有问题的，可能是你gpu的问题。 试着用这个命令, 启用半精度：
> 
> ```shell
> python tools/llama/generate.py \
>   --text "你好，很高兴见到你" \
>   --prompt-text "为安全起见，最好找人打听一下。" \
>   --prompt-tokens "fake.npy" \
>   --checkpoint-path "checkpoints/fish-speech-1.2" \
>   --num-samples 5 \
>   --half
> ```

应该不是在这一步出现的问题，我在第一步对prompt wav的encode和decode就遇到了还原的wav变成杂音的问题。看起来是codec的编解码我这里出现了问题。

**Comment by AnyaCoder** [comment]
应该和精度有关，默认bf16

**Comment by wcr369** [comment]
> 应该和精度有关，默认bf16 你用的什么设备？

刚刚降了一下cuda的版本，现在正常了，感谢
