### ISSUE TITLE
[Feature] The biggest demand for TTS is the reading API. Can it be made into an app to run TTS services on mobile devices in the future?

### ISSUE THREAD

**Issue by adoin** [fishaudio/fish-speech#382]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Is your feature request related to a problem? Please describe.**
Novel read.

**Describe the solution you'd like**
Set TTS on mobile, listen to the novel.
**Describe alternatives you've considered**
MultiTTS

**Additional context**

**Comment by Whale-Dolphin** [comment]
Our api service will be avaliable soon on https://fish.audio/.  You can later to use our api service build your own mobile apps.

**Comment by starlite0660** [comment]
很期待朗读api的上线！

**Comment by starlite0660** [comment]
Looking forward to the speak api going live!

**Comment by adoin** [comment]
> Our api service will be avaliable soon on https://fish.audio/. You can later to use our api service build your own mobile apps.

Is is possible to deploy API on mobile local?
Novel reading do really coast too much when using 4g/5g

**Comment by Stardust-minus** [comment]
https://github.com/fishaudio/fish-speech/issues/515 Change title to English.
