### ISSUE TITLE
[Feature] Other language support?

### ISSUE THREAD

**Issue by Naozumi520** [fishaudio/fish-speech#39]
**Is your feature request related to a problem? Please describe.**
I'm always finding a text to speech project that can be used on Cantonese. But most are outdated and the quality is not so well. I tried to port vits2 and innnky/emotional-vits to Cantonese by copy the old Cantonese cleaner, but the result is so poor. 

**Describe the solution you'd like**
Use [chinese-dialect-lexicons](https://github.com/CjangCjengh/chinese-dialect-lexicons) as text cleaner?

**Describe alternatives you've considered**
I've noticed that phonemizer is going to be dropped soon. I wonder if with `--no-g2p` can archive it.

**Additional context**
N/A

**Comment by leng-yue** [comment]
`--no-g2p` will achieve that. We can add more languages by adding more data.

**Comment by Naozumi520** [comment]
<3 It's the best news for me! Thank you very much!

**Comment by Naozumi520** [comment]
Can I have documents on how to train/use it by myself with my data with `--no-g2p`? :D

**Comment by leng-yue** [comment]
Sounds good! Can you submit a PR?

**Comment by Naozumi520** [comment]
Uh.. Sorry, I mean could I have the details on how did `--no-g2p` work, and how many datas do I need to finetune the model. Sorry for my misleading :(

**Comment by leng-yue** [comment]
Just add `--no-g2p` to the `generate.py`, and I will suggest you to try ~1000 hours of yue data.

**Comment by Naozumi520** [comment]
Training with modified g2p seemed to be a more appropriate way for low resources languages. Close as finished.

**Comment by leng-yue** [comment]
You may also want to try the new no-g2p mode in dev branch, it requires far less data now.

**Comment by Naozumi520** [comment]
> You may also want to try the new no-g2p mode in dev branch, it requires far less data now.

I see. But I just got a new issue that is, retrain with different data it could not generate speech #129, can you help me please?
