### ISSUE TITLE
[Question] VQGAN fine-tuning dataset size and training time

### ISSUE THREAD

**Issue by TundraWork** [fishaudio/fish-speech#40]
I'd like to gather some insights about the fine-tuning process from those who have experienced it.

  - What is the recommended dataset size for fine-tuning?

  - What is the anticipated training time? I noticed there's a `max_steps: 100000` configuration for the lightning trainer, but based on my current training speed, this will take a significant amount of time (>7 days). I have attempted to run it on both a single-card A100 instance and an eight-card V100 instance, both resulted a training speed at ~7500 epochs per 12 hours.

  - And one more question: Is the VQGAN model sensitive to the emotion or speaking style of the speaker? For example, a single speaker might express different emotions in different samples; will this influence the training results?

**Comment by leng-yue** [comment]
Hi, each epoch generally contains multiple steps (depends on the size of your dataset). For finetuning, I think we are using 1000 steps (aka batches) by default and the recommended dataset size is > 1 hours.

**Comment by TundraWork** [comment]
Hi leng-yue, thanks for your insights!
Just a quick question: 
In `vqgan_finetune.yaml`, we have:
```
trainer:
  accelerator: gpu
  devices: auto
  strategy: ddp_find_unused_parameters_true
  precision: 32
  max_steps: 100000
  val_check_interval: 1000
```
the max steps is 100k, and from the code of `train.py` L98, `Trainer.fit()` function does not have any automatic early-stop features.
Could you indicate where the setting for 1000 batches originates? I have attempted pretraining, and it did not stop even after 7000 epochs.

**Comment by leng-yue** [comment]
Oh, I thought you are discussing the semantic model (llama). For vqgan, the reason I set the max_steps to 100k is that we are using the ExponentialLR instead of Cosine (which max_steps doesn't matter). Finetuning 5k steps should be good enough for most case. You can check that in the tensorboard.

**Comment by lucasjinreal** [comment]
Does the llama and vqgan should training separately?

**Comment by TundraWork** [comment]
> Does the llama and vqgan should training separately?

Yes, you can find more details in the document here: https://speech.fish.audio/en/finetune/

And of course you can train them using the same dataset.

**Comment by lucasjinreal** [comment]
Hows the effect, does it peformance better than bertvits2?
