### ISSUE TITLE
[Bug] After fine-tuning the llama model, no fine-tuned checkpoints folder is generated

### ISSUE THREAD

**Issue by lbl1120** [fishaudio/fish-speech#408]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**

**To Reproduce**
![屏幕截图 2024-07-20 185657](https://github.com/user-attachments/assets/e1231b6b-65da-4bbb-9a2b-d76c751a3d65)

**Expected behavior**

**Screenshots / log**
If applicable, add screenshots / 
![image](https://github.com/user-attachments/assets/943e8640-49c1-4143-a24e-fb5e538d2709)
logs to help explain your problem.

**Additional context**

**Comment by PoTaTo-Mika** [comment]
根据文档进行操作，同时请检查各个文件目录下的内容

**Comment by Stardust-minus** [comment]
#515 Change title to English.
