### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by XierHacker** [fishaudio/fish-speech#41]
**Describe the bug**
I followed your steps for fine-tuning. During the last step of training, this error occurred. 

**Screenshots / log**

**Additional context**
My machine is a 32G V100.
The maximum audio length in my data set is 8 seconds with a sample rate of 22050.
This problem still occurs when the batch size is set to 2

**Comment by leng-yue** [comment]
Can you try the latest version with grad checkpointing enabled?

**Comment by leng-yue** [comment]
You can also try reduce the squence length from 4096 to 1024 when finetuning.

**Comment by XierHacker** [comment]
The problem was solved after updating to the latest code.
My configuration is as follows:
（flash-attention is not used）
precision:32
batch_size: 8
memory: 31G

**Comment by leng-yue** [comment]
Cool

**Comment by leng-yue** [comment]
You can try 16-mixed, which should save another 50%.
