### ISSUE TITLE
[BUG]OSError: [Errno -9996] Invalid output device (no default output device)

### ISSUE THREAD

**Issue by pengyuange** [fishaudio/fish-speech#413]
使用的是
![screenshot-20240722-112703](https://github.com/user-attachments/assets/2aab45cb-92c7-4fe4-809f-f224c8886ee0)
然后post_api的时候报错了
![screenshot-20240722-112917](https://github.com/user-attachments/assets/f16c1101-8c57-480b-ba4f-1bccf7886625)

![screenshot-20240722-112939](https://github.com/user-attachments/assets/c3317494-6b90-428a-9254-196972955cc0)

**Comment by AnyaCoder** [comment]
您上传的图片显示在Ubuntu上使用pyaudio时遇到ALSA（Advanced Linux Sound Architecture）库的问题，主要问题是找不到合适的音频输出设备。以下是一些排查和解决该问题的步骤：

确保ALSA已正确安装：

```bash
sudo apt-get update
sudo apt-get install alsa-base alsa-utils
```
检查可用的声音设备：
运行以下命令列出可用的声音设备：

```bash
aplay -l
```
如果没有列出任何设备，可能表明声卡驱动程序或硬件有问题。

安装PulseAudio：
PulseAudio是一个在ALSA之上运行的声音服务器，可以帮助管理音频设备。

```bash
sudo apt-get install pulseaudio
```

配置PulseAudio：
确保PulseAudio正在运行：

```bash
pulseaudio --start
```
检查用户对音频设备的访问权限：
确保您的用户是audio组的成员：

```bash
sudo usermod -aG audio $USER
```
注销并重新登录以使更改生效。

使用一个简单的Python脚本进行测试：
创建一个简单的Python脚本检查pyaudio是否可以访问音频设备：

```python
import pyaudio

p = pyaudio.PyAudio()
for i in range(p.get_device_count()):
    print(p.get_device_info_by_index(i))
```
检查PyAudio错误：
确保PyAudio已正确安装并更新：

```bash
pip install pyaudio --upgrade
```

**Comment by pengyuange** [comment]
> 您上传的图片显示在Ubuntu上使用pyaudio时遇到ALSA（Advanced Linux Sound Architecture）库的问题，主要问题是找不到合适的音频输出设备。以下是一些排查和解决该问题的步骤：
> 
> 确保ALSA已正确安装：
> 
> ```shell
> sudo apt-get update
> sudo apt-get install alsa-base alsa-utils
> ```
> 
> 检查可用的声音设备： 运行以下命令列出可用的声音设备：
> 
> ```shell
> aplay -l
> ```
> 
> 如果没有列出任何设备，可能表明声卡驱动程序或硬件有问题。
> 
> 安装PulseAudio： PulseAudio是一个在ALSA之上运行的声音服务器，可以帮助管理音频设备。
> 
> ```shell
> sudo apt-get install pulseaudio
> ```
> 
> 配置PulseAudio： 确保PulseAudio正在运行：
> 
> ```shell
> pulseaudio --start
> ```
> 
> 检查用户对音频设备的访问权限： 确保您的用户是audio组的成员：
> 
> ```shell
> sudo usermod -aG audio $USER
> ```
> 
> 注销并重新登录以使更改生效。
> 
> 使用一个简单的Python脚本进行测试： 创建一个简单的Python脚本检查pyaudio是否可以访问音频设备：
> 
> ```python
> import pyaudio
> 
> p = pyaudio.PyAudio()
> for i in range(p.get_device_count()):
>     print(p.get_device_info_by_index(i))
> ```
> 
> 检查PyAudio错误： 确保PyAudio已正确安装并更新：
> 
> ```shell
> pip install pyaudio --upgrade
> ```

非常感谢，看来是没声卡
![image](https://github.com/user-attachments/assets/e455d46a-89f8-462d-8720-bd49f480e230)
