### ISSUE TITLE
[Feature]生成音频时能设置语速吗？

### ISSUE THREAD

**Issue by smallkeyonce** [fishaudio/fish-speech#415]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Stardust-minus** [comment]
暂时不能，可以通过变更参考音频语速的方法实现。
