### ISSUE TITLE
[BUG] 推理的时候，使用codes_0.npy 和 codes_1.npy 有什么区别

### ISSUE THREAD

**Issue by pengyuange** [fishaudio/fish-speech#416]
![image](https://github.com/user-attachments/assets/6924d340-512d-44e2-9012-593f5fd6c4fb)
这个可能生成n个npy的文件，使用哪个比较好，听起来都差不太多

**Comment by Stardust-minus** [comment]
是LLAMA生成的不同结果，本质上没有差别。
