### ISSUE TITLE
[Feature] existing streaming latency is still takes time,

### ISSUE THREAD

**Issue by kunci115** [fishaudio/fish-speech#417]
streaming in 4090 tooks more than 2 second depend on length of token, is there a way to yield it/return while the engine still generating?

**Comment by Stardust-minus** [comment]
PR Welcome

**Comment by PoTaTo-Mika** [comment]
Please compile the model, or try the quantized version.

**Comment by kunci115** [comment]
@PoTaTo-Mika  what do you mean by compile the model ? also how to do quantized version? since I only do steps for inference in english documentation

**Comment by PoTaTo-Mika** [comment]
there's a python file called quantize.py, you can view the file and choose to quantize.
![image](https://github.com/user-attachments/assets/f1e54be0-7a7e-4366-ac55-100af3643ae6)

**Comment by kunci115** [comment]
> there's a python file called quantize.py, you can view the file and choose to quantize. ![image](https://private-user-images.githubusercontent.com/148920650/351576756-f1e54be0-7a7e-4366-ac55-100af3643ae6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3OTY3NjQsIm5iZiI6MTcyMTc5NjQ2NCwicGF0aCI6Ii8xNDg5MjA2NTAvMzUxNTc2NzU2LWYxZTU0YmUwLTdhN2UtNDM2Ni1hYzU1LTEwMGFmMzY0M2FlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwNDQ3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGQ5Zjc2ZmQyNTM1ZDZmODc1YzhiZWU3NjgyOGNjZDRlY2I3NjM0N2FiZWZjODUwNGUzODQzYzQ2Y2U4YWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vQgR3jAzbohyMOQiaT2tWK-Ueu3VFU1ptfwo2B5f-qw)

its creating me a folder quantized version of the model now, just run it like previous run with that checkpoints model? still got the same latency
