### ISSUE TITLE
[BUG] 运行窗口出现如下代码，单击后程序自动退出。

### ISSUE THREAD

**Issue by geforce213** [fishaudio/fish-speech#418]
Active code page: 65001
"HF_ENDPOINT: https://hf-mirror.com"
"NO_PROXY: localhost, 127.0.0.1, 0.0.0.0"
The system cannot find the path specified.
Debug: flags = --listen 0.0.0.0:8080 --llama-checkpoint-path "checkpoints/fish-speech-1.2-sft" --decoder-checkpoint-path "checkpoints/fish-speech-1.2-sft/firefly-gan-vq-fsq-4x1024-42hz-generator.pth" --decoder-config-name firefly_gan_vq

Next launch the page...
The system cannot find the path specified.
Press any key to continue . . .

**Comment by AnyaCoder** [comment]
先按照文档里的步骤装好环境。

**Comment by YukiChoco** [comment]
我也一样

**Comment by Tezozomoctli** [comment]
I have a similar issue. When I try to run start.bat I get this:

Active code page: 65001
"HF_ENDPOINT: https://hf-mirror.com"
"NO_PROXY: localhost, 127.0.0.1, 0.0.0.0"

There are special characters in the current path, please make the path of fish-speech free of special characters before running.
Press any key to continue . . .

I already created my virtual environment with at the beginning. I did all of these steps in the venv:

# Create a python 3.10 virtual environment, you can also use virtualenv
conda create -n fish-speech python=3.10
conda activate fish-speech

# Install pytorch
pip3 install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu121

# Install fish-speech
pip3 install -e .

# (Enable acceleration) Install triton-windows
pip install https://github.com/AnyaCoder/fish-speech/releases/download/v0.1.0/triton_windows-0.1.0-py3-none-any.whl

But, I still go that issue. 

Am I missing something?
