### ISSUE TITLE
[BUG] Segmentation fault in inference

### ISSUE THREAD

**Issue by MengWenkui** [fishaudio/fish-speech#421]
<img width="630" alt="image" src="https://github.com/user-attachments/assets/00e4f296-676a-4bc1-801c-245bbf6f4c29">
<img width="872" alt="image" src="https://github.com/user-attachments/assets/bae504d9-0170-4cb4-a58b-7336d5c6ec63">

安装后尝试从命令行推理，或者是尝试从api 发post请求推理，都报了 类似如下的错：
2024-07-24 10:15:09.192 | INFO     | __main__:main:84 - Loaded audio with 36.35 seconds
Segmentation fault

每次都识别语音文件和时长，就是接着就会段错误。我的音频都是正常能播放的音频。

推理命令如下：python3 tools/vqgan/inference.py  -i "ref_data/mwk_1.wav"   --checkpoint-path "checkpoints/fish-speech-1.2-sft/firefly-gan-vq-fsq-4x1024-42hz-generator.pth"

**Comment by beibidesr** [comment]
我也遇到了同样的问题

**Comment by CodeLyokoscj** [comment]
Same issue...

**Comment by Stardust-minus** [comment]
#515 Change title to English.

**Comment by clumsyroot** [comment]
可能和使用的docker镜像有关。或许可以换个镜像试试。
