### ISSUE TITLE
使用LORA

### ISSUE THREAD

**Issue by one-pip** [fishaudio/fish-speech#428]
训练的时候如何像版本V1.12，取消使用LORA

**Comment by AnyaCoder** [comment]
更新代码后就可以了

**Comment by one-pip** [comment]
更新哪里的代码？请指教，谢谢

> 更新代码后就可以了

**Comment by one-pip** [comment]
> 用webui的情况：LLAMA配置页取消勾选"使用LoRA". 用命令行的情况： 不加+lora那个参数

1.2版本， WEBUI 的LLAMA配置页不可以取消勾选"使用LORA"

**Comment by AnyaCoder** [comment]
> > 用webui的情况：LLAMA配置页取消勾选"使用LoRA". 用命令行的情况： 不加+lora那个参数
> 
> 1.2版本， WEBUI 的LLAMA配置页不可以取消勾选"使用LORA"

现在git pull之后就行，你试试

**Comment by one-pip** [comment]
> > > 用webui的情况：LLAMA配置页取消勾选"使用LoRA". 用命令行的情况： 不加+lora那个参数
> > 
> > 
> > 1.2版本， WEBUI 的LLAMA配置页不可以取消勾选"使用LORA"
> 
> 现在git pull之后就行，你试试

可以了，谢谢

**Comment by one-pip** [comment]
> > > > 用webui的情况：LLAMA配置页取消勾选"使用LoRA". 用命令行的情况： 不加+lora那个参数
> > > 
> > > 
> > > 1.2版本， WEBUI 的LLAMA配置页不可以取消勾选"使用LORA"
> > 
> > 
> > 现在git pull之后就行，你试试
> 
> 可以了，谢谢

这个训练完后。*.skpt的文件放在哪个文件夹读取？

**Comment by AnyaCoder** [comment]
先用tools\extract_model.py提取出不含优化器的模型:
```bash
python tools\extract_model.py {*.ckpt路径} {model.pth}
```
然后复制一份checkpoints/fish-speech-1.2-sft，也放在checkpoints下，这个文件夹改名为 `fs-1.2-ft-{随便取名}`, 拿刚才的model.pth替换里面的model.pth。最后，在webui中选择之。

**Comment by jizh18** [comment]
您好，我按照上述步骤操作后，显示 
File "/home/tt/anaconda3/envs/fish/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/tt/anaconda3/envs/fish/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tt/anaconda3/envs/fish/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/tt/fish/fish-speech/tools/llama/generate.py", line 679, in main
    for response in generator:
  File "/home/tt/fish/fish-speech/tools/llama/generate.py", line 521, in generate_long
    assert (codes >= 0).all(), f"Negative code found"
AssertionError: Negative code found

> 先用tools\extract_model.py提取出不含优化器的模型:
> 
> ```shell
> python tools\extract_model.py {*.ckpt路径} {model.pth}
> ```
> 
> 然后复制一份checkpoints/fish-speech-1.2-sft，也放在checkpoints下，这个文件夹改名为 `fs-1.2-ft-{随便取名}`, 拿刚才的model.pth替换里面的model.pth。最后，在webui中选择之。

**Comment by Xiaodu233** [comment]
> 先用tools\extract_model.py提取出不含优化器的模型:
> 
> ```shell
> python tools\extract_model.py {*.ckpt路径} {model.pth}
> ```
> 
> 然后复制一份checkpoints/fish-speech-1.2-sft，也放在checkpoints下，这个文件夹改名为 `fs-1.2-ft-{随便取名}`, 拿刚才的model.pth替换里面的model.pth。最后，在webui中选择之。

你好，按照您的步骤操作后，在web推理界面中进行生成，会有以下报错
```
2024-07-30 22:15:56.514 | INFO     | tools.api:encode_reference:117 - No reference audio provided
2024-07-30 22:15:56.520 | INFO     | tools.llama.generate:generate_long:432 - Encoded text: 这座法属岛屿拥有世界上最大, 最深的泻湖之一,
2024-07-30 22:15:56.526 | INFO     | tools.llama.generate:generate_long:432 - Encoded text: 周围环绕着近一百英里长的珊瑚礁.
2024-07-30 22:15:56.526 | INFO     | tools.llama.generate:generate_long:450 - Generating sentence 1/2 of sample 1/1
100%|█████████████████████████████████████████████████████████████████████████████| 1023/1023 [00:07<00:00, 133.12it/s]
2024-07-30 22:16:04.241 | INFO     | tools.llama.generate:generate_long:496 - Compilation time: 7.72 seconds
2024-07-30 22:16:04.241 | INFO     | tools.llama.generate:generate_long:505 - Generated 1024 tokens in 7.72 seconds, 132.66 tokens/sec
2024-07-30 22:16:04.241 | INFO     | tools.llama.generate:generate_long:508 - Bandwidth achieved: 65.04 GB/s
2024-07-30 22:16:04.247 | INFO     | tools.llama.generate:generate_long:513 - GPU Memory used: 1.61 GB
Traceback (most recent call last):
  File "E:\AI_Tools\Fish-Speech\fishenv\env\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "E:\AI_Tools\Fish-Speech\fishenv\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\AI_Tools\Fish-Speech\fishenv\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "E:\AI_Tools\Fish-Speech\fishenv\env\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "E:\AI_Tools\Fish-Speech\fishenv\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\AI_Tools\Fish-Speech\fishenv\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "E:\AI_Tools\Fish-Speech\fishenv\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "E:\AI_Tools\Fish-Speech\fishenv\env\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "E:\AI_Tools\Fish-Speech\tools\webui.py", line 252, in inference_wrapper
    result = inference_with_auto_rerank(
  File "E:\AI_Tools\Fish-Speech\tools\webui.py", line 203, in inference_with_auto_rerank
    _, (sample_rate, audio), message = _
TypeError: cannot unpack non-iterable NoneType object
```
选择是否编译模型和启用参考音频都会报错

**Comment by AnyaCoder** [comment]
换其他文本有类似问题么？

**Comment by Xiaodu233** [comment]
更换过文本内容、语言，出现相同的报错情况

> 换其他文本有类似问题么？

**Comment by one-pip** [comment]
我也试过了，也是不行。期待大佬的更新。

**Comment by AnyaCoder** [comment]
奇怪，我们无法复现你们的问题。默认模型，默认参数。
![QQ_1722490129550](https://github.com/user-attachments/assets/7ecae8db-b8f4-42b0-b127-2e3dda1e9414)
![QQ_1722490146765](https://github.com/user-attachments/assets/e768e0aa-e51d-4d5d-97ae-3d2570f1f106)

**Comment by Xiaodu233** [comment]
重新调整了数据集，可能是之前的语音太零碎了，平均2-5秒这样，有断的只说了一个词这样的，所以重新连接成了1-2分钟的语音，重新训练后就正常了。麻烦您的关注和测试了！

> 奇怪，我们无法复现你们的问题。 以下情况都进行了实验。
> 
> * [x]  默认模型，默认参数。
> * [x]  微调模型，默认参数。
> * [x]  微调模型，默认参数，参考音频。
>   也许和数据集有关。
>   ![QQ_1722490129550](https://private-user-images.githubusercontent.com/122108331/354091480-7ecae8db-b8f4-42b0-b127-2e3dda1e9414.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDk3MDcsIm5iZiI6MTcyMjYwOTQwNywicGF0aCI6Ii8xMjIxMDgzMzEvMzU0MDkxNDgwLTdlY2FlOGRiLWI4ZjQtNDJiMC1iMTI3LTJlM2RkYTFlOTQxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxNDM2NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODI2ZmJiMjU5NWVhYjU5NDJmYjNmYzNhNWY0MzM1YTVlMDc1NmIxYmYwZmMxMGVkNzAxZDc4MDkxMDcxNjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sY5JvdVNWsSngR2T3-p9KZqORDeZZxTMDqVN5fOtE1Y)
>   ![QQ_1722490146765](https://private-user-images.githubusercontent.com/122108331/354091556-e768e0aa-e51d-4d5d-97ae-3d2570f1f106.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDk3MDcsIm5iZiI6MTcyMjYwOTQwNywicGF0aCI6Ii8xMjIxMDgzMzEvMzU0MDkxNTU2LWU3NjhlMGFhLWU1MWQtNGQ1ZC05N2FlLTNkMjU3MGYxZjEwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxNDM2NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTc4MTAzOTBhOGI5MGQwYjgxMzI0MjUwNDQ3OTcyYzE2ODM3ODA3YWIwMDU3MTQyMWYwZmQ2MWMyYmI4MGNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S6a9jXlV1KiHtjTStgw7es7U2xY3125u4-dj8bVobhw)

**Comment by ouyang-yuxuan** [comment]
> 您好，我按照上述步骤操作后，显示 File "/home/tt/anaconda3/envs/fish/lib/python3.10/site-packages/click/core.py", line 1078, in main rv = self.invoke(ctx) File "/home/tt/anaconda3/envs/fish/lib/python3.10/site-packages/click/core.py", line 1434, in invoke return ctx.invoke(self.callback, **ctx.params) File "/home/tt/anaconda3/envs/fish/lib/python3.10/site-packages/click/core.py", line 783, in invoke return __callback(*args, **kwargs) File "/home/tt/fish/fish-speech/tools/llama/generate.py", line 679, in main for response in generator: File "/home/tt/fish/fish-speech/tools/llama/generate.py", line 521, in generate_long assert (codes >= 0).all(), f"Negative code found" AssertionError: Negative code found
> 
> > 先用tools\extract_model.py提取出不含优化器的模型:
> > ```shell
> > python tools\extract_model.py {*.ckpt路径} {model.pth}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后复制一份checkpoints/fish-speech-1.2-sft，也放在checkpoints下，这个文件夹改名为 `fs-1.2-ft-{随便取名}`, 拿刚才的model.pth替换里面的model.pth。最后，在webui中选择之。

我也出现了相同问题：
2024-08-08 10:07:22.574 | INFO     | __main__:llama_lora_merge:650 - ['python', 'tools/llama/merge_lora.py', '--lora-config', 'r_8_alpha_16', '--lora-weight', 'results/YF/checkpoints/step_000003100.ckpt', '--output', 'checkpoints/merged_20240808_100722']
2024-08-08 10:07:27.249 | INFO     | __main__:merge:23 - Merging checkpoints/fish-speech-1.2-sft and results/YF/checkpoints/step_000003100.ckpt into checkpoints\merged_20240808_100722 with r_8_alpha_16
2024-08-08 10:07:27.336 | INFO     | __main__:merge:31 - Loaded lora model with config LoraConfig(r=8, lora_alpha=16, lora_dropout=0.01)
2024-08-08 10:07:36.543 | WARNING  | fish_speech.models.text2semantic.llama:from_pretrained:394 - No weight for embeddings.lora_A
...................

2024-08-08 10:07:36.583 | WARNING  | fish_speech.models.text2semantic.llama:from_pretrained:394 - No weight for fast_output.lora_B
2024-08-08 10:07:36.591 | INFO     | __main__:merge:38 - Loaded llama model
2024-08-08 10:07:40.362 | INFO     | __main__:merge:65 - Found 203 keys in llama model
2024-08-08 10:07:40.363 | INFO     | __main__:merge:66 - Found 203 keys in lora model
Traceback (most recent call last):
  File "D:\AI\AIB\TTS\fish-speech\tools\llama\merge_lora.py", line 95, in <module>
    merge()
  File "D:\AI\AIB\TTS\fish-speech\fishenv\env\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\AI\AIB\TTS\fish-speech\fishenv\env\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\AI\AIB\TTS\fish-speech\fishenv\env\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\AI\AIB\TTS\fish-speech\fishenv\env\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\AI\AIB\TTS\fish-speech\tools\llama\merge_lora.py", line 69, in merge
    llama_model.load_state_dict(merged_state_dict, strict=True)
  File "D:\AI\AIB\TTS\fish-speech\fishenv\env\lib\site-packages\torch\nn\modules\module.py", line 2191, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DualARTransformer:
        Missing key(s) in state_dict: "embeddings.lora_A", "embeddings.lora_B", "codebook_embeddings.lora_A", "codebook_embeddings.lora_B", "layers.0.attention.wqkv.lora_A", "layers.0.attention.wqkv.lora_B", "layers.0.attention.wo.lora_A", "layers.0.attention.wo.lora_B", "layers.0.feed_forward.w1.lora_A", "layers.0.feed_forward.w1.lora_B", "layers.0.feed_forward.w3.lora_A", "layers.0.feed_forward.w3.lora_B", "layers.0.feed_forward.w2.lora_A", "layers.0.feed_forward.w2.lora_B", "layers.1.attention.wqkv.lora_A", "layers.1.attention.wqkv.lora_B", "layers.1.attention.wo.lora_A", "layers.1.attention.wo.lora_B", "layers.1.feed_forward.w1.lora_A", "layers.1.feed_forward.w1.lora_B", "layers.1.feed_forward.w3.lora_A", "layers.1.feed_forward.w3.lora_B", "layers.1.feed_forward.w2.lora_A", "layers.1.feed_forward.w2.lora_B", "layers.2.attention.wqkv.lora_A", "layers.2.attention.wqkv.lora_B", "layers.2.attention.wo.lora_A", "layers.2.attention.wo.lora_B", "layers.2.feed_forward.w1.lora_A", "layers.2.feed_forward.w1.lora_B", "layers.2.feed_forward.w3.lora_A", "layers.2.feed_forward.w3.lora_B", "layers.2.feed_forward.w2.lora_A", "layers.2.feed_forward.w2.lora_B", "layers.3.attention.wqkv.lora_A", "layers.3.attention.wqkv.lora_B", "layers.3.attention.wo.lora_A", "layers.3.attention.wo.lora_B", "layers.3.feed_forward.w1.lora_A", "layers.3.feed_forward.w1.lora_B", "layers.3.feed_forward.w3.lora_A", "layers.3.feed_forward.w3.lora_B", "layers.3.feed_forward.w2.lora_A", "layers.3.feed_forward.w2.lora_B", "layers.4.attention.wqkv.lora_A", "layers.4.attention.wqkv.lora_B", "layers.4.attention.wo.lora_A", "layers.4.attention.wo.lora_B", "layers.4.feed_forward.w1.lora_A", "layers.4.feed_forward.w1.lora_B", "layers.4.feed_forward.w3.lora_A", "layers.4.feed_forward.w3.lora_B", "layers.4.feed_forward.w2.lora_A", "layers.4.feed_forward.w2.lora_B", "layers.5.attention.wqkv.lora_A", "layers.5.attention.wqkv.lora_B", "layers.5.attention.wo.lora_A", "layers.5.attention.wo.lora_B", "layers.5.feed_forward.w1.lora_A", "layers.5.feed_forward.w1.lora_B", "layers.5.feed_forward.w3.lora_A", "layers.5.feed_forward.w3.lora_B", "layers.5.feed_forward.w2.lora_A", "layers.5.feed_forward.w2.lora_B", "layers.6.attention.wqkv.lora_A", "layers.6.attention.wqkv.lora_B", "layers.6.attention.wo.lora_A", "layers.6.attention.wo.lora_B", "layers.6.feed_forward.w1.lora_A", "layers.6.feed_forward.w1.lora_B", "layers.6.feed_forward.w3.lora_A", "layers.6.feed_forward.w3.lora_B", "layers.6.feed_forward.w2.lora_A", "layers.6.feed_forward.w2.lora_B", "layers.7.attention.wqkv.lora_A", "layers.7.attention.wqkv.lora_B", "layers.7.attention.wo.lora_A", "layers.7.attention.wo.lora_B", "layers.7.feed_forward.w1.lora_A", "layers.7.feed_forward.w1.lora_B", "layers.7.feed_forward.w3.lora_A", "layers.7.feed_forward.w3.lora_B", "layers.7.feed_forward.w2.lora_A", "layers.7.feed_forward.w2.lora_B", "layers.8.attention.wqkv.lora_A", "layers.8.attention.wqkv.lora_B", "layers.8.attention.wo.lora_A", "layers.8.attention.wo.lora_B", "layers.8.feed_forward.w1.lora_A", "layers.8.feed_forward.w1.lora_B", "layers.8.feed_forward.w3.lora_A", "layers.8.feed_forward.w3.lora_B", "layers.8.feed_forward.w2.lora_A", "layers.8.feed_forward.w2.lora_B", "layers.9.attention.wqkv.lora_A", "layers.9.attention.wqkv.lora_B", "layers.9.attention.wo.lora_A", "layers.9.attention.wo.lora_B", "layers.9.feed_forward.w1.lora_A", "layers.9.feed_forward.w1.lora_B", "layers.9.feed_forward.w3.lora_A", "layers.9.feed_forward.w3.lora_B", "layers.9.feed_forward.w2.lora_A", "layers.9.feed_forward.w2.lora_B", "layers.10.attention.wqkv.lora_A", "layers.10.attention.wqkv.lora_B", "layers.10.attention.wo.lora_A", "layers.10.attention.wo.lora_B", "layers.10.feed_forward.w1.lora_A", "layers.10.feed_forward.w1.lora_B", "layers.10.feed_forward.w3.lora_A", "layers.10.feed_forward.w3.lora_B", "layers.10.feed_forward.w2.lora_A", "layers.10.feed_forward.w2.lora_B", "layers.11.attention.wqkv.lora_A", "layers.11.attention.wqkv.lora_B", "layers.11.attention.wo.lora_A", "layers.11.attention.wo.lora_B", "layers.11.feed_forward.w1.lora_A", "layers.11.feed_forward.w1.lora_B", "layers.11.feed_forward.w3.lora_A", "layers.11.feed_forward.w3.lora_B", "layers.11.feed_forward.w2.lora_A", "layers.11.feed_forward.w2.lora_B", "layers.12.attention.wqkv.lora_A", "layers.12.attention.wqkv.lora_B", "layers.12.attention.wo.lora_A", "layers.12.attention.wo.lora_B", "layers.12.feed_forward.w1.lora_A", "layers.12.feed_forward.w1.lora_B", "layers.12.feed_forward.w3.lora_A", "layers.12.feed_forward.w3.lora_B", "layers.12.feed_forward.w2.lora_A", "layers.12.feed_forward.w2.lora_B", "layers.13.attention.wqkv.lora_A", "layers.13.attention.wqkv.lora_B", "layers.13.attention.wo.lora_A", "layers.13.attention.wo.lora_B", "layers.13.feed_forward.w1.lora_A", "layers.13.feed_forward.w1.lora_B", "layers.13.feed_forward.w3.lora_A", "layers.13.feed_forward.w3.lora_B", "layers.13.feed_forward.w2.lora_A", "layers.13.feed_forward.w2.lora_B", "layers.14.attention.wqkv.lora_A", "layers.14.attention.wqkv.lora_B", "layers.14.attention.wo.lora_A", "layers.14.attention.wo.lora_B", "layers.14.feed_forward.w1.lora_A", "layers.14.feed_forward.w1.lora_B", "layers.14.feed_forward.w3.lora_A", "layers.14.feed_forward.w3.lora_B", "layers.14.feed_forward.w2.lora_A", "layers.14.feed_forward.w2.lora_B", "layers.15.attention.wqkv.lora_A", "layers.15.attention.wqkv.lora_B", "layers.15.attention.wo.lora_A", "layers.15.attention.wo.lora_B", "layers.15.feed_forward.w1.lora_A", "layers.15.feed_forward.w1.lora_B", "layers.15.feed_forward.w3.lora_A", "layers.15.feed_forward.w3.lora_B", "layers.15.feed_forward.w2.lora_A", "layers.15.feed_forward.w2.lora_B", "layers.16.attention.wqkv.lora_A", "layers.16.attention.wqkv.lora_B", "layers.16.attention.wo.lora_A", "layers.16.attention.wo.lora_B", "layers.16.feed_forward.w1.lora_A", "layers.16.feed_forward.w1.lora_B", "layers.16.feed_forward.w3.lora_A", "layers.16.feed_forward.w3.lora_B", "layers.16.feed_forward.w2.lora_A", "layers.16.feed_forward.w2.lora_B", "layers.17.attention.wqkv.lora_A", "layers.17.attention.wqkv.lora_B", "layers.17.attention.wo.lora_A", "layers.17.attention.wo.lora_B", "layers.17.feed_forward.w1.lora_A", "layers.17.feed_forward.w1.lora_B", "layers.17.feed_forward.w3.lora_A", "layers.17.feed_forward.w3.lora_B", "layers.17.feed_forward.w2.lora_A", "layers.17.feed_forward.w2.lora_B", "layers.18.attention.wqkv.lora_A", "layers.18.attention.wqkv.lora_B", "layers.18.attention.wo.lora_A", "layers.18.attention.wo.lora_B", "layers.18.feed_forward.w1.lora_A", "layers.18.feed_forward.w1.lora_B", "layers.18.feed_forward.w3.lora_A", "layers.18.feed_forward.w3.lora_B", "layers.18.feed_forward.w2.lora_A", "layers.18.feed_forward.w2.lora_B", "layers.19.attention.wqkv.lora_A", "layers.19.attention.wqkv.lora_B", "layers.19.attention.wo.lora_A", "layers.19.attention.wo.lora_B", "layers.19.feed_forward.w1.lora_A", "layers.19.feed_forward.w1.lora_B", "layers.19.feed_forward.w3.lora_A", "layers.19.feed_forward.w3.lora_B", "layers.19.feed_forward.w2.lora_A", "layers.19.feed_forward.w2.lora_B", "layers.20.attention.wqkv.lora_A", "layers.20.attention.wqkv.lora_B", "layers.20.attention.wo.lora_A", "layers.20.attention.wo.lora_B", "layers.20.feed_forward.w1.lora_A", "layers.20.feed_forward.w1.lora_B", "layers.20.feed_forward.w3.lora_A", "layers.20.feed_forward.w3.lora_B", "layers.20.feed_forward.w2.lora_A", "layers.20.feed_forward.w2.lora_B", "layers.21.attention.wqkv.lora_A", "layers.21.attention.wqkv.lora_B", "layers.21.attention.wo.lora_A", "layers.21.attention.wo.lora_B", "layers.21.feed_forward.w1.lora_A", "layers.21.feed_forward.w1.lora_B", "layers.21.feed_forward.w3.lora_A", "layers.21.feed_forward.w3.lora_B", "layers.21.feed_forward.w2.lora_A", "layers.21.feed_forward.w2.lora_B", "layers.22.attention.wqkv.lora_A", "layers.22.attention.wqkv.lora_B", "layers.22.attention.wo.lora_A", "layers.22.attention.wo.lora_B", "layers.22.feed_forward.w1.lora_A", "layers.22.feed_forward.w1.lora_B", "layers.22.feed_forward.w3.lora_A", "layers.22.feed_forward.w3.lora_B", "layers.22.feed_forward.w2.lora_A", "layers.22.feed_forward.w2.lora_B", "layers.23.attention.wqkv.lora_A", "layers.23.attention.wqkv.lora_B", "layers.23.attention.wo.lora_A", "layers.23.attention.wo.lora_B", "layers.23.feed_forward.w1.lora_A", "layers.23.feed_forward.w1.lora_B", "layers.23.feed_forward.w3.lora_A", "layers.23.feed_forward.w3.lora_B", "layers.23.feed_forward.w2.lora_A", "layers.23.feed_forward.w2.lora_B", "output.lora_A", "output.lora_B", "fast_embeddings.lora_A", "fast_embeddings.lora_B", "fast_layers.0.attention.wqkv.lora_A", "fast_layers.0.attention.wqkv.lora_B", "fast_layers.0.attention.wo.lora_A", "fast_layers.0.attention.wo.lora_B", "fast_layers.0.feed_forward.w1.lora_A", "fast_layers.0.feed_forward.w1.lora_B", "fast_layers.0.feed_forward.w3.lora_A", "fast_layers.0.feed_forward.w3.lora_B", "fast_layers.0.feed_forward.w2.lora_A", "fast_layers.0.feed_forward.w2.lora_B", "fast_layers.1.attention.wqkv.lora_A", "fast_layers.1.attention.wqkv.lora_B", "fast_layers.1.attention.wo.lora_A", "fast_layers.1.attention.wo.lora_B", "fast_layers.1.feed_forward.w1.lora_A", "fast_layers.1.feed_forward.w1.lora_B", "fast_layers.1.feed_forward.w3.lora_A", "fast_layers.1.feed_forward.w3.lora_B", "fast_layers.1.feed_forward.w2.lora_A", "fast_layers.1.feed_forward.w2.lora_B", "fast_layers.2.attention.wqkv.lora_A", "fast_layers.2.attention.wqkv.lora_B", "fast_layers.2.attention.wo.lora_A", "fast_layers.2.attention.wo.lora_B", "fast_layers.2.feed_forward.w1.lora_A", "fast_layers.2.feed_forward.w1.lora_B", "fast_layers.2.feed_forward.w3.lora_A", "fast_layers.2.feed_forward.w3.lora_B", "fast_layers.2.feed_forward.w2.lora_A", "fast_layers.2.feed_forward.w2.lora_B", "fast_layers.3.attention.wqkv.lora_A", "fast_layers.3.attention.wqkv.lora_B", "fast_layers.3.attention.wo.lora_A", "fast_layers.3.attention.wo.lora_B", "fast_layers.3.feed_forward.w1.lora_A", "fast_layers.3.feed_forward.w1.lora_B", "fast_layers.3.feed_forward.w3.lora_A", "fast_layers.3.feed_forward.w3.lora_B", "fast_layers.3.feed_forward.w2.lora_A", "fast_layers.3.feed_forward.w2.lora_B", "fast_output.lora_A", "fast_output.lora_B".

**Comment by JohnHerry** [comment]
请教各位大佬，项目中LoRA是做什么用的呢？新曾音色，还是新增语言？ 然后使用了LoRA后推理性能降低多少？

**Comment by jky-yy** [comment]
训练效果可以分享下吗？我打算训练多情感音色。不确定这个模型效果如何
