### ISSUE TITLE
Clarification on License Terms

### ISSUE THREAD

**Issue by ryan-minato** [fishaudio/fish-speech#430]
According to the documentation, the code is released under the `BSD-3-Clause`([url](https://github.com/fishaudio/fish-speech/blob/46440f25be4554800f1c4cb7a13af87854eb9378/docs/en/index.md?plain=1#L17C40-L17C63)) license. However, I noticed that the LICENSE file only includes terms for the `CC-BY-NC-SA-4.0` license.

Is this discrepancy a documentation issue, or is there an issue with the LICENSE file?

Could you please clarify the following points:

1. If I use parts of this codebase (excluding the weights) in my project, can I do so under the BSD-3-Clause license as indicated in the documentation?
2. Is the CC-BY-NC-SA-4.0 license applicable only to specific parts of the code, or does it cover the entire repository?

Thank you for your response to this matter.

**Comment by leng-yue** [comment]
Seems we forgot to update the license in the document website, the codebase, since Fish Speech 1.1,  is covered by CC-BY-NC-SA-4.0.
