### ISSUE TITLE
windows install_env.bat安装后启动失败[BUG]

### ISSUE THREAD

**Issue by Xiaodu233** [fishaudio/fish-speech#432]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**

Cannot start web-ui after installation
Used [this package](https://github.com/fishaudio/fish-speech/actions/runs/10140219634) built by Actions to install
The file that was not found is actually in `E:\AI_Tools\Fish-Speech\fishenv\env`**\Lib**`\site-packages\torch\lib\fbgemm.dll`
It is different with `E:\AI_Tools\Fish-Speech\fishenv\env`**\lib**`\site-packages\torch\lib\fbgemm.dll` in error log
So I tried to rename it but it throwed out the same error log

**To Reproduce**

1.Run install_env.bat
2.Run start.bat

**Expected behavior**

Start web-ui

**Screenshots / log**

1.After running install_env.bat
```
Environment Check: Success.
Press any key to continue . . .
```
2.After running start.bat
```
Debug: flags = --listen 0.0.0.0:8080 --llama-checkpoint-path "checkpoints/fish-speech-1.2-sft" --decoder-checkpoint-path "checkpoints/fish-speech-1.2-sft/firefly-gan-vq-fsq-4x1024-42hz-generator.pth" --decoder-config-name firefly_gan_vq

Next launch the page...
['', 'E:\\AI_Tools\\Fish-Speech\\fish_speech\\webui', 'E:\\AI_Tools\\Fish-Speech', 'E:\\AI_Tools\\Fish-Speech\\fishenv\\env\\python310.zip', 'E:\\AI_Tools\\Fish-Speech\\fishenv\\env\\DLLs', 'E:\\AI_Tools\\Fish-Speech\\fishenv\\env\\lib', 'E:\\AI_Tools\\Fish-Speech\\fishenv\\env', 'E:\\AI_Tools\\Fish-Speech\\fishenv\\env\\lib\\site-packages', '__editable__.fish_speech-0.1.0.finder.__path_hook__']
You are in  E:\AI_Tools\Fish-Speech
Traceback (most recent call last):
  File "E:\AI_Tools\Fish-Speech\fish_speech\webui\manage.py", line 1134, in <module>
    versions=versions_html(),
  File "E:\AI_Tools\Fish-Speech\fish_speech\webui\launch_utils.py", line 37, in versions_html
    import torch
  File "E:\AI_Tools\Fish-Speech\fishenv\env\lib\site-packages\torch\__init__.py", line 142, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "E:\AI_Tools\Fish-Speech\fishenv\env\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
Press any key to continue . . .
```

**Additional context**

System : Win 11 LTSC 26100.1150

**Comment by AnyaCoder** [comment]
See the docs [windows安装](https://speech.fish.audio/#windows)

**Comment by Xiaodu233** [comment]
抱歉在安装前没有仔细看文档，还以为是旧版本那样运行完 install_env.bat 就能运行
