### ISSUE TITLE
从文本生成语义 token阶段加了--compile参数会出错，找不到原因

### ISSUE THREAD

**Issue by CasonTsai** [fishaudio/fish-speech#436]
在文本生成语义token阶段，想加速，加了--compile参数，但是出现错误，去掉--compile参数就不会出错
指令如下’python tools/llama/generate.py  --text "位于中国广东省深圳市南山区粤海路1006号"  --prompt-text "The text corresponding to reference audio"     --prompt-tokens "fake.npy"   --checkpoint-path "H:\workProject\WorkProject\HangDian\dataSet\x\tts\fish-speech-1.2\checkpoints"   --num-samples 2 --compile  ‘，产生错误，
![image](https://github.com/user-attachments/assets/274f5e24-bd19-4921-b808-69c02b9717bd)
环境是：pytorch 2.3.1+cu121,gpu:rtx4060ti

**Comment by CasonTsai** [comment]
![image](https://github.com/user-attachments/assets/82d76de1-6765-4270-b029-8984ec88a896)
不知道是不是跟pytorch版本有关。

**Comment by AnyaCoder** [comment]
必须用fish自带的特制环境。
https://speech.fish.audio/#windows

**Comment by CasonTsai** [comment]
> 必须用fish自带的特制环境。 https://speech.fish.audio/#windows

嗯嗯，那就是无法整合推理代码到自己的代码对吧，除非使用fish的环境？

**Comment by AnyaCoder** [comment]
> > 必须用fish自带的特制环境。 https://speech.fish.audio/#windows
> 
> 嗯嗯，那就是无法整合推理代码到自己的代码对吧，除非使用fish的环境？

编译的情况下是这样的

**Comment by CasonTsai** [comment]
> > > 必须用fish自带的特制环境。 https://speech.fish.audio/#windows
> > 
> > 
> > 嗯嗯，那就是无法整合推理代码到自己的代码对吧，除非使用fish的环境？
> 
> 编译的情况下是这样的

好的谢谢
