### ISSUE TITLE
[BUG] Some situations encountered after enabling multiple workers

### ISSUE THREAD

**Issue by josangmi** [fishaudio/fish-speech#438]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**
直接用 --workers 2 会出现
WARNING:  You must pass the application as an import string to enable 'reload' or 'workers' 然后会退出进程，
<img width="790" alt="image" src="https://github.com/user-attachments/assets/e0cec5b1-7273-43b0-8013-7cca3fc7a35a">

**To Reproduce**
需要修改：
原代码：    uvicorn.run(app, host=host, port=int(port), workers=args.workers, log_level="info")
修改后代码：     uvicorn.run("tools.api:app", host=host, port=int(port), workers=args.workers, log_level="info")
然后就可以启动了。
但是并没有加载两个模型，理解不能同时进行推理，如果希望加载模型同时推理的话，有优化的办法吗？
还有多显卡的话，好像不能device=auto
**Expected behavior**
多workers 启动之后使用会出现
<img width="853" alt="image" src="https://github.com/user-attachments/assets/e8c6ea9b-5fb1-449b-93c4-bd9369efc348">
接下来不会改了。 谢谢。
**Screenshots / log**
If applicable, add screenshots / logs to help explain your problem.

**Additional context**

**Comment by PoTaTo-Mika** [comment]
可以尝试单机多端口进行并发。

**Comment by keepgoingwang** [comment]
原因应该是开启多进程后，args参数是由主进程获取的，子进程无法获取主进程变量。不知道后续是否会修补这个bug呢？

**Comment by Stardust-minus** [comment]
https://github.com/fishaudio/fish-speech/issues/515 Change title to English.
