### ISSUE TITLE
[Bug] After deployment is complete, the 4090 graphics card uses GPU inference for 2 minutes and the audio duration is 40 seconds. Is this normal?

### ISSUE THREAD

**Issue by 2776721779** [fishaudio/fish-speech#439]

**Comment by AnyaCoder** [comment]
开了编译吧，第一次推理要先等一段时间。要多次使用请不要分步骤推理。

**Comment by 2776721779** [comment]
没有分步推理，请问您使用的是什么显卡，40s的音频需要推理多长时间？

**Comment by AnyaCoder** [comment]
4060 laptop, 大概5s。
你把你做的所有步骤说一下。

**Comment by PoTaTo-Mika** [comment]
可能是开了auto-rerank，gradio会把下载whisper的时间记录在内。

**Comment by 2776721779** [comment]
正常部署，在服务器是win系统，你们打开的webui页面是这个吗？
![8af0dbe50f6b2b81f87d5ff0a493d7d3](https://github.com/user-attachments/assets/fbf94ca3-a831-4e3f-a131-86570875dc09)

**Comment by 2776721779** [comment]
你们是否对代码做了什么修改？还是说和pytorch版本有关？我下的是最新版本的pytorch

**Comment by AnyaCoder** [comment]
照着这些步骤开编译功能。https://speech.fish.audio/#windows

**Comment by AnyaCoder** [comment]
是的

**Comment by Stardust-minus** [comment]
#515 Change title to English.
