### ISSUE TITLE
Use webui and enable model compilation, the progress bar will stuck for a few seconds before start every times[BUG]

### ISSUE THREAD

**Issue by randoms** [fishaudio/fish-speech#440]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**
Use webui and enable model compilation, the progress bar will stuck for a few seconds before start every times

**Expected behavior**
As I understood, the model should be compiled at the very beginning only once, so when input multi sentences the progress bar should not stuck latter.

**Comment by AnyaCoder** [comment]
I guess your os is linux now? This is a problem caused by torch 2.4.0 implementation.
Downgrade torch to version ~ 2.3.0

**Comment by randoms** [comment]
I found the reason! 
[this code](https://github.com/fishaudio/fish-speech/blob/main/tools/llama/generate.py#L237) causes the `decode_one_token` function to block the first time it is called. possibly because it is recompiling the model. If I move this code to the `load_model` function, everything works smoothly.

change the code [here](https://github.com/fishaudio/fish-speech/blob/main/tools/llama/generate.py#L557) to below.
```python
def worker():
  model, decode_one_token = load_model(
      checkpoint_path, device, precision, compile=compile
  )
  with torch.device(device):
      model.setup_caches(
          max_batch_size=1, max_seq_len=4096, dtype=next(model.parameters()).dtype
      )
  init_event.set()
```

I'm not familiar with this code, but `max_seq_len` appears to be a constant, always set to 4096.

**Comment by randoms** [comment]
before

![QQ_1722579860266](https://github.com/user-attachments/assets/fcfe231d-7868-4e0d-aa1d-03275a722e1b)

after

![QQ_1722580091361](https://github.com/user-attachments/assets/c0cbfb65-7030-4e07-99c3-4fe686f32100)

I'm using windows with Nvidia 1060 TI

**Comment by AnyaCoder** [comment]
Well, that's ok though. Before torch~=2.3.0 it's changable for input tensor shape without re-compiling. 
Thanks for your exploration. We'll consider if we can change the code.

**Comment by vgabbo** [comment]
I have got the same problem but I cannot understand how to you solved it, I'm really sorry. Can you please help me? @randoms 

Inside launch_thread_safe_queue I have got:

def worker():
        model, decode_one_token = load_model(
            checkpoint_path, device, precision, compile=compile
        )
        with torch.device(device):
            model.setup_caches(
                max_batch_size=1,
                max_seq_len=model.config.max_seq_len,
                dtype=next(model.parameters()).dtype,
            )
        init_event.set()

        while True:
            item: GenerateRequest | None = input_queue.get()
            if item is None:
                break

            kwargs = item.request
            response_queue = item.response_queue

            try:
                for chunk in generate_long(
                    model=model, decode_one_token=decode_one_token, **kwargs
                ):
                    response_queue.put(
                        WrappedGenerateResponse(status="success", response=chunk)
                    )
            except Exception as e:
                response_queue.put(WrappedGenerateResponse(status="error", response=e))
                
 What parts am I supposed to move to load_model?

**Comment by vgabbo** [comment]
I think it might be the same problem, but it's not clear to me. I tried reducing the max new tokens but still I have got long waits for each generation @randoms 
I'm a bit desperate.. 

2024-10-18 13:57:03.316 | INFO     | __main__:generate_long:466 - Generating sentence 1/1 of sample 1/1
  0%|                                                  | 0/3927 [00:00<?, ?it/s]/usr/lib/python3.12/contextlib.py:105: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)
  0%|                                       | 1/3927 [00:13<14:54:51, 13.68s/it]/usr/lib/python3.12/contextlib.py:105: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)
  0%|                                        | 2/3927 [00:13<6:13:26,  5.71s/it]/usr/lib/python3.12/contextlib.py:105: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)
  9%|███▌                                    | 346/3927 [00:18<00:46, 76.40it/s]^C
  9%|███▋                                    | 359/3927 [00:18<03:04, 19.38it/s]
