### ISSUE TITLE
 No module named 'torch.nn.attention'这个是torch版本问题吗？该如何解决？[BUG]

### ISSUE THREAD

**Issue by HAS-1314** [fishaudio/fish-speech#441]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / log**
If applicable, add screenshots / logs to help explain your problem.

**Additional context**

**Comment by AnyaCoder** [comment]
降级torch ~= 2.3.0

**Comment by PoTaTo-Mika** [comment]
2.4版本有一些api爆炸了，需要pip install torch==2.3.0

**Comment by hildazzz** [comment]
我的torch版本是2.2.1，也会报这个错误。请问如何解决呢？

**Comment by Stardust-minus** [comment]
> 我的torch版本是2.2.1，也会报这个错误。请问如何解决呢？

最低要求2.3.0

**Comment by hildazzz** [comment]
> > 我的torch版本是2.2.1，也会报这个错误。请问如何解决呢？
> 
> 最低要求2.3.0

好的谢谢
