### ISSUE TITLE
[Feature]想了解下推理速度与显存消耗

### ISSUE THREAD

**Issue by Ming-Zhou0201** [fishaudio/fish-speech#442]
如题，文档中没有关于GPU下TTS推理性能的情况，想大致了解下
另外 中英混 的效果如何呢？
🙏🙏

**Comment by PoTaTo-Mika** [comment]
4060推理大约15tokens/s，具体效果可以自行测试。

**Comment by Ming-Zhou0201** [comment]
> 4060推理大约15tokens/s，具体效果可以自行测试。

感谢大佬

**Comment by Xiaodu233** [comment]
我这里4060推理大约30tokens/s，编译后大约130tokens/s

**Comment by Zhmz** [comment]
请问下，“编译后”是指加streaming=True这个编译参数吗，我这边加上之后，速度没怎么变，还是30tokens/s呢。

**Comment by PoTaTo-Mika** [comment]
自己看文档

**Comment by PoTaTo-Mika** [comment]
> 请问下，“编译后”是指加streaming=True这个编译参数吗，我这边加上之后，速度没怎么变，还是30tokens/s呢。

自己看文档
