### ISSUE TITLE
[BUG] 3080 TI and it's still slow even with --compile

### ISSUE THREAD

**Issue by ftk789** [fishaudio/fish-speech#444]
3080 TI and it's still slow even with --compile it takes like 120 seconds at least even with small text input

**Comment by leng-yue** [comment]
Which are you using? API or CLI?

**Comment by PoTaTo-Mika** [comment]
1.check if you use auto_rerank(use faster_whisper for infer in webui).
2.please show us the picture of the terminal.

**Comment by ftk789** [comment]
1. I downloaded it by cloning the whole repo, Then running `install_env.bat` 
2. I run the console `run_cmd.bat` To ensure I'm in the right environment
3. I tried all ways that it can provide:
  1. using the CLI:
  
![image](https://github.com/user-attachments/assets/12ce0c52-36c6-41f6-99c6-19ebba31abb8)
The command above took some time but it's not as slow.
After getting the .npy file:
![image](https://github.com/user-attachments/assets/5674d1c1-cbe4-4ffc-8d61-ce2e42dceea5)

This one took the same duration, about 10-25 seconds

Then for generating the audio:

![image](https://github.com/user-attachments/assets/5c7bb995-0754-48b8-8fb1-a69f045ac198)

This one was like 3-6 seconds.

Overall it adds up over 60 seconds for only a small input.

It goes the same for the API, And the WebUI.

{A NOTICE}: I don't use --compile because of an error I get saying I don't have a CC compiler, Yet I `set CC=[Directoy of CL.exe from microsoft studio]` and it gives another error:

![image](https://github.com/user-attachments/assets/88e5206f-7707-4791-919b-0c1e282775b8)


  
  Sorry if I couldn't explain more.

**Comment by ftk789** [comment]
![image](https://github.com/user-attachments/assets/d0048752-6f62-475b-899f-a0204ecc2936)

This is another example using the API. Look how long it took! Also sometimes it's unclear what the TTS speaks as well...

**Comment by AnyaCoder** [comment]
> {A NOTICE}: I didn't't use --compile this time because of an error I get saying I don't have a CC compiler, Yet I set CC=[Directoy of CL.exe from microsoft studio] and it gives another error:

Hmm... Maybe the docs don't mandate this, and that's what led to your misunderstanding. I'll make it clear to you now that in order to use the compile function in a windows environment, you have to follow the documentation's instructions for installing the environment. Once done, please edit API_FLAGS.txt to the following format:
```bat
--infer
# --api
--listen ... \
... \
--compile
```
Then click start.bat again to get the acceleration.

**Comment by ftk789** [comment]
> > {A NOTICE}: I didn't't use --compile this time because of an error I get saying I don't have a CC compiler, Yet I set CC=[Directoy of CL.exe from microsoft studio] and it gives another error:
> 
> Hmm... Maybe the docs don't mandate this, and that's what led to your misunderstanding. Remove the CC environment variables you set first. I'll make it clear to you now that in order to use the compile function in a windows environment, you have to follow the documentation's instructions for installing the environment. Once done, please edit `API_FLAGS.txt` to the following format:
> 
> ```batchfile
> --infer
> # --api
> # --listen ... \
> ... \
> --compile
> ```
> 
> Then click `start.bat` again to get the acceleration.

Ok now assuming I wanna use the API version, How?

**Comment by ftk789** [comment]
> edit `API_FLAGS.txt` to the following format:
> 
> ```batchfile
> # --infer
> --api
> --listen ... \
> ... \
> --compile
> ```
> 
> Then click `start.bat`.

Ok I tried that, Yet it still gives the compile error.

And I think my issue here is that clang is not properly being called when --compile is passed:

![image](https://github.com/user-attachments/assets/91f075f6-703e-4c35-8b36-56116d99c084)

I have visual studio as well and doing `clang --version` in my CMD insures that it's working.

**Comment by AnyaCoder** [comment]
Do you have visual studio c++ development environment installed?

**Comment by ftk789** [comment]
> Do you have visual studio c++ development environment installed?

Yes I do, I have 2015, 2017, and 2022 installed, I can check that by searching `x64 Native Tools Command Prompt for VS 2019` in the windows search bar and opening it:

![image](https://github.com/user-attachments/assets/b13a1bca-a37f-4089-aad6-3637ced06230)

**Comment by AnyaCoder** [comment]
Let's see, that shouldn't happen.
I think you can try uninstalling all versions of MSVC++ and reinstalling the 2022 version of the development tools.

**Comment by ftk789** [comment]
> Let's see, that shouldn't happen. I think you can try uninstalling all versions of MSVC++ and reinstalling the 2022 version of the development tools.

This Was the fix, Now it does almost 300 iterations per second which is blazingly fast! Thank you so much for your kind help <3

**Comment by Emersonksc** [comment]
> > Let's see, that shouldn't happen. I think you can try uninstalling all versions of MSVC++ and reinstalling the 2022 version of the development tools.
> 
> This Was the fix, Now it does almost 300 iterations per second which is blazingly fast! Thank you so much for your kind help <3
Hey, bro, what version of PyTorch did you use? And which language did you run your inference in? I’ve got a 3090, but I
only hit about 200 iterations per second, how you reach 300it/s for 3080ti
