### ISSUE TITLE
[BUG]官网的API页面，充值了但是一直看不到额度，刷新页面提示：Internal Server Error

### ISSUE THREAD

**Issue by YoungWiller** [fishaudio/fish-speech#445]
官网的API页面，充值了但是一直看不到额度，刷新页面提示：Internal Server Error

想测试一下官方的api

![WX20240804-130424](https://github.com/user-attachments/assets/29ff889d-75f1-49dd-b1cb-059094e245bc)

这块充值规则是什么样的呢？

**Comment by Stardust-minus** [comment]
Fixed.
