### ISSUE TITLE
[BUG] WeTextProcessing not available in Windows.

### ISSUE THREAD

**Issue by Memory2414** [fishaudio/fish-speech#45]
I follow the interface guide （https://speech.fish.audio/inference/）
![image](https://github.com/fishaudio/fish-speech/assets/50972228/b86092fa-e91b-4c81-801b-0824bb6ab800)
This step requires running "tools/llama/generate.py" , but i can't install "WeTextProcessing" (bucause "Pynini" doesn't seem to support "Windows") .

Who Can Help Me , THANKS！

**Comment by leng-yue** [comment]
Thanks for reporting. Will push a fix later.

**Comment by leng-yue** [comment]
Fixed, can you give a try?
