### ISSUE TITLE
Website audio generation is giving constant Interval Server Error

### ISSUE THREAD

**Issue by csjaugustus** [fishaudio/fish-speech#455]
I am a premium user on the fish audio website and have been unable to generate audio for over 5 hours due to the constant Internal Server Error on the site. I am unsure what is causing it, as it is not providing any additional information on the error.

Alternatively I tried calling the API, and was given a 400: Bad Request response. 

Do these point to some kind of server issue or bug? 

Thank you.

**Comment by leng-yue** [comment]
Should be fixed, it's caused by a new behavior introduced in envoy.
