### ISSUE TITLE
[BUG] Nonetype when using --compile

### ISSUE THREAD

**Issue by ifounda-bug** [fishaudio/fish-speech#458]
**Describe the bug**
When using compile option with a 3090 on linux and the webui, I am getting this error:

`  0%|                                                  | 0/2047 [01:14<?, ?it/s]
Traceback (most recent call last):
  File "/run/media/user/HD3/_AI/fish speech/fish-speech/.venv/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/run/media/user/HD3/_AI/fish speech/fish-speech/.venv/lib/python3.10/site-packages/gradio/route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "/run/media/user/HD3/_AI/fish speech/fish-speech/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/run/media/user/HD3/_AI/fish speech/fish-speech/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/run/media/user/HD3/_AI/fish speech/fish-speech/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/run/media/user/HD3/_AI/fish speech/fish-speech/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/run/media/user/HD3/_AI/fish speech/fish-speech/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/run/media/user/HD3/_AI/fish speech/fish-speech/.venv/lib/python3.10/site-packages/gradio/utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "/run/media/user/HD3/_AI/fish speech/fish-speech/tools/webui.py", line 259, in inference_wrapper
    result = inference_with_auto_rerank(
  File "/run/media/user/HD3/_AI/fish speech/fish-speech/tools/webui.py", line 205, in inference_with_auto_rerank
    _, (sample_rate, audio), message = _
TypeError: cannot unpack non-iterable NoneType object`

**To Reproduce**
`!python tools/webui.py \
    --llama-checkpoint-path checkpoints/fish-speech-1.2-sft \
    --decoder-checkpoint-path checkpoints/fish-speech-1.2-sft/firefly-gan-vq-fsq-4x1024-42hz-generator.pth \
    --compile`

**Expected behavior**
Without compile, it works no problem.

**Comment by ifounda-bug** [comment]
**Configuration:** 
Every configuration fails to complete. I also tried without the web-ui and instead using a script (and compiling), and I get a different error.

**Environment:**
- Linux localhost.localdomain 6.9.9-1-default # 1 SMP PREEMPT_DYNAMIC Thu Jul 11 11:31:54 UTC 2024 (8c0f797) x86_64 x86_64 x86_64 GNU/Linux
- LSB Version:	n/a
  Distributor ID:	openSUSE
  Description:	openSUSE Tumbleweed
  Release:	20240716
  Codename:	n/a
- Python 3.10.14
- NVIDIA-SMI 555.42.06              Driver Version: 550.90.07      CUDA Version: 12.4 


```
absl-py==2.1.0
aiofiles==23.2.1
aiohappyeyeballs==2.3.4
aiohttp==3.10.1
aiosignal==1.3.1
aliyun-python-sdk-core==2.15.1
aliyun-python-sdk-kms==2.16.3
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyio==4.4.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
async-timeout==4.0.3
attrs==24.1.0
audioread==3.0.1
av==12.3.0
Babel==2.15.0
baize==0.22.1
beautifulsoup4==4.12.3
bleach==6.1.0
certifi==2024.7.4
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
coloredlogs==15.0.1
comm==0.2.2
contourpy==1.2.1
crcmod==1.7
cryptography==43.0.0
ctranslate2==4.3.1
cycler==0.12.1
datasets==2.18.0
debugpy==1.8.3
decorator==5.1.1
defusedxml==0.7.1
dill==0.3.8
docker-pycreds==0.4.0
editdistance==0.8.1
einops==0.8.0
einx==0.2.2
exceptiongroup==1.2.2
executing==2.0.1
fastapi==0.112.0
faster-whisper==1.0.3
fastjsonschema==2.20.0
ffmpy==0.4.0
filelock==3.15.4
-e git+https://github.com/fishaudio/fish-speech@59fa05d6e8b1ff8ed65b7a9e71b411eecd3927ff#egg=fish_speech
flatbuffers==24.3.25
fonttools==4.53.1
fqdn==1.5.1
frozendict==2.4.4
frozenlist==1.4.1
fsspec==2024.2.0
funasr==1.1.2
gitdb==4.0.11
GitPython==3.1.43
gradio==4.40.0
gradio_client==1.2.0
grpcio==1.65.4
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
huggingface-hub==0.24.5
humanfriendly==10.0
hydra-core==1.3.2
idna==3.7
importlib_resources==6.4.0
ipykernel==6.29.5
ipython==8.26.0
isoduration==20.11.0
jaconv==0.4.0
jamo==0.4.1
jedi==0.19.1
jieba==0.42.1
Jinja2==3.1.4
jmespath==0.10.0
joblib==1.4.2
json5==0.9.25
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client==8.6.2
jupyter_core==5.7.2
jupyter_server==2.14.2
jupyter_server_terminals==0.5.3
jupyterlab==4.2.4
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.3
kaldiio==2.18.0
kiwisolver==1.4.5
kui==1.8.1
lazy_loader==0.4
librosa==0.10.2.post1
lightning==2.3.3
lightning-utilities==0.11.6
llvmlite==0.43.0
loguru==0.7.2
loralib==0.1.2
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.0
matplotlib-inline==0.1.7
mdurl==0.1.2
mistune==3.0.2
modelscope==1.16.1
mpmath==1.3.0
msgpack==1.0.8
multidict==6.0.5
multiprocess==0.70.16
natsort==8.4.0
nbclient==0.10.0
nbconvert==7.16.4
nbformat==5.10.4
nest-asyncio==1.6.0
networkx==3.3
notebook_shim==0.2.4
numba==0.60.0
numpy==1.26.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.6.20
nvidia-nvtx-cu12==12.1.105
omegaconf==2.3.0
onnxruntime==1.18.1
opencc-python-reimplemented==0.1.7
orjson==3.10.6
oss2==2.18.6
overrides==7.7.0
packaging==24.1
pandas==2.2.2
pandocfilters==1.5.1
parso==0.8.4
pexpect==4.9.0
pillow==10.4.0
platformdirs==4.2.2
pooch==1.8.2
prometheus_client==0.20.0
prompt_toolkit==3.0.47
protobuf==4.25.4
psutil==6.0.0
ptyprocess==0.7.0
pure_eval==0.2.3
pyarrow==17.0.0
pyarrow-hotfix==0.6
pycparser==2.22
pycryptodome==3.20.0
pydantic==2.8.2
pydantic_core==2.20.1
pydub==0.25.1
Pygments==2.18.0
pynndescent==0.5.13
pyparsing==3.1.2
pyrootutils==1.0.4
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-json-logger==2.0.7
python-multipart==0.0.9
pytorch-lightning==2.3.3
pytorch-wpe==0.0.1
pytz==2024.1
PyYAML==6.0.1
pyzmq==26.1.0
referencing==0.35.1
regex==2024.7.24
requests==2.32.3
resampy==0.4.3
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.7.1
rotary-embedding-torch==0.6.4
rpds-py==0.19.1
ruff==0.5.6
safetensors==0.4.4
scikit-learn==1.5.1
scipy==1.14.0
semantic-version==2.10.0
Send2Trash==1.8.3
sentencepiece==0.2.0
sentry-sdk==2.12.0
setproctitle==1.3.3
shellingham==1.5.4
six==1.16.0
smmap==5.0.1
sniffio==1.3.1
soundfile==0.12.1
soupsieve==2.5
soxr==0.4.0
stack-data==0.6.3
starlette==0.37.2
sympy==1.13.1
tensorboard==2.17.0
tensorboard-data-server==0.7.2
tensorboardX==2.6.2.2
terminado==0.18.1
threadpoolctl==3.5.0
tinycss2==1.3.0
tokenizers==0.19.1
tomli==2.0.1
tomlkit==0.12.0
torch==2.3.1
torch-complex==0.4.4
torchaudio==2.3.1
torchmetrics==1.4.1
torchvision==0.19.0+cu121
tornado==6.4.1
tqdm==4.66.5
traitlets==5.14.3
transformers==4.43.4
triton==2.3.1
typer==0.12.3
types-python-dateutil==2.9.0.20240316
typing_extensions==4.12.2
tzdata==2024.1
umap-learn==0.5.6
uri-template==1.3.0
urllib3==2.2.2
uvicorn==0.30.5
vector-quantize-pytorch==1.15.3
wandb==0.17.5
wcwidth==0.2.13
webcolors==24.6.0
webencodings==0.5.1
websocket-client==1.8.0
websockets==12.0
Werkzeug==3.0.3
xxhash==3.4.1
yarl==1.9.4
zstandard==0.23.0
```

**Comment by AnyaCoder** [comment]
What messages are above progress bar?
`  0%|                                                  | 0/2047 [01:14<?, ?it/s]`
We need all info.

**Comment by ifounda-bug** [comment]
After digging into it for a while, I believe the issue was that I set up in a path which had a space in it. This caused torch to not be able to find ptxas which I believe is shipped with torchtriton. After clearing the space from the path and setting up the virtual environment again, I was able to resolve the issue.

Thanks!
