### ISSUE TITLE
[Feature] How to accelerate inference

### ISSUE THREAD

**Issue by xyyimian** [fishaudio/fish-speech#46]
![image](https://github.com/fishaudio/fish-speech/assets/30361039/f6f27c21-17af-44d6-9104-73645e7b89b4)
**Is your feature request related to a problem? Please describe.**

Is the inference time normal? Not considering the model loading time, is it normal to take more than 30s to generate a speech with 60 english words. How could I accelerate it if I want to make the inference time in ~2s? Thanks!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by leng-yue** [comment]
Can you try inference with the webui? Otherwise it compiles the model every time you run the program.

**Comment by xyyimian** [comment]
webui works. it only took 2s to generate 30s speech

**Comment by lucasjinreal** [comment]
@xyyimian Can u help test on CPU as well?
