### ISSUE TITLE
[BUG] --compile 加载之后推理更慢了，tokens 个位数

### ISSUE THREAD

**Issue by josangmi** [fishaudio/fish-speech#460]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**
使用了HTTP API 推理的方式，先启动了服务端
python -m tools.api \
    --listen 0.0.0.0:8000 \
    --llama-checkpoint-path "checkpoints/fish-speech-1.2-sft" \
    --decoder-checkpoint-path "checkpoints/fish-speech-1.2-sft/firefly-gan-vq-fsq-4x1024-42hz-generator.pth" \
    --decoder-config-name firefly_gan_vq
    --compile

**To Reproduce**

**Expected behavior**

**Screenshots / log**
If applicable, add screenshots / logs to help explain your problem.
<img width="551" alt="image" src="https://github.com/user-attachments/assets/c4af8412-9430-4f48-8f11-43cf771e460c">
<img width="567" alt="image" src="https://github.com/user-attachments/assets/7d0ce2d3-61a8-48de-94af-247bd46bbf52">
<img width="727" alt="image" src="https://github.com/user-attachments/assets/2bf087df-9dbe-44ed-8799-494f8416b61a">
<img width="896" alt="image" src="https://github.com/user-attachments/assets/3c1f2c17-3636-4028-9194-c01fbc51d3e3">

**Additional context**

**Comment by AnyaCoder** [comment]
从第二次推理开始再比较是否compile的速度。

**Comment by josangmi** [comment]
没有使用编译第二次
<img width="1110" alt="image" src="https://github.com/user-attachments/assets/b8a251dd-585e-477f-8099-870bfd059794">
编译时间
<img width="559" alt="image" src="https://github.com/user-attachments/assets/22a2656a-764e-4fa2-9394-1c8e12a1bc6c">
此时我的显存接近98%，
使用编译第一次
<img width="998" alt="image" src="https://github.com/user-attachments/assets/f7d0a617-a8d4-4dc9-8061-a02b9a5c9543">
第二、三次，产生了幻觉，跑满了1023tokens，但是提升到50+tokens，这个不知道怎么才能避免现在
参数：  "max_new_tokens": 1024,
  "chunk_length": 200,
  "top_p": 0.7,
  "repetition_penalty": 1.2,
  "temperature": 0.1,
<img width="1108" alt="image" src="https://github.com/user-attachments/assets/cf0fb6ef-848e-463e-b231-34502c5e7f81">
第四次，tokens下降，
<img width="869" alt="image" src="https://github.com/user-attachments/assets/aedeb305-aa14-48fd-a368-c0211f2711ab">
后续几次都和第四次一致，趋于稳定，
其他参数：  
  "speaker": "SPEAKER3",
  "emotion": "EMOTION1",
  "format": "mp3",
  "streaming": false
期间一直有几个FutureWarning 暂时没法修改。 
vector_quantize_pytorch/residual_fsq.py:170: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
vector_quantize_pytorch/finite_scalar_quantization.py:192: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
contextlib.py:105: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.

**Comment by AnyaCoder** [comment]
temperature 我记得默认是0.7吧。
你用的是30系及以上的卡吗？不是的话编译提升不会太多。

**Comment by josangmi** [comment]
temperature 0.1 是因为感觉幻觉大修改的。 
计划用两张4090，但是暂时没法移到第二张卡。

**Comment by Stardust-minus** [comment]
请勿使用torch 2.4.0,降级到2.3.1

**Comment by loredunk** [comment]
> 请勿使用torch 2.4.0,降级到2.3.1

都降级到2.3.1 也会出现 FutureWarning: torch.backends.cuda.sdp_kernel() is deprecated. In the future, this context manager will be removed. Please see torch.nn.attention.sdpa_kernel() for the new context manager, with updated signature.
这样的问题

**Comment by JessonChan** [comment]
> 请勿使用torch 2.4.0,降级到2.3.1
hye  guys, why do we need to downgrade to version 2.3.1? are there any deeper reasons or reference documents available? thanks.

**Comment by AnyaCoder** [comment]
now 2.4.0 is ok

**Comment by JessonChan** [comment]
Thanks a lot for your reply! I actually tested torch  versions 2.4 and 2.5 too, and they both work. The only downside is that the model's inference speed isn't super fast—only around 110 tokens per second on the 4090D,even with the compile parameter.

**Comment by AnyaCoder** [comment]
In my case test torch version 2.4 is twice as fast as version 2.5. There is something wrong with the fact that you are measuring about the same speed with your 4090D card as with my 4060 card, maybe you don't have enough CPU performance.

**Comment by JessonChan** [comment]
Nice reference! i will retest it, as perhaps I didn't follow a more rigorous process. ps, my CPU performance should be enough, I'm using a i9-14th.

**Comment by JessonChan** [comment]
Great, when I downgraded the version of torch from 2.5 to 2.4.1, I indeed saw a 2x improvement, thank you!
