### ISSUE TITLE
[BUG] 速度很慢，加了compile后15tokens/s，一句话要十多秒

### ISSUE THREAD

**Issue by Songjc0511** [fishaudio/fish-speech#465]
![1723454759019](https://github.com/user-attachments/assets/8596b569-1676-42d5-91fa-1826b6e5eed2)

GPU: 3080
CUDA: 12.1
TORCH: 2.4
这个速度太慢了，按照的是文档里的流程启动了webui，请问我哪一步有错么？

**Comment by Stardust-minus** [comment]
Use torch==2.3.1

**Comment by whengu** [comment]
这个项目就是以慢为特点的, 我使用公司的80G显存的服务器也很慢, 更不要说你们本地运行的了

![Image](https://github.com/user-attachments/assets/2c9e20c0-5159-4ba3-9436-23bdb1aaa777)
