### ISSUE TITLE
关于开源权重问题

### ISSUE THREAD

**Issue by Jalen-Zhong** [fishaudio/fish-speech#469]
想问一下开源权重模型效果和网站上提供的闭源模型差距有多大？我使用docker环境，同样的引用音频和测试文本，生成的效果差距很大。

**Comment by PoTaTo-Mika** [comment]
差一个小版本。

**Comment by Jalen-Zhong** [comment]
方便透露模型的具体参数量嘛 : )

**Comment by PoTaTo-Mika** [comment]
参数量与开源的一致。

**Comment by AnyaCoder** [comment]
> 方便透露模型的具体参数量嘛 : )

1.1 llama 有 500M, 1B 两个版本
1.2 llama 为 500M
