### ISSUE TITLE
What are the improvements of fish-speech compared to TorToise-TTS or CosyVoice

### ISSUE THREAD

**Issue by JohnHerry** [fishaudio/fish-speech#470]
I did not find the paper about this project, but since it is AR LLM based tts, I want to know the idea in the fish-speech that superior to privious works like TorToise and Cosyvoice. Is there and instructions?  
And as we have tried, the single VQGAN as decoder to transform speech tokens into waveform is not good enough, the Diffusion based module like that used in TorToise got better result. what are the tricks in VQGAN here of fish-speech so that there need no such diffusion module any more?  
Thanks.

**Comment by wehos** [comment]
Did you compare the performance of fishaudio with CosyVoice or do you have a plan? I'd be interested to see which one is better.

**Comment by wehos** [comment]
By the way, the latest published [LSLM](https://arxiv.org/pdf/2408.02622) paper also used a [GAN-based vocoder (UniCATS)](https://ojs.aaai.org/index.php/AAAI/article/view/29747/31286). I'm wondering did you see any recent rigid benchmarks that show the diffusion models indeed outperform non-diffusion ones?

**Comment by JohnHerry** [comment]
> Did you compare the performance of fish-speech with CosyVoice or do you have a plan? I'd be interested to see which one is better.

No, we had tried TorToise-TTS before.  the model use simple vqvae-GAN,  not GroupedResidualVQ-GAN here in fish. the direct decode results of vqgan are far from acceptable, so we use diffusion then.  since in TorToise-TTS, we use only one codebook, and codebook indices are used in LLM training.  Here I see the fish-speech, it use GroupedResidualVQ-GAN with 4 groups and one codebook with 512 dim inner-hiddens [from configs/firefly_gan_vq.yaml],  then how is the vq-gan used to train the LLM? directly use the inner-hiddens OR use indices just like TorToise-TTS?
