### ISSUE TITLE
后半段丟字严重， llm 过早预测了结束符

### ISSUE THREAD

**Issue by kunyao2015** [fishaudio/fish-speech#473]
极大概率 出现 后半截文本丢失现象，如何减小或避免这种现象出现的概率呢？

**Comment by AnyaCoder** [comment]
用好一些的数据，不用lora训一下llama

**Comment by kunyao2015** [comment]
意思是prompt 选的好，就会好很多吗，这个“好数据“有啥标准不

**Comment by kunyao2015** [comment]
我用的是1.2-sft模型，未训练；意思是prompt wav选的好，就会好很多吗，这个“好数据“有啥标准不

**Comment by kunyao2015** [comment]
我用的是1.2-sft模型，未训练；意思是prompt wav选的好，就会好很多吗，这个“好数据“有啥标准不
