### ISSUE TITLE
[help wanted] faster whisper model的作用

### ISSUE THREAD

**Issue by Jalen-Zhong** [fishaudio/fish-speech#474]
请教问题如上

**Comment by AnyaCoder** [comment]
一种低级的蛮力的降低错字率的手段。
如果推理出来的音频出现比较多的错误，会再推n次，直到错字率达标或推理次数耗尽。

**Comment by Jalen-Zhong** [comment]
> 一种低级的蛮力的降低错字率的手段。 如果推理出来的音频出现比较多的错误，会再推n次，直到错字率达标或推理次数耗尽。

请问大佬你说的降低错字率的手段具体表现在`whisper_asr.py`这个脚本里嘛？我在`webui.py`里看到`faster whisper model`的应用好像就只有自动生成标签这一个功能。麻烦具体指出一下，感谢！

**Comment by Jalen-Zhong** [comment]
看到了：https://github.com/fishaudio/fish-speech/blob/cc7afe8d7bf6e390e757e02ffcdb2c60c7b857cb/tools/webui.py#L163

**Comment by Jalen-Zhong** [comment]
刚刚看了一下源码，看来`faster whisper model`的目的是将`fish-speech`的音频转化成文字，转化的文字再与参考文本比较，如果满足一定阈值则推，不满足则重新生成一遍，直到n次。如果n次都不满足则推出最好的音频版本。
不知道理解对不对，请指正。
另外，我看到`流式输出`似乎没有用到`whisper`来进行音频版本管理，请问是有什么不妥的地方嘛？

**Comment by AnyaCoder** [comment]
你的理解是对的。
流式的目的是尽可能地及时听到人声，并且`不被打断`。而`whisper`重新推理会打断这个过程。

**Comment by Jalen-Zhong** [comment]
感谢解答！
