### ISSUE TITLE
[Feature] 目前的项目，支持中英文混合输出吗？

### ISSUE THREAD

**Issue by dogvane** [fishaudio/fish-speech#48]
很多bert和vits在多语言混合输出上都有些问题，这个版本会有改进么。

**Comment by leng-yue** [comment]
预计会在下个版本有改进.

**Comment by luohao123** [comment]
@leng-yue Hello, any estimate on next version release? vqgan2 maybe? Also the Chinese frontend might need update to handle more complicated Multi-syllable words. such as:

孩子别吃了，这里的肉脏，走，跟我去太平间

and some puncuation not properly resolved such as `: ; ` etc.

**Comment by shirubei** [comment]
不错，中英文混合用以下测试OK
我正在测试windows下的语音tts功能。
