### ISSUE TITLE
[BUG] Website reCaptcha error without reCaptcha

### ISSUE THREAD

**Issue by MInecrafterPictures** [fishaudio/fish-speech#481]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**
SHow me a reCaptcha error, but it never showed me reCaptcha

**To Reproduce**
Generate the voice multiple times frequently at fish.audio

**Expected behavior**
Allowing me to generate or at least giving me reCaptcha.

**Comment by PoTaTo-Mika** [comment]
Please change your ip and try again.

**Comment by MInecrafterPictures** [comment]
I am not using a vpn. Changing it is not an option.

**Comment by Stardust-minus** [comment]
We now removed reCaptcha  for premium user.

**Comment by MInecrafterPictures** [comment]
Can the reCaptcha at least be fixed so it actually works?
