### ISSUE TITLE
[BUG] Model output keeps repeating itself, after certain input/max token combination was executed.

### ISSUE THREAD

**Issue by andantei** [fishaudio/fish-speech#49]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**
When certain audio and max tokens settings were used to generate the first audio, all subsequent generations will keep using the inputs of the first generation no matter what is given to the model.

**To Reproduce**
See video below:
https://www.awesomescreenshot.com/video/23829885?key=2c741f2c20efe2939f38085c73b3d740

**Expected behavior**
Subsequent generations should generate what is given as the input, not what is given in the first generation.

**Screenshots / log**
If applicable, add screenshots / logs to help explain your problem.
https://www.awesomescreenshot.com/video/23829885?key=2c741f2c20efe2939f38085c73b3d740

**Additional context**
Created a PR to fix it. Possibly related setup_caches, reason unknown, maybe the repo owner can help investigate.

**Comment by leng-yue** [comment]
This seems to be a webui issue, can you test calling the http api directly to see if that happens?

**Comment by andantei** [comment]
Same thing with HTTP API.

**Comment by leng-yue** [comment]
Do you mind to share your ref files? I will test it later.

**Comment by andantei** [comment]
Sure, GitHub doesn't seem to allow audio files to be uploaded, I've converted it into an mp4.

https://github.com/fishaudio/fish-speech/assets/97192387/80ebfad4-7014-4233-8749-4fc808dd7aa4

**Comment by andantei** [comment]
Prompt text: "今天去哪里玩好呢，咱们一起去海边吧，感受一下人工智能的清新，和阳光的温暖怎么样。"
Max tokens: 2000

**Comment by leng-yue** [comment]
Are you using npy path for http api?

**Comment by andantei** [comment]
i only tried .wav path

**Comment by sos1sos2Sixteen** [comment]
this seemed to be an issue with reallocating the kv cache.

**Comment by seele-vollerei-ai** [comment]
Have encountered the same problem, is there a solution?

**Comment by seele-vollerei-ai** [comment]
After changing max_new_tokens from 1024 to 4096 this issue did not occur again ~
