### ISSUE TITLE
[BUG] 按照linux方法安装报错

### ISSUE THREAD

**Issue by shinoairisu** [fishaudio/fish-speech#490]
The conflict is caused by:
    transformers 4.35.2 depends on tokenizers<0.19 and >=0.14
    faster-whisper 0.8.0 depends on tokenizers==0.13.*
    transformers 4.35.2 depends on tokenizers<0.19 and >=0.14
    faster-whisper 0.7.1 depends on tokenizers==0.13.*
    transformers 4.35.2 depends on tokenizers<0.19 and >=0.14
    faster-whisper 0.7.0 depends on tokenizers==0.13.*
    transformers 4.35.2 depends on tokenizers<0.19 and >=0.14
    faster-whisper 0.6.0 depends on tokenizers==0.13.*
    transformers 4.35.2 depends on tokenizers<0.19 and >=0.14
    faster-whisper 0.5.1 depends on tokenizers==0.13.*
    transformers 4.35.2 depends on tokenizers<0.19 and >=0.14
    faster-whisper 0.5.0 depends on tokenizers==0.13.*
    transformers 4.35.2 depends on tokenizers<0.19 and >=0.14
    faster-whisper 0.4.1 depends on tokenizers==0.13.*
    transformers 4.35.2 depends on tokenizers<0.19 and >=0.14
    faster-whisper 0.4.0 depends on tokenizers==0.13.*
    transformers 4.35.2 depends on tokenizers<0.19 and >=0.14
    faster-whisper 0.3.0 depends on tokenizers==0.13.*
    transformers 4.35.2 depends on tokenizers<0.19 and >=0.14
    faster-whisper 0.2.0 depends on tokenizers==0.13.*

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

**Comment by ShredderMing** [comment]
按照 #486 #487 这两个还没有合并的pull request改一下就行了

**Comment by wukongbuku** [comment]
哈喽，你的问题，解决了吗

**Comment by shinoairisu** [comment]
没有。后来就没时间了。暂时还没有处理。

**Comment by wukongbuku** [comment]
> 没有。后来就没时间了。暂时还没有处理。

好吧，楼上的人给的建议，不大好用，我今天刚拉取的代码，不行，还在找解决办法

**Comment by wukongbuku** [comment]
> 按照 #486 #487 这两个还没有合并的pull request改一下就行了

哈喽，你的代码已经pr进去了，我今天刚刚拉的main代码，但是没有效果，还是报错了

**Comment by wukongbuku** [comment]
排查了一遍，我这边默认的清华源，这些镜像不行，好多新包都没有，得用默认源进行安装

**Comment by ShredderMing** [comment]
我刚刚试了一下是可以安装成功的，环境是Archlinux, miniconda3。
楼主的报错应该不是我说的解决方法，之前只看到linux安装报错就直接回答了。
现在看看报错，transformers 4.35.2没问题，因为项目里pyproject.toml里指明了>=4.35.2。
问题是faster-whisper未指定，而报错中没找到满足依赖关系的版本。
我这边自动装了1.0.3的版本是可以的，如果没有，可能是源的问题。

**Comment by shinoairisu** [comment]
我也是7.9…老系统不好整啊

**Comment by Stardust-minus** [comment]
建议使用Ubuntu或者Debian部署

**Comment by wansho** [comment]
> 排查了一遍，我这边默认的清华源，这些镜像不行，好多新包都没有，得用默认源进行安装

是的，不能用第三方的镜像源，里面很多包都不是最新的
