### ISSUE TITLE
After AutoDL is deployed, the 4090 graphics card uses GPU to infer the length of 1,000 Chinese characters, which takes 37 seconds. Is the audio length of 3 minutes and 10 seconds normal?

### ISSUE THREAD

**Issue by wosuiyu** [fishaudio/fish-speech#493]
AutoDL部署完成之后，4090显卡使用GPU推理1000汉字字符长度，时长需要消耗的时间37秒，音频时长3分10秒正常吗？
并且在推理结果中会出现，丢失整行文字的情况，一定概率。是什么问题导致呢？另外日志中看到GPU只用到1.6GB左右，这个准确吗？
![111](https://github.com/user-attachments/assets/e6b929cc-1c7f-4c1e-9771-adca85913a45)
![222](https://github.com/user-attachments/assets/70fa218e-19d0-480b-8489-3ef4ce60dca1)

**Comment by PoTaTo-Mika** [comment]
吞字系模型幻觉，多抽卡可以缓解

**Comment by Stardust-minus** [comment]
#515 Change title to English.
