### ISSUE TITLE
[Feature]在线API是否可以考虑提交创建模型？

### ISSUE THREAD

**Issue by 08090813** [fishaudio/fish-speech#494]
1、我目前正在基于API接口开发应用。
API文档上只有一个语音合成的接口，但是在使用API构建自己的应用时，大部分场景都需要创建自己的声音。

**Comment by leng-yue** [comment]
目前接口有的, 正在整理文档.

**Comment by 08090813** [comment]
> 目前接口有的, 正在整理文档.

非常感谢，期待更新文档

**Comment by leng-yue** [comment]
更新了: https://docs.fish.audio/api-reference/endpoint/model/create-model.  
目前需要用 multipart 提交 voices 需要是 bytes.  
可以参考 https://fish.audio/train/new-model/ 的请求.

**Comment by Stardust-minus** [comment]
#515 Change title to English.
