### ISSUE TITLE
[Feature]改善api 接口，  不需要提供reference audio and text

### ISSUE THREAD

**Issue by fastfading** [fishaudio/fish-speech#495]
https://notion.fish.audio/APIs-2afdd0529d72479e96834df114c16274
api 这里需要设置 ReferenceAudio
  references=[
        ServeReferenceAudio(
            audio=open("lengyue.wav", "rb").read(),
            text="Text in reference AUDIO",
        )
    ],
    
 作为api ，用户哪里去找和原模型一致的 音频。
使用很不方便。

能不能改成像demo 一样，
用户只要设置text 和 reference id

**Comment by xeoshow** [comment]
其实可以两种形态都支持最好。
另外，这个API接口方式，国内不翻墙也可以正常调用吗？
https://fish.audio/zh-CN/go-api/

**Comment by fastfading** [comment]
request = ServeTTSRequest(
    text="Hello, world!",
    # references=[
    #     ServeReferenceAudio(
    #         audio=open("lengyue.wav", "rb").read(),
    #         text="Text in reference AUDIO",
    #     )
    # ],
    reference_id="7f92f8afb8ec43bf81429cc1c9199cb1",
)

改写后一直报错
{"status":401,"message":"Invalid API key"}

**Comment by Stardust-minus** [comment]
> request = ServeTTSRequest( text="Hello, world!", # references=[ # ServeReferenceAudio( # audio=open("lengyue.wav", "rb").read(), # text="Text in reference AUDIO", # ) # ], reference_id="7f92f8afb8ec43bf81429cc1c9199cb1", )
> 
> 改写后一直报错 {"status":401,"message":"Invalid API key"}

是不是没有填写API Key

**Comment by fastfading** [comment]
> > request = ServeTTSRequest( text="Hello, world!", # references=[ # ServeReferenceAudio( # audio=open("lengyue.wav", "rb").read(), # text="Text in reference AUDIO", # ) # ], reference_id="7f92f8afb8ec43bf81429cc1c9199cb1", )
> > 改写后一直报错 {"status":401,"message":"Invalid API key"}
> 
> 是不是没有填写API Key

这里好容易误解， 填的token ， 要填的居然是 id

**Comment by leng-yue** [comment]
之前没及时更新文档, 在改了.jpg

**Comment by Stardust-minus** [comment]
#515 Change title to English.

**Comment by SpencerZhaoQi** [comment]
> request = ServeTTSRequest( text="Hello, world!", # references=[ # ServeReferenceAudio( # audio=open("lengyue.wav", "rb").read(), # text="Text in reference AUDIO", # ) # ], reference_id="7f92f8afb8ec43bf81429cc1c9199cb1", )
> 
> 改写后一直报错 {"status":401,"message":"Invalid API key"}

reference_id="7f92f8afb8ec43bf81429cc1c9199cb1",  使用reference_id，没有效果，我声音模型是在线生成的，然后fish-speech是本地部署的，不知道和这个有没有关系
