### ISSUE TITLE
toos/api.py开启half推理时报错

### ISSUE THREAD

**Issue by litao-zhx** [fishaudio/fish-speech#496]
当使用默认参数推理时，发现生成速度过慢，所以想把half开启看看效果，结果运行报错，设置如下：
![image](https://github.com/user-attachments/assets/284c94a9-3eba-4a23-a7ba-48b9b915bdfe)
报错内容如下：
![image](https://github.com/user-attachments/assets/5663fa6e-d682-4f9d-a738-848c159a67d5)
启动命令为：CUDA_VISIBLE_DEVICES=2 python -m tools.api

**Comment by Stardust-minus** [comment]
什么GPU

**Comment by litao-zhx** [comment]
3090

**Comment by litao-zhx** [comment]
CUDA环境如下：
![image](https://github.com/user-attachments/assets/075bfc4f-f747-4b67-b668-83c829e69b90)

**Comment by Stardust-minus** [comment]
尝试降级torch版本到2.3.1

**Comment by litao-zhx** [comment]
![image](https://github.com/user-attachments/assets/67286a13-61a9-4b13-8849-422090a34566)

**Comment by litao-zhx** [comment]
torch 就时2.3.1的，难道是因为cuda的问题吗？

**Comment by litao-zhx** [comment]
不好意思，是我这边的问题，但是速度好像还时不快啊？就转录“今天天气真好啊,我真想出去玩”这几个字就需要8s

**Comment by Stardust-minus** [comment]
#515 Change title to English.
