### ISSUE TITLE
[BUG]安装 fish-speech安装不上，是否和pip的版本有关系？

### ISSUE THREAD

**Issue by wukongbuku** [fishaudio/fish-speech#502]
pip3 install -e .[stable]
以上安装的时候，会有依赖冲突，导致无法正常安装（不同的pip版本有不同的依赖冲突。。。。）

Using cached https://pypi.tuna.tsinghua.edu.cn/packages/12/dd/f17b11a93a9ca27728e12512d167eb1281c151c4c6881d3ab59eb58f4127/transformers-4.35.2-py3-none-any.whl (7.9 MB)

ERROR: Cannot install fish-speech because these package versions have conflicting dependencies.
The conflict is caused by:
transformers 4.35.2 depends on tokenizers<0.19 and >=0.14
faster-whisper 0.7.1 depends on tokenizers==0.13.*

目前已经试了pip的三个版本了
pip==24.2
pip==23.0
pip==22.0

**Comment by PoTaTo-Mika** [comment]
建议新建虚拟环境后pip install -e .
之后再根据缺少的函数库逐个安装。

**Comment by wukongbuku** [comment]
更新，看看是否默认清华源之类的了，好多都是新版本的包
得用默认源才行

**Comment by wukongbuku** [comment]
在更，centos好像不支持，onnxruntime==1.18.1，最多1.16.3

**Comment by Stardust-minus** [comment]
#515 Change title to English.

**Comment by zsLin177** [comment]
> > 建议新建虚拟环境后pip install -e . 之后再根据缺少的函数库逐个安装。
> 
> 不行，主要是 from tools.tile import AUDlO EXIENSIONS ModuleNotFoundError: No module named 'tools' 用命令行，推理的时候，报这个错误，然后 tools.tile是代码里的一个文件 加载不到，然后才反推到上边的。。。。

你好，请问你解决了吗？我也遇到了一样的问题
