### ISSUE TITLE
[BUG]有没有用  centos 的大佬，环境安装成功的，各种依赖报错

### ISSUE THREAD

**Issue by wukongbuku** [fishaudio/fish-speech#503]
![image](https://github.com/user-attachments/assets/c5c89959-50ba-4c25-baf2-d8f625c40fd5)

如图

死活装不成功，各种依赖报错

**Comment by Stardust-minus** [comment]
建议使用Ubuntu或者Debian部署

**Comment by wukongbuku** [comment]
> 建议使用Ubuntu或者Debian部署

确实这样子，centos 7 系统不更新了，以后尽量不用

**Comment by Stardust-minus** [comment]
#515 Change title to English.
