### ISSUE TITLE
[BUG]Unable to continue last training session

### ISSUE THREAD

**Issue by tao1261060556** [fishaudio/fish-speech#504]
使用1.2版本，同一个训练集，用webui训练一段时间后，停止训练.重启电脑后，重新打开WebUI,选择好 LLAMA 检查点后，再点训练，就出错了。
不知别人有没有遇到相同的情况。1.1.2版本则不会出错，可以继续接下去训练。

**Comment by AnyaCoder** [comment]
1.2默认使用lora，未支持继续训练

**Comment by tao1261060556** [comment]
> 1.2默认使用lora，未支持继续训练

原来如此，我试着把lora的勾去掉，但去不掉。没办法不用lora

**Comment by AnyaCoder** [comment]
更新一下代码就可以取消勾选了

**Comment by tao1261060556** [comment]
> 更新一下代码就可以取消勾选了

更新后可以不勾选了，但练训出来的模型，用webui没有加载到，无法推理

**Comment by AnyaCoder** [comment]
参见 tools\extract_model.py 提取出 state_dict ，
```bash
python tools\extract_model.py results\..\step_0000{xxx}.ckpt model.pth 
```
然后再复制一份 checkpoints/fish-speech-1.2-sft ， 粘贴该文件夹并重命名为 checkpoints/fs-1.2-new (随意取名) , 将提取出的`model.pth`覆盖进去。最后在webui里选中即可。

**Comment by Stardust-minus** [comment]
#515 Change title to English.
