### ISSUE TITLE
[BUG] How to reproduce demo for English TTS

### ISSUE THREAD

**Issue by xyyimian** [fishaudio/fish-speech#51]
I am trying to use webui. I load the checkpoint and use the reference wav provided in demo [page](https://speech.fish.audio/samples/). But I can not reproduce. 

**Describe the bug**
I am trying to reproduce this demo
![image](https://github.com/fishaudio/fish-speech/assets/30361039/4b9a0078-c6e1-4ae3-842a-d277bc2547a6)

model settings
![image](https://github.com/fishaudio/fish-speech/assets/30361039/6a8a3171-69ab-48c7-be17-eee05adf8887)

I used same reference wav.
![image](https://github.com/fishaudio/fish-speech/assets/30361039/fc6cc23f-7efa-48f4-8408-b08e1fcfd43a)

But the results are pretty bad 
[audio.zip](https://github.com/fishaudio/fish-speech/files/13856417/audio.zip)

How could I reproduce the demo performance? Thanks!

**Comment by leng-yue** [comment]
There are not enough English training data in v0.3, this should be fixed in v1.0. As the demo page mentioned, you need to enable the g2p (aka `自动音素`) for English and Japanese synthesize.

**Comment by xyyimian** [comment]
> There are not enough English training data in v0.3, this should be fixed in v1.0. As the demo page mentioned, you need to enable the g2p (aka `自动音素`) for English and Japanese synthesize.

Thanks for your reply. Do you have plan to release v1.0 checkpoint in the future?

**Comment by leng-yue** [comment]
Of course. It should be released in the next 4 weeks.

**Comment by Qubitium** [comment]
@leng-yue  Any update on the progress of v1.0 model checkpoint?

**Comment by leng-yue** [comment]
We are optimizing the VQGAN for better audio quality, most issues are solved now.
