### ISSUE TITLE
Why fish-speech implementation of transformer feedforward contains there linears?

### ISSUE THREAD

**Issue by JohnHerry** [fishaudio/fish-speech#512]
As I read in the fish-speech llama transformers, there are three linears in FeedForward.  as I know most of the transformer implementations there are only two linears works as scale out and scale back. Why there are three linears in this implementation? is there any benifit worth that computation cost?

**Comment by leng-yue** [comment]
This is basically gated linear unit, it's same as what was used in original LLAMA.

**Comment by JohnHerry** [comment]
Thanks you. get it
