### ISSUE TITLE
Mac support?

### ISSUE THREAD

**Issue by Pareak** [fishaudio/fish-speech#532]
### Self Checks

- [X] I have searched for existing issues [search for existing issues]([https://github.com/langgenius/dify/issues](https://github.com/fishaudio/fish-speech/issues)), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Will it run on Mac any time soon?
 In the documentation it only described how to use it for Windows and Linux.

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Stardust-minus** [comment]
No offical support plan.

**Comment by fast01** [comment]
> ### Self Checks
> * [x]  I have searched for existing issues search for existing issues, including closed ones.
> * [x]  I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
> * [x]  [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
> * [x]  Please do not modify this template :) and fill in all the required fields.
> 
> ### 1. Is this request related to a challenge you're experiencing? Tell me about your story.
> Will it run on Mac any time soon? In the documentation it only described how to use it for Windows and Linux.
> 
> ### 2. Additional context or comments
> _No response_
> 
> ### 3. Can you help us with this feature?
> * [ ]  I am interested in contributing to this feature.

there is a try that can run on win and  mac.  Try this :  https://blog.csdn.net/weixin_43935971/article/details/144435437
