### ISSUE TITLE
ModuleNotFoundError: No module named 'ormsgpack'

### ISSUE THREAD

**Issue by one-pip** [fishaudio/fish-speech#535]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have searched for existing issues [search for existing issues](https://github.com/fishaudio/fish-speech/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

To create a public link, set `share=True` in `launch()`.
2024-09-12 21:49:19.002 | INFO     | __main__:clean_infer_cache:144 - Deleted cached audios: C:\Users\ADMINI~1\AppData\Local\Temp\gradio
Traceback (most recent call last):
  File "C:\AI\fish-speech\tools\webui.py", line 25, in <module>
    from tools.api import decode_vq_tokens, encode_reference
  File "C:\AI\fish-speech\tools\api.py", line 15, in <module>
    import ormsgpack
ModuleNotFoundError: No module named 'ormsgpack'

### ✔️ Expected Behavior

I updated it today, what is this problem?
ModuleNotFoundError: No module named 'ormsgpack'

### ❌ Actual Behavior

To create a public link, set `share=True` in `launch()`.
2024-09-12 21:49:19.002 | INFO     | __main__:clean_infer_cache:144 - Deleted cached audios: C:\Users\ADMINI~1\AppData\Local\Temp\gradio
Traceback (most recent call last):
  File "C:\AI\fish-speech\tools\webui.py", line 25, in <module>
    from tools.api import decode_vq_tokens, encode_reference
  File "C:\AI\fish-speech\tools\api.py", line 15, in <module>
    import ormsgpack
ModuleNotFoundError: No module named 'ormsgpack'

**Comment by leng-yue** [comment]
It's included in `pyproject.toml`, do you mind to share how you install the project?

**Comment by one-pip** [comment]
> It's included in `pyproject.toml`, do you mind to share how you install the project?

i just used "git pull" to update

**Comment by one-pip** [comment]
> Run pip install ormsgpack

i have tried this way, but it is no use to solve problem

**Comment by leng-yue** [comment]
Please make sure you installed it in a correct env.
