### ISSUE TITLE
The expanded size of the tensor (472) must match the existing size (1023) at non-singleton dimension 1.

### ISSUE THREAD

**Issue by lafreak** [fishaudio/fish-speech#537]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have searched for existing issues [search for existing issues](https://github.com/fishaudio/fish-speech/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Infer via WebUI with mid-size prompt (5-6 sentences)

Configs default:
Iterative Prompt Length = 200
Maximum tokens per batch = 1024
Top-P 0.7
Repetition Penalty 1.2
Temperature 0.7

Model: default one, from: https://speech.fish.audio/

### ✔️ Expected Behavior

Audio being generated

### ❌ Actual Behavior

 The expanded size of the tensor (895) must match the existing size (1023) at non-singleton dimension 1. Target sizes: [9, 895]. Tensor sizes: [9, 1023]

**Comment by arushijain** [comment]
I'm having the same issue. 

```RuntimeError: The expanded size of the tensor (1024) must match the existing size (4735) at non-singleton dimension 1.  Target sizes: [9, 1024].  Tensor sizes: [9, 4735]```

**Comment by Aalisha** [comment]
Also, getting a similar error after finetuning the Fish-speech 1.4 model and then tried to run the inference - `RuntimeError: The expanded size of the tensor (4096) must match the existing size (4133) at non-singleton dimension 1.  Target sizes: [9, 4096].  Tensor sizes: [9, 4133]`

**Comment by newrichard** [comment]
This patch can fix the bug. 
```
--- a/tools/llama/generate.py
+++ b/tools/llama/generate.py
@@ -263,13 +263,15 @@ def generate(
         model,
         next_token.view(1, codebook_dim, -1),
         input_pos,
-        max_new_tokens - 1,
+        max_new_tokens - T - 1,
         im_end_id=im_end_id,
         decode_one_token=decode_one_token,
         **sampling_kwargs,
     )
     # x = torch.cat(generated_tokens, dim=1)
```
But I got two new problems. 
1. Increasing max_new_tokens to 2048 cause cuda error: device-side assert triggered.
```
unknown:0: unknown: block: [0,0,0], thread: [32,0,0] Assertion `index out of bounds: 0 <= tmp5 < 2048` failed.
unknown:0: unknown: block: [0,0,0], thread: [33,0,0] Assertion `index out of bounds: 0 <= tmp5 < 2048` failed.
unknown:0: unknown: block: [0,0,0], thread: [34,0,0] Assertion `index out of bounds: 0 <= tmp5 < 2048` failed.
unknown:0: unknown: block: [0,0,0], thread: [35,0,0] Assertion `index out of bounds: 0 <= tmp5 < 2048` failed.
```
2. After apply the patch above,  it will trigger a new bug occasionally that prompt size T is larger than max_new_tokens.

**Comment by AnyaCoder** [comment]
Hi, everyone. We can fix this issue by modifying the file `tools\generate.py`.

```python
    - empty = torch.empty((codebook_dim, max_new_tokens), dtype=dtype, device=device)
    + empty = torch.empty((codebook_dim, model.config.max_seq_len), dtype=dtype, device=device)
```
It works fine with 30s prompts.

**Comment by Stardust-minus** [comment]
See #540

**Comment by arushijain** [comment]
I pulled the latest changes but I still see the following 

```RuntimeError: The expanded size of the tensor (4096) must match the existing size (4735) at non-singleton dimension 1.  Target sizes: [9, 4096].  Tensor sizes: [9, 4735]```

I'm pretty cookie cutter following the inference example -- https://github.com/fishaudio/fish-speech/blob/main/inference.ipynb

Are there any specifications on what the audio file should be? Certain length, # of channels?

**Comment by bkosowski** [comment]
The problem is back:

```
The expanded size of the tensor (8192) must match the existing size (8446) at non-singleton dimension 1. Target sizes: [9, 8192]. Tensor sizes: [9, 8446] 
```

**Comment by Kingdroper** [comment]
> This patch can fix the bug.
> 
> ```
> --- a/tools/llama/generate.py
> +++ b/tools/llama/generate.py
> @@ -263,13 +263,15 @@ def generate(
>          model,
>          next_token.view(1, codebook_dim, -1),
>          input_pos,
> -        max_new_tokens - 1,
> +        max_new_tokens - T - 1,
>          im_end_id=im_end_id,
>          decode_one_token=decode_one_token,
>          **sampling_kwargs,
>      )
>      # x = torch.cat(generated_tokens, dim=1)
> ```
> 
> But I got two new problems.
> 
> 1. Increasing max_new_tokens to 2048 cause cuda error: device-side assert triggered.
> 
> ```
> unknown:0: unknown: block: [0,0,0], thread: [32,0,0] Assertion `index out of bounds: 0 <= tmp5 < 2048` failed.
> unknown:0: unknown: block: [0,0,0], thread: [33,0,0] Assertion `index out of bounds: 0 <= tmp5 < 2048` failed.
> unknown:0: unknown: block: [0,0,0], thread: [34,0,0] Assertion `index out of bounds: 0 <= tmp5 < 2048` failed.
> unknown:0: unknown: block: [0,0,0], thread: [35,0,0] Assertion `index out of bounds: 0 <= tmp5 < 2048` failed.
> ```
> 
> 2. After apply the patch above,  it will trigger a new bug occasionally that prompt size T is larger than max_new_tokens.

hello, How did you solve this problem 1?

**Comment by MisakaMikoto96** [comment]
> > This patch can fix the bug.
> > ```
> > --- a/tools/llama/generate.py
> > +++ b/tools/llama/generate.py
> > @@ -263,13 +263,15 @@ def generate(
> >          model,
> >          next_token.view(1, codebook_dim, -1),
> >          input_pos,
> > -        max_new_tokens - 1,
> > +        max_new_tokens - T - 1,
> >          im_end_id=im_end_id,
> >          decode_one_token=decode_one_token,
> >          **sampling_kwargs,
> >      )
> >      # x = torch.cat(generated_tokens, dim=1)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But I got two new problems.
> > 
> > 1. Increasing max_new_tokens to 2048 cause cuda error: device-side assert triggered.
> > 
> > ```
> > unknown:0: unknown: block: [0,0,0], thread: [32,0,0] Assertion `index out of bounds: 0 <= tmp5 < 2048` failed.
> > unknown:0: unknown: block: [0,0,0], thread: [33,0,0] Assertion `index out of bounds: 0 <= tmp5 < 2048` failed.
> > unknown:0: unknown: block: [0,0,0], thread: [34,0,0] Assertion `index out of bounds: 0 <= tmp5 < 2048` failed.
> > unknown:0: unknown: block: [0,0,0], thread: [35,0,0] Assertion `index out of bounds: 0 <= tmp5 < 2048` failed.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. After apply the patch above,  it will trigger a new bug occasionally that prompt size T is larger than max_new_tokens.
> 
> hello, How did you solve this problem 1?

hi, have you solved this problem?
