### ISSUE TITLE
[BUG] Confusion caused by 'prompt-text/tokens' in inference stage

### ISSUE THREAD

**Issue by WinterStraw** [fishaudio/fish-speech#54]
Thank you so much for your open-source initiative. The transition from a VITS structure to a transformer-based structure is exciting. 

**Describe the bug**
It could be a mistake in the description of the introduction/inference, or it could be something else.

**Details**
I noticed that in the introduction stage, the inference part of the model was described as requiring only textual input. But under inference, the user is asked to enter 'prompt-text/tokens''.

Perhaps you can consider adding a simple inference code that requires only --text or explain why prompt input is still required during the inference phase.

Thank you for your contributions.

**Comment by leng-yue** [comment]
Prompt text / tokens are used for zeroshot TTS speaker following (conditioned on specific speaker), otherwise, it will use random speaker.
