### ISSUE TITLE
How can i train a new language? [pt-br]

### ISSUE THREAD

**Issue by eletroswing** [fishaudio/fish-speech#549]
### Self Checks

- [X] I have searched for existing issues [search for existing issues]([https://github.com/langgenius/dify/issues](https://github.com/fishaudio/fish-speech/issues)), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

There aren't many TTS focused on BR Portuguese, and the quality of fish tts is incredible, I want to be able to train a model in this language, but I couldn't find any guides or how to structure the dataset

### 2. Additional context or comments

put in the docs how to structure a dataset and generate a model in a new language different from the pre-existing ones

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by AnyaCoder** [comment]
We have written a tutorial for this.
https://speech.fish.audio/finetune/

**Comment by batya86** [comment]
Hello. I am Azerbaijani. I tested my own voice. It does not pronounce letters like **Q, Ü, Ə, X** correctly. How can I fix this? Everything works, but these letters do not sound right.

**Comment by MrNogat** [comment]
hi, is portuguese supported now?
