### ISSUE TITLE
创建一个微信群供国内用户讨论，并将其放置于显眼位置 (Adding WeChat Group for Chinese users)

### ISSUE THREAD

**Issue by sudo888samewick** [fishaudio/fish-speech#558]
### Self Checks

- [X] I have searched for existing issues [search for existing issues]([https://github.com/langgenius/dify/issues](https://github.com/fishaudio/fish-speech/issues)), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

我发现当前好像没有提供微信群的入口，仅有的 QQ 群也是被放在一个不是很显眼的位置。 国内用户其实大多用微信，我建议也设置一个微信社区群。并非引流，下面的群作为过渡，若作者需要，我可以转让群管理权（我已经阅读了第三条 check ，礼貌上为了不违反它，下面再用英语复述一遍）

I found that the current requirements do not provide an entrance to the WeChat group. In addition to the QQ group, it is also recommended to be placed in a less conspicuous position. Domestic users actually mainly use WeChat, and I have also set up a WeChat community group.

![image](https://github.com/user-attachments/assets/b4385ff5-cb77-4b6a-a2d5-0067fccdbf80)

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by huazhipeng** [comment]
过期了

**Comment by zzhdbw** [comment]
Expired, request update

**Comment by ltcxjtu** [comment]
please update

**Comment by rose07** [comment]
https://tts.byylook.com/ai/text-to-speech

**Comment by rose07** [comment]
> Expired, request update

https://tts.byylook.com/ai/text-to-speech

**Comment by rose07** [comment]
> please update

https://tts.byylook.com/ai/text-to-speech

**Comment by jhhhhkj** [comment]
重新发一下

**Comment by xeoshow** [comment]
二维码过期了，qq群也没看到在哪里

**Comment by abersheeran** [comment]
官方 QQ 频道在 https://pd.qq.com/s/bwxia254o
