### ISSUE TITLE
[Feature] Ukrainian language model

### ISSUE THREAD

**Issue by gianpaj** [fishaudio/fish-speech#563]
### Self Checks

- [X] I have searched for existing issues [search for existing issues]([https://github.com/langgenius/dify/issues](https://github.com/fishaudio/fish-speech/issues)), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I would like to generate Ukrainian audio files

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by PoTaTo-Mika** [comment]
Planned to add in the later versions.

**Comment by vgabbo** [comment]
please add also Italian T_T

**Comment by emptystack1024** [comment]
please add also Tibetan T_T
