### ISSUE TITLE
Sampling parameters in llama generate.py get ignored

### ISSUE THREAD

**Issue by EndlessReform** [fishaudio/fish-speech#567]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have searched for existing issues [search for existing issues](https://github.com/fishaudio/fish-speech/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

I've made a reproducible example that prints out the sampling args going into `decode_one_token_ar` and immediately aborts: https://github.com/EndlessReform/fish-speech/blob/c6555d6d49a1e768e3ba29ef4d9caca2cb903822/tools/llama/generate.py#L102.  Check out [this branch](https://github.com/EndlessReform/fish-speech/tree/hyperparameter-issue) and run:

```
python tools/llama/generate.py --text "Hello world" --num-samples 1 --half --device cpu --checkpoint-path ../fish-speech-candle/checkpoints/fish-speech-1.2-sft --temperature 0.5
```

It should print out:
```
{'temperature': 0.1, 'top_p': 0.1, 'repetition_penalty': 1.0}
```

### ✔️ Expected Behavior

Hopefully, these default values (temp 0.1, min-p 0.1 rep pen 1 over a 16 token window) would be moved to the defaults in the entry point `generate.py` and overrideable. Alternately, I noticed that greedy sampling with no repetition penalty leads to highly repetitive output very quickly. If these are the only decoding settings that work, maybe this could be documented somewhere, and the options to set the parameters removed.

### ❌ Actual Behavior

I noticed that in `tools/llama/generate.py`, the sampling parameters like temperature, top-p, and rep-pen from CLI or defaults get ignored. In the `decode_one_token_ar` method, they're all hard-coded: https://github.com/fishaudio/fish-speech/blob/aa9f85a20504c1e77812cededf01127da433b3e0/tools/llama/generate.py#L101. The CLI and Gradio options to override them don't actually work.  This is currently very confusing, because there's no warning that these options aren't actually being used, and (for example) you can't set deterministic output without monkey-patching the generation code.

**Comment by leng-yue** [comment]
Please don't set temperature to 0.5, we use greedy for main vocab (eos etc) decoding, while users' provided params for codebooks.
