### ISSUE TITLE
Question about ASR results.

### ISSUE THREAD

**Issue by BrianXiao1** [fishaudio/fish-speech#57]
Nice project! For time reasons, I did not read the specific code carefully. So I am confused with the ASR results. 
The original ASR model here is openai whisper and I found that the outputs use space instead punctuation marks. But actually whisper performes not so good on madarin. So I use funasr instead. But the outputs of funasr model are with punctuation marks. 
1. Should I replace punctuation with Spaces?

2. I found that the prompt text and text in your demo are with punctuation marks. So It makes confused.

**Comment by leng-yue** [comment]
Punctuation typically enhances the model's generation quality, but it can also function effectively without it, as it was trained on data with and without punctuation.
