### ISSUE TITLE
how to use webUI ( downloaded) correctly?

### ISSUE THREAD

**Issue by crowdedplus** [fishaudio/fish-speech#571]
### Self Checks

- [X] I have searched for existing issues [search for existing issues]([https://github.com/langgenius/dify/issues](https://github.com/fishaudio/fish-speech/issues)), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I tried to use it on the website ,and downloaded the model ,trained and i received a bad model ,worse than that i generated on the website , so i think there may be something wrong with my work ,and i don't know where the problem is . I ran the install_env.bat , downloaded something ,and started the webUI ,selected the audio path ,clicked on "start training" button , then started the inference server , audio generated sound like it didn't be trained at all.... something i did wrong ? Please forgive my poor english and poor technical skills .

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by AnyaCoder** [comment]
Did you do lora training?

**Comment by chenxi3929** [comment]
> 你参加过 lora 培训吗？
有相关的培训链接吗？

**Comment by rose07** [comment]
https://tts.byylook.com/ai/text-to-speech
