### ISSUE TITLE
Unable to process special characters

### ISSUE THREAD

**Issue by zhang-jr** [fishaudio/fish-speech#572]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have searched for existing issues [search for existing issues](https://github.com/fishaudio/fish-speech/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

In the current version (fish-speech-1.4), if the text to be synthesized contains special characters, like `### **`, the model may exhibit strange behaviors, such as repetition or even producing nonsensical output.

**Comment by Stardust-minus** [comment]
You should do normalize, remove these characters.
