### ISSUE TITLE
「粤语」（广东话, Cantonese）support request

### ISSUE THREAD

**Issue by SakuraRK** [fishaudio/fish-speech#573]
### Self Checks

- [X] I have searched for existing issues [search for existing issues]([https://github.com/langgenius/dify/issues](https://github.com/fishaudio/fish-speech/issues)), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

我希望生成粤语音频，但系似乎输入简体同埋繁体中文都只能生成普通话(国语)/闽南语语音，并且会发生严重既幻觉（欠收敛），既系生成胡言乱语。(There is orginal from cantonese/zh-Hant)
I would like to generate Cantonese audio waves, but it seems that input Simplified Chinese or Traditional Chinese only generates Mandarin/Min Nan speech, and there are serious hallucinations  that it is generating gibberish. 

### 2. Additional context or comments

none

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by leng-yue** [comment]
Probably need to finetune on some Cantonese dataset.

**Comment by Octopus058** [comment]
@SakuraRK btw is Traditional Chinese README needed?

**Comment by SakuraRK** [comment]
> 顺便说一句，需要繁体中文 README 吗？
Thank you, but I can understand and use Cantonese and Mandarin well. But if not you can add it to provide help for Traditional Chinese users.

**Comment by Octopus058** [comment]
> > 顺便说一句，需要繁体中文 README 吗？
> Thank you, but I can understand and use Cantonese and Mandarin well. But if not you can add it to provide help for Traditional Chinese users.
> 

huh, I can only translate Simplified Chinese characters literally into Traditional Chinese characters, but some specific Cantonese expressions cannot be translated. I will translate them recently and send them to this issue. Could you please verify and correct it?

**Comment by rose07** [comment]
https://tts.byylook.com/ai/text-to-speech

**Comment by SakuraRK** [comment]
> > > 顺便说一句，需要繁体中文 README 吗？
> > > Thank you, but I can understand and use Cantonese and Mandarin well. But if not you can add it to provide help for Traditional Chinese users.
> 
> huh, I can only translate Simplified Chinese characters literally into Traditional Chinese characters, but some specific Cantonese expressions cannot be translated. I will translate them recently and send them to this issue. Could you please verify and correct it?



> > > 顺便说一句，需要繁体中文 README 吗？
> > > Thank you, but I can understand and use Cantonese and Mandarin well. But if not you can add it to provide help for Traditional Chinese users.
> 
> huh, I can only translate Simplified Chinese characters literally into Traditional Chinese characters, but some specific Cantonese expressions cannot be translated. I will translate them recently and send them to this issue. Could you please verify and correct it?
>"Just DO IT" XD

**Comment by SakuraRK** [comment]
> > > 顺便说一句，需要繁体中文 README 吗？
> > > Thank you, but I can understand and use Cantonese and Mandarin well. But if not you can add it to provide help for Traditional Chinese users.
> 
> huh, I can only translate Simplified Chinese characters literally into Traditional Chinese characters, but some specific Cantonese expressions cannot be translated. I will translate them recently and send them to this issue. Could you please verify and correct it?

"Just DO IT" XD
