### ISSUE TITLE
V1.4 still have word swallowing problem, the last word can only be read half or not.

### ISSUE THREAD

**Issue by DogeFlow** [fishaudio/fish-speech#575]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have searched for existing issues [search for existing issues](https://github.com/fishaudio/fish-speech/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

V1.4 still have word swallowing problem, the last word can only be read half or not.

**Comment by PoTaTo-Mika** [comment]
Try to use ref audio with 0.5s empty voice in the end.

**Comment by zzhdbw** [comment]
> Try to use ref audio with 0.5s empty voice in the end.

how to set this and where can i see the example ?

**Comment by canonhui** [comment]
@zzhdbw you can use this code to add 0.5s empty voice in the end of a wav file:
```
from scipy.io import wavfile

rate, data = wavfile.read('/path/to/your/input/wav')

zeros = np.zeros((rate // 2, data.shape[1]), dtype=data.dtype)
data = np.concatenate([data, zeros], axis=0)

wavfile.write('/path/to/your/modified/wav', rate, data)
```

**Comment by zzhdbw** [comment]
> @zzhdbw you can use this code to add 0.5s empty voice in the end of a wav file:
> 
> ```
> from scipy.io import wavfile
> 
> rate, data = wavfile.read('/path/to/your/input/wav')
> 
> zeros = np.zeros((rate // 2, data.shape[1]), dtype=data.dtype)
> data = np.concatenate([data, zeros], axis=0)
> 
> wavfile.write('/path/to/your/modified/wav', rate, data)
> ```

Thank you!!!!!!!
