### ISSUE TITLE
[Feature] llama model size selection

### ISSUE THREAD

**Issue by WinterStraw** [fishaudio/fish-speech#58]
Thank you so much for your open-source project.

Have you considered using llama models of **larger sizes**?

After completing several finetuning tasks, I found that the current llama model, even after finetuning training, has difficulty learning the difference between synonyms in different contexts.

For example, the word '滚'  in the Chinese blessing '财运滚滚' was read like a swearing.
Perhaps this is the limitation of small-size llama. Or I may need more complex training data to finetune. (currently using 20 hours)

Maybe offering different sizes like openai-whisper would be a good solution.

**Comment by gaotiesuanna** [comment]
hello，you seem to have successfully trained ,can you help me for this ,when i run train.py ,i meet this bug.
https://github.com/fishaudio/fish-speech/issues/59

**Comment by gaotiesuanna** [comment]
hello,have you meet the bug : nstantiationException: Error locating target 'fish_speech.models.vqgan.VQGAN', can you help me?

**Comment by leng-yue** [comment]
Currently, we are working on a larger and more diversed dataset, hope this can help mitigating synonyms issue.
