### ISSUE TITLE
Feature request: ask support for the InternLM

### ISSUE THREAD

**Issue by boshallen** [fishaudio/fish-speech#584]
### Self Checks

- [X] I have searched for existing issues [search for existing issues]([https://github.com/langgenius/dify/issues](https://github.com/fishaudio/fish-speech/issues)), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Hi,

I noticed that the repository currently lacks support for the InternLM2.5-7B (1.8B, 20B) model, which may cause compatibility issues or missing steps for users trying to implement it. It would be beneficial to update the repository with detailed instructions or tools for integrating and using the InternLM2.5-7B model, ensuring the content remains relevant.

I believe that adding this support would significantly enhance the usability of the project. While some manual adjustments are possible, official guidance or toolchain support would be much more efficient and advantageous, especially for new users.

If possible, including example scripts or demonstrating integration with InternLM2.5-7B would also be a valuable addition.

For further support, please add the InternLM Assistant (WeChat search: InternLM) or join the InternLM Discord(https://discord.com/invite/xa29JuW87d).

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by leng-yue** [comment]
How is a TTS project related to InternLM...
