### ISSUE TITLE
ImportError: cannot import name 'LRScheduler' from 'torch.optim.lr_scheduler'

### ISSUE THREAD

**Issue by MrJingLiguo** [fishaudio/fish-speech#586]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have searched for existing issues [search for existing issues](https://github.com/fishaudio/fish-speech/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Cloud or Self Hosted

Cloud

### Steps to reproduce

install pytorch

conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch

start.bat

![image](https://github.com/user-attachments/assets/a9f52738-1aed-4917-aa0f-4078437f7f73)

An error occurs after clicking

![image](https://github.com/user-attachments/assets/ce7168b5-a0f8-48cd-8e3c-b83858fe5b3b)

**Comment by leng-yue** [comment]
Note we only support torch >= 2.3.0
