### ISSUE TITLE
[BUG] InstantiationException: Error locating target 'fish_speech.models.vqgan.VQGAN'

### ISSUE THREAD

**Issue by gaotiesuanna** [fishaudio/fish-speech#59]
when I want to finetune,I run ython fish_speech/train.py --config-name vqgan_finetune ,then it showed : 
<img width="1140" alt="image" src="https://github.com/fishaudio/fish-speech/assets/140049796/8c395a26-46b9-4ddf-b172-1c88faeb3cd4">

<img width="1123" alt="image" src="https://github.com/fishaudio/fish-speech/assets/140049796/5662b733-00cd-44ad-91b6-493ad8f30b38">

hydra.utils.instantiate maybe is reason,but i don't know how to solve?

**Comment by WinterStraw** [comment]
Did you download the VQGAN model from Huggingface?

**Comment by gaotiesuanna** [comment]
> Did you download the VQGAN model from Huggingface?

I did

**Comment by gaotiesuanna** [comment]
Can you tell me about your operating environment? I successfully this step(hydra.utils.instantiate(cfg.model)) in colab, but i failed this step in my mac. and the version of hydra-core is the same 1.3.2 ,  python's is 3.10

**Comment by WinterStraw** [comment]
> Can you tell me about your operating environment? I successfully this step(hydra.utils.instantiate(cfg.model)) in colab, but i failed this step in my mac. and the version of hydra-core is the same 1.3.2 , python's is 3.10

I used Ubuntu and just followed the document. It may have something to do with the path representation of different systems. I'm not sure, but I don't have the problem you mentioned.

**Comment by gaotiesuanna** [comment]
Thanks very much. maybe I can change the environment.

**Comment by leng-yue** [comment]
Feels like the path / env is incorrect.

**Comment by dwanggit** [comment]
just update your python path to include the parent directory

**Comment by gaotiesuanna** [comment]
> just update your python path to include the parent directory

![image](https://github.com/fishaudio/fish-speech/assets/140049796/a67336f1-ad96-4658-8baa-ef254dab2014)
hello, I tried both paths separately.but the error was the same, can you please tell me why ? Thanks in advance!
