### ISSUE TITLE
difference using traditional chinese in website vs. local inference

### ISSUE THREAD

**Issue by colafly** [fishaudio/fish-speech#590]
### Self Checks

- [X] I have searched for existing issues [search for existing issues]([https://github.com/langgenius/dify/issues](https://github.com/fishaudio/fish-speech/issues)), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

i've tried the same sentence in traditional Chinese both on your website and through local inference and got very different results:

the sentence is "您的餐點好了, 請至櫃台領取" 

however, in your website it is generated with mandarin pronunciation, in local inference it generated some dialect instead. What's the difference?  Is there certain parameters I should use? 

If I want to use traditional Chinese with mandarin pronunciation, would that work on fine-tune? 

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by leng-yue** [comment]
We applied trad to simplify on the website

**Comment by colafly** [comment]
Thanks for quick response. Can zero-shot support for traditional chinese possible with lora fine-tuning ? or thats something need to be done during pre-train?
