### ISSUE TITLE
Speed controls, emotions, and other input parameters

### ISSUE THREAD

**Issue by platform-kit** [fishaudio/fish-speech#591]
### Self Checks

- [X] I have searched for existing issues [search for existing issues]([https://github.com/langgenius/dify/issues](https://github.com/fishaudio/fish-speech/issues)), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

First off, great work on this project. It's very impressive.

I think in order for it to be useful in a wide variety of situations, certain things are needed. The first one I've run into is the need to control the speed of the speech.  

Can someone confirm -- am I mistaken, or does this not yet exist, as it does in other TTS libraries?

On that note, what are the other input parameters besides temperature, and where are they documented?  

Particularly -- I saw in some of the blog/medium posts surrounding the release of 1.3 and 1.4 that "emotion control" was a feature, but is that an independently controllable input, or is it entirely inferred from the reference audio in zero-shot voice cloning?

### 2. Additional context or comments

Just looking for answers.

One thought I had -- If it is technically possible to pass one piece of audio for speaker identity / timbre, and another for cadence and/or emotion, that might solve the problem. I am unclear right now on whether those are all treated as a single value, or if they can be separated.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by xiaokang00010** [comment]
For another project, GPT-SoViTs, it will automatically inherit the speech speed from reference audios. However, in fish-speech, I still can't find a way to adjust it.

**Comment by MWTJC** [comment]
From the code of this repo, no code has been found that controls "something about emotion" of the output voices using parameters.    The codes related to emotion in the `sencevoice` directory are not related to speech generation also.    The only confirmed is to use pre-prepared reference audio with different emotions to influence output voices.
Additionally, from the Release text of another repo created by one of the contributors of this repo(AnyaCoder/fish-speech-gui/releases/tag/v1.0.0), it can be confirmed that as of the current time, this repo has no parameters that can clearly control emotion-related things, and probably being prepared and not yet implemented.
