### ISSUE TITLE
RuntimeError: Cannot find a working triton installation. More information on installing Triton can be found at https://github.com/openai/triton

### ISSUE THREAD

**Issue by 0smboy** [fishaudio/fish-speech#596]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have searched for existing issues [search for existing issues](https://github.com/fishaudio/fish-speech/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Cloud or Self Hosted

Cloud

### Steps to reproduce

python tools/llama/generate.py --text "你在干什么？" --prompt-text "Vice President, members of Congress,the First Lady of the United States,and my fellow Americans.Less than one year has passed since I first stood at this podium"  --prompt-tokens "fake.npy" --checkpoint-path ../checkpoints/fish-speech-1.4 --num-samples 2 --compile

**Comment by AnyaCoder** [comment]
how did you install the environment? give detailed infomation.

**Comment by 0smboy** [comment]
colab install script
``` bash
!git clone https://github.com/fishaudio/fish-speech.git

!cd fish-speech/ && pip3 install -e .[stable]
!huggingface-cli download fishaudio/fish-speech-1.4 --local-dir checkpoints/fish-speech-1.4
```

**Comment by AnyaCoder** [comment]
Follow the docs...

**Comment by 0smboy** [comment]
`pip install triton` bypass the error
