### ISSUE TITLE
Inconsistent Voice Quality in Long Speech Generation: Voice Changes After First Few Minutes

### ISSUE THREAD

**Issue by 0smboy** [fishaudio/fish-speech#597]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have searched for existing issues [search for existing issues](https://github.com/fishaudio/fish-speech/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Cloud or Self Hosted

Cloud

### Steps to reproduce

python tools/llama/generate.py --text "嘿，你好。准备好让事情彻底颠覆吧。我们今天要深入探讨彼得·蒂尔的《从0到1》。..."
--prompt-text "Vice President, members of Congress,the First Lady of the United States,and my fellow Americans.Less than one year has passed since I first stood at this podium"  --prompt-tokens "fake.npy" --checkpoint-path ../checkpoints/fish-speech-1.4 --num-samples 1 --compile

### ✔️ Expected Behavior

The generated speech should consistently maintain the same voice quality and tone throughout the entire audio, regardless of length. For a cloned voice, such as Trump’s, the voice should remain stable from start to finish without any noticeable changes or shifts in sound or speaker identity.

**Comment by 0smboy** [comment]
You can listen to the audio example here: [Audio Sample](https://on.soundcloud.com/wbnxGPmvHjY6hE8E8)

**Comment by AnyaCoder** [comment]
use webui / gui for long sentences

**Comment by leng-yue** [comment]
We are working on some better dpo version to reduce the chance of voice changes
