### ISSUE TITLE
which pytorch version do you use?

### ISSUE THREAD

**Issue by deyituo** [fishaudio/fish-speech#6]
python tools/llama/generate.py \
>     --text "要转换的文本" \
>     --prompt-text "你的参考文本" \
>     --prompt-tokens "fake.npy" \
>     --checkpoint-path "checkpoints/text2semantic-400m-v0.2-4k.pth" \
>     --num-samples 2 
Traceback (most recent call last):
  File "xxx/fish-speech/tools/llama/generate.py", line 22, in <module>
    torch._inductor.config.fx_graph_cache = True  # Experimental feature to reduce compilation times, will be on by default in future
  File "xxx/fish-speech/lib/python3.10/site-packages/torch/_dynamo/config_utils.py", line 72, in __setattr__
    raise AttributeError(f"{self.__name__}.{name} does not exist")
AttributeError: torch._inductor.config.fx_graph_cache does not exist

which pytorch version do you use?

**Comment by deyituo** [comment]
comment it seems to work

**Comment by leng-yue** [comment]
I will add some code to check if the inductor config exists.

**Comment by leng-yue** [comment]
Fixed.
