### ISSUE TITLE
Problems reading japanese and punctuations

### ISSUE THREAD

**Issue by reveperdu** [fishaudio/fish-speech#608]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have searched for existing issues [search for existing issues](https://github.com/fishaudio/fish-speech/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

input some less common japanese words, eg. 即ち(sunawachi),沢山(takusan),覆す(kutsugaesu),仮令(tatoe)..., or sentences containing it, and add some punctuations like “”……～

### ✔️ Expected Behavior

read normally with correct pronounciation

### ❌ Actual Behavior

the words are not read correctly, for the words above it was read as sokuchi,zawayama,osu,karei in one case, and the incorrect readings maybe not consistent, when using no reference audio(ie. using random speaker)
For punctuations, sometimes they will be read like a word.
not sure if it's the problem here, and it can be "bypassed" by directly input kana(phonetic notation), though
(also it might have problems telling apart chinese and japanese text)

**Comment by PoTaTo-Mika** [comment]
The punctuation problem will be solved when the supervised finetune version released.
