### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by 443127316** [fishaudio/fish-speech#61]
Hello, I have been deeply impressed by your project after reviewing it. Thank you for open-sourcing such a fantastic project. Additionally, I have two questions for you:

1. Computing Power: Could you please share the GPU model you used to train the current results? Also, approximately how much time did it take for the training?

2. Are you planning to release the training code?

If it is convenient for you, I would greatly appreciate it if you could clarify these questions for me. Once again, thank you very much.

**Comment by leng-yue** [comment]
The training code is already included in repo and all training are done on A800 GPUs.
