### ISSUE TITLE
webui is failed to generate audio, no error reports on the backend log

### ISSUE THREAD

**Issue by Emotibot5** [fishaudio/fish-speech#610]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have searched for existing issues [search for existing issues](https://github.com/fishaudio/fish-speech/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

ui display:
<img width="1528" alt="image" src="https://github.com/user-attachments/assets/285ade29-595b-4bca-963f-83c2209c6e43">

backend report no errors.
i am on linux  and A100 GPU。 

### ✔️ Expected Behavior

the generated audio can be played on the webpage.

### ❌ Actual Behavior

no audio file genereted

**Comment by Emotibot5** [comment]
backend log：


102|fishspeech_webui-1-4  | 2024-10-14 16:46:52.035 | INFO     | tools.llama.generate:generate_long:438 - Encoded text: hello
102|fishspeech_webui-1-4  | 2024-10-14 16:46:52.035 | INFO     | tools.llama.generate:generate_long:456 - Generating sentence 1/1 of sample 1/1
  0%|          | 0/1023 [00:00<?, ?it/s]
  0%|          | 3/1023 [00:00<00:49, 20.68it/s]
  1%|          | 6/1023 [00:00<00:48, 20.83it/s]
  1%|          | 9/1023 [00:00<00:48, 20.90it/s]
  1%|          | 12/1023 [00:00<00:48, 20.89it/s]
  1%|▏         | 15/1023 [00:00<00:48, 20.91it/s]
  2%|▏         | 18/1023 [00:00<00:48, 20.88it/s]
  2%|▏         | 21/1023 [00:01<00:47, 20.88it/s]
  2%|▏         | 24/1023 [00:01<00:48, 20.78it/s]
  3%|▎         | 27/1023 [00:01<00:47, 20.84it/s]
  3%|▎         | 30/1023 [00:01<00:47, 20.76it/s]
  3%|▎         | 31/1023 [00:01<00:49, 20.18it/s]
102|fishspeech_webui-1-4  | 2024-10-14 16:46:53.628 | INFO     | tools.llama.generate:generate_long:511 - Generated 33 tokens in 1.59 seconds, 20.71 tokens/sec
102|fishspeech_webui-1-4  | 2024-10-14 16:46:53.629 | INFO     | tools.llama.generate:generate_long:514 - Bandwidth achieved: 10.24 GB/s
102|fishspeech_webui-1-4  | 2024-10-14 16:46:53.629 | INFO     | tools.llama.generate:generate_long:519 - GPU Memory used: 1.56 GB
102|fishspeech_webui-1-4  | 2024-10-14 16:46:53.630 | INFO     | tools.api:decode_vq_tokens:144 - VQ features: torch.Size([8, 32])

**Comment by allstable** [comment]
Hello，did you resolve this problem？How？I meet the same one. While in the WebUI I can synthesize the audio,but can not play, except I download the audio file to localhost.
