### ISSUE TITLE
load reference audio everytime when i use request and set reference_id

### ISSUE THREAD

**Issue by xhjcxxl** [fishaudio/fish-speech#619]
### Self Checks

- [X] I have searched for existing issues [search for existing issues]([https://github.com/langgenius/dify/issues](https://github.com/fishaudio/fish-speech/issues)), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

1. have you setting to load reference audio **only once**, i want to set one reference audio and timbre not change when i use fish-speech api
2. then, i want to know the worker can work to set over 1, i want to set high qps request

**Comment by AnyaCoder** [comment]
I'll have a look at it.

**Comment by AnyaCoder** [comment]
see #621

**Comment by xhjcxxl** [comment]
it's cool!!!
thanks
