### ISSUE TITLE
[QUESTION] VQGAN Low quality prediction for some audios

### ISSUE THREAD

**Issue by TundraWork** [fishaudio/fish-speech#62]
Recently I found VQGAN seems not very stable on the prediction quality. It will give obviously low quality prediction on many cases.

Here is one typical bad case for example:

[sample-6-gt-and-pred.zip](https://github.com/fishaudio/fish-speech/files/13945482/sample-6-gt-and-pred.zip)

Is this a weakness of the VQGAN model, or it can be workarounded by having higher sampling rate?

I have seen that in `vqgan_pretrain.yaml` we have `sample_rate: 22050`, while in `vqgan_pretrain_v2.yaml` we have `sample_rate: 44100`.

**Comment by leng-yue** [comment]
We are working on a larger and more robust version of VQGAN v2.
