### ISSUE TITLE
use reference voice or random generate voice, the result voice is deep and dull

### ISSUE THREAD

**Issue by xhjcxxl** [fishaudio/fish-speech#624]
### Self Checks

- [X] I have searched for existing issues [search for existing issues]([https://github.com/langgenius/dify/issues](https://github.com/fishaudio/fish-speech/issues)), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

hello，I try use reference voice or random voice to build my voice, but the result voice is deep and dull.Deep and resonant（生成的声音低沉沉闷，不够洪亮，不如官网给出的参考声音）
the female4:
[female4.wav.zip](https://github.com/user-attachments/files/17436308/female4.wav.zip)
the result1:
[audio (47).wav.zip](https://github.com/user-attachments/files/17436319/audio.47.wav.zip)
the female5:
[female5.wav.zip](https://github.com/user-attachments/files/17436320/female5.wav.zip)
the result2:
[audio (48).wav.zip](https://github.com/user-attachments/files/17436324/audio.48.wav.zip)

the websit is good,like this:
![image](https://github.com/user-attachments/assets/1185c95c-6688-4fa8-b0ee-8c29544d09af)

1.so, i want to konw how to set params to fix it, i use reference api params:
```
{
  "text": "请问您期望的安装日期是几月几日，您可以说8月3日，温馨提示",
  "chunk_length": 200,
  "format": "wav",
  "mp3_bitrate": 64,
  "references": [],
  "reference_id": "female5",
  "normalize": true,
  "opus_bitrate": -1000,
  "latency": "normal",
  "streaming": false,
  "emotion": null,
  "max_new_tokens": 1024,
  "top_p": 0.7,
  "repetition_penalty": 1.2,
  "temperature": 0.7
}
```

2.  i try use random voice timbre to generate voice，then i get a good voice；i want to fixed voice, and want to generate voice timbre always, it is has param to fixed it?（我想得到一个比较好的随机音色后，想固定这个音色，固定下来）

- [X] I am interested in contributing to this feature.

**Comment by AnyaCoder** [comment]
```还可以用--reference_id(仅能用一个)来代替--reference_audio和--reference_text, 前提是在项目根目录下创建references/<your reference_id>文件夹， 里面放上任意个音频与对应的标注文本。 目前支持的参考音频最多加起来总时长90s。```
Did you follow it?

**Comment by xhjcxxl** [comment]
> `还可以用--reference_id(仅能用一个)来代替--reference_audio和--reference_text, 前提是在项目根目录下创建references/<your reference_id>文件夹， 里面放上任意个音频与对应的标注文本。 目前支持的参考音频最多加起来总时长90s。` Did you follow it?

yes，i try build dir in references,then i use reference_id,it's work ok! but the result voice is deep and dull
![image](https://github.com/user-attachments/assets/2548aca3-8939-43db-84a6-339b0b37d70a)
![image](https://github.com/user-attachments/assets/a7229fd0-31c1-4f6f-879e-0e3b4186a1c1)

**Comment by AnyaCoder** [comment]
> i try use random voice timbre to generate voice，then i get a good voice；i want to fixed voice, and want to generate voice timbre always, it is has param to fixed it?（我想得到一个比较好的随机音色后，想固定这个音色，固定下来）
see #627 
it seems not possible to fix a voice timbre because there is not speaker embedding used in the model . You can just only make the output deterministic, given some reference audio.

**Comment by liaoweiguo** [comment]
can we select preset references?
