### ISSUE TITLE
Is there a way to upgrade the existing model from version 1.1 to 1.4?

### ISSUE THREAD

**Issue by duchengyao** [fishaudio/fish-speech#625]
### Self Checks

- [X] I have searched for existing issues [search for existing issues]([https://github.com/langgenius/dify/issues](https://github.com/fishaudio/fish-speech/issues)), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Is it technically feasible? If so, could you provide a request for an upgrade tool?

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by AnyaCoder** [comment]
```bash
huggingface-cli download fishaudio/fish-speech-1.4 --local-dir checkpoints/fish-speech-1.4
```

**Comment by duchengyao** [comment]
@AnyaCoder 

I mean, I currently have a model fine-tuned on version 1.1. Can it be converted in some way to work for inference in version 1.4?

Thanks!
