### ISSUE TITLE
python tools/vqgan/inference.py     -i example.wav     --checkpoint-path "checkpoints/fish-speech-1.4/firefly-gan-vq-fsq-8x1024-21hz-generator.pth" Traceback (most recent call last):   File "tools/vqgan/inference.py", line 9, in <module>     from hydra import compose, initialize ImportError: cannot import name 'compose' from 'hydra' (/opt/huawei/ProgramFiles/anaconda3/envs/tts38/lib/python3.8/site-packages/hydra.py)

### ISSUE THREAD

**Issue by ThinkInFuture** [fishaudio/fish-speech#628]
### Self Checks

- [X] This template is only for bug reports. For questions, please visit [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find information to solve my problem. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues, including closed ones. [Search issues](https://github.com/fishaudio/fish-speech/issues)
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template and fill in all required fields.

### Cloud or Self Hosted

Self Hosted (Source)

### Environment Details

1

### Steps to Reproduce

python tools/vqgan/inference.py     -i example.wav     --checkpoint-path "checkpoints/fish-speech-1.4/firefly-gan-vq-fsq-8x1024-21hz-generator.pth"
Traceback (most recent call last):
  File "tools/vqgan/inference.py", line 9, in <module>
    from hydra import compose, initialize
ImportError: cannot import name 'compose' from 'hydra' (/opt/huawei/ProgramFiles/anaconda3/envs/tts38/lib/python3.8/site-packages/hydra.py)

### ✔️ Expected Behavior

1

### ❌ Actual Behavior

1

**Comment by AnyaCoder** [comment]
use python=3.10
