### ISSUE TITLE
What should I do to make fish-speech support streaming input?

### ISSUE THREAD

**Issue by Kingdroper** [fishaudio/fish-speech#629]
### Self Checks

- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find any relevant information that meets my needs. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues [search for existing issues]([https://github.com/langgenius/dify/issues](https://github.com/fishaudio/fish-speech/issues)), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell us your story.

In order to reduce speech synthesis time during long text conversions, I would like to work towards churning input churning output. Can you give me some suggestions?Thank you very much！

### 2. What is your suggested solution?

Maybe we can look at other possible options?

### 3. Additional context or comments

streaming input and streaming output

### 4. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by michaellin99999** [comment]
any luck?  we are trying the same too
