### ISSUE TITLE
Inquiry About Inference Speed in Git Repository with Specific CUDA and PyTorch Configuration

### ISSUE THREAD

**Issue by hertz-pj** [fishaudio/fish-speech#63]
I have encountered an issue related to inference speed that I hope you can assist me with. Below are the details of my environment and the problem:

CUDA and PyTorch Version:
Due to the limitations of my environment, I am restricted to using CUDA version 117, which corresponds to PyTorch version 2.1.0.

Modification for Compatibility:
To make the code run smoothly, I had to comment out line 20 in the file tools/llama/generate.py, which is torch._inductor.config.coordinate_descent_tuning = True.

Issue with Inference Speed:
I observed that the inference speed has not significantly improved as expected. The speed seems to have increased only marginally from 30 tokens/second to 35 tokens/second, rather than reaching the anticipated 500 tokens/second.

Given this context, I have a couple of questions:

Have you conducted any experiments or do you have insights related to inference speed with this specific configuration (CUDA 117 and PyTorch 2.1.0)?
Is there a known issue or limitation with this setup that could explain the lack of expected acceleration in token processing speed?
Any guidance or information you can provide would be greatly appreciated.

Thank you for your time and assistance.

**Comment by leng-yue** [comment]
Are you using Windows or Linux? Which GPU are you using?

**Comment by leng-yue** [comment]
Can you try the beta version of PyTorch to see if they made any improvment.

**Comment by hertz-pj** [comment]
Due to specific reasons, I am unable to change my CUDA version. CUDA 117 only supports up to PyTorch 2.1, therefore, I am unable to use the nightly version of PyTorch.

**Comment by leng-yue** [comment]
What's your GPU utilization and GPU memory bandwidth when generating samples?

**Comment by hertz-pj** [comment]
![Uploading image.png…]()

**Comment by hertz-pj** [comment]
![Uploading 企业微信截图_17055459408184.png…]()

**Comment by hertz-pj** [comment]
![企业微信截图_17055459408184](https://github.com/fishaudio/fish-speech/assets/17819608/6cbb17f4-a983-4d33-b95a-a4b027214530)

**Comment by hertz-pj** [comment]
![image](https://github.com/fishaudio/fish-speech/assets/17819608/e8140199-3377-4a0b-940b-49c41a1e9b58)

**Comment by hertz-pj** [comment]
If I don't comment out this line of code,
torch._inductor.config.coordinate_descent_tuning = True
an error occurs:
assert len(candidate_values) > 0."

**Comment by hertz-pj** [comment]
gpu：A10
cuda：12.3
pytorch：2.3
It's ok。

**Comment by dwanggit** [comment]
> ![企业微信截图_17055459408184](https://private-user-images.githubusercontent.com/17819608/297595614-6cbb17f4-a983-4d33-b95a-a4b027214530.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDkyODQsIm5iZiI6MTcwNTU0ODk4NCwicGF0aCI6Ii8xNzgxOTYwOC8yOTc1OTU2MTQtNmNiYjE3ZjQtYTk4My00ZDMzLWI5NWEtYTRiMDI3MjE0NTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDAzMzYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ODJhM2FhMTIyZTlmOTUwYzcwY2NmMTIzMzEwYmFkMmRhZDYxYzcxYWYxYjkyM2YyMWE0OWZjYmZhYWFjMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hHxRDubzYL7K0ACTzYdSU79CCfNstDN0-uHdlKMfgLc)

Actually I have a similar question regarding this figure. As we can see the first round "code_0" is much slower than the rest "code_1, _2 ...". But those codes are actually different output variations for one same input text. However, if I am trying to generate only one result (code_0) for one input and generate for a batch of different input texts, the speed will be slow, since every decode process will be as slow as the first time. How I can improve the inference speed for case like that (code_0 inference speed)?

**Comment by hertz-pj** [comment]
> > ![企业微信截图_17055459408184](https://private-user-images.githubusercontent.com/17819608/297595614-6cbb17f4-a983-4d33-b95a-a4b027214530.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDkyODQsIm5iZiI6MTcwNTU0ODk4NCwicGF0aCI6Ii8xNzgxOTYwOC8yOTc1OTU2MTQtNmNiYjE3ZjQtYTk4My00ZDMzLWI5NWEtYTRiMDI3MjE0NTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDAzMzYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ODJhM2FhMTIyZTlmOTUwYzcwY2NmMTIzMzEwYmFkMmRhZDYxYzcxYWYxYjkyM2YyMWE0OWZjYmZhYWFjMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hHxRDubzYL7K0ACTzYdSU79CCfNstDN0-uHdlKMfgLc)
> 
> Actually I have a similar question regarding this figure. As we can see the first round "code_0" is much slower than the rest "code_1, _2 ...". But those codes are actually different output variations for one same input text. However, if I am trying to generate only one result (code_0) for one input and generate for a batch of different input texts, the speed will be slow, since every decode process will be as slow as the first time. How I can improve the inference speed for case like that (code_0 inference speed)?

The issue you mentioned is different from mine. It's normal for the first round of inference to be slow, as this is due to the mechanism of torch.compile.

**Comment by leng-yue** [comment]
> > ![企业微信截图_17055459408184](https://private-user-images.githubusercontent.com/17819608/297595614-6cbb17f4-a983-4d33-b95a-a4b027214530.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDkyODQsIm5iZiI6MTcwNTU0ODk4NCwicGF0aCI6Ii8xNzgxOTYwOC8yOTc1OTU2MTQtNmNiYjE3ZjQtYTk4My00ZDMzLWI5NWEtYTRiMDI3MjE0NTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDAzMzYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ODJhM2FhMTIyZTlmOTUwYzcwY2NmMTIzMzEwYmFkMmRhZDYxYzcxYWYxYjkyM2YyMWE0OWZjYmZhYWFjMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hHxRDubzYL7K0ACTzYdSU79CCfNstDN0-uHdlKMfgLc)
> 
> Actually I have a similar question regarding this figure. As we can see the first round "code_0" is much slower than the rest "code_1, _2 ...". But those codes are actually different output variations for one same input text. However, if I am trying to generate only one result (code_0) for one input and generate for a batch of different input texts, the speed will be slow, since every decode process will be as slow as the first time. How I can improve the inference speed for case like that (code_0 inference speed)?

This is caused by torch.compile, if you use the API server, which only compile the model once, you can solve this issue.
