### ISSUE TITLE
Duplicate seed arg in post api tool

### ISSUE THREAD

**Issue by NinjaPerson24119** [fishaudio/fish-speech#645]
### Self Checks

- [X] This template is only for bug reports. For questions, please visit [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find information to solve my problem. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues, including closed ones. [Search issues](https://github.com/fishaudio/fish-speech/issues)
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template and fill in all required fields.

### Cloud or Self Hosted

Self Hosted (Source)

### Environment Details

Arch

### Steps to Reproduce

https://github.com/fishaudio/fish-speech/blob/main/tools/post_api.py#L128

You've registered the arg for --seed twice, causing it to fail when running the example here https://speech.fish.audio/inference/#vqgan-decoder

**Comment by AnyaCoder** [comment]
Sorry for carelessness, fixed it
