### ISSUE TITLE
[BUG] Hanging on train.py

### ISSUE THREAD

**Issue by hzfei** [fishaudio/fish-speech#65]
![image](https://github.com/fishaudio/fish-speech/assets/42926130/71216d9e-ab9c-4ccb-a920-61a7ef740882)

**Comment by leng-yue** [comment]
Can you provide more details like GPU and system you are using? I don't think nccl is working properly on windows, you may want to try gloo instead.

**Comment by hzfei** [comment]
system:  ubuntu22.04
GPU: 4090 X 4

using one GPU works

**Comment by hzfei** [comment]
GPUS communication err

**Comment by leng-yue** [comment]
You need to send env: NCCL_P2P_DISABLE=1
