### ISSUE TITLE
fish agent local webui cannot send audio to model

### ISSUE THREAD

**Issue by Starlento** [fishaudio/fish-speech#657]
### Self Checks

- [X] This template is only for bug reports. For questions, please visit [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find information to solve my problem. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues, including closed ones. [Search issues](https://github.com/fishaudio/fish-speech/issues)
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template and fill in all required fields.

### Cloud or Self Hosted

Self Hosted (Source)

### Environment Details

wsl2
python 3.11
gradio 5.5.0

### Steps to Reproduce

https://speech.fish.audio/start_agent/
Is it an issue related to gradio? For text input, the system works.
For audio, actually the record or upload works in UI, but it seems failed to send to model.
Maybe an issue for wsl2+windows host access the webui?

### ✔️ Expected Behavior

Audio successfully recorded and input to model.

### ❌ Actual Behavior

  File "/opt/fish-speech/tools/e2e_webui.py", line 69, in process_audio_input
    raise gr.Error("Invalid audio format")
gradio.exceptions.Error: 'Invalid audio format'

OR

  File "/opt/fish-speech/tools/e2e_webui.py", line 50, in process_audio_input
    raise gr.Error("No input provided")
gradio.exceptions.Error: 'No input provided'

![image](https://github.com/user-attachments/assets/d6794b08-7d0e-4dfc-a6a7-d459494d55b1)

**Comment by AnyaCoder** [comment]
#659 will fully fix it

**Comment by Starlento** [comment]
> #659 will fully fix it

Just test that it is working properly. Thanks for the great work.
