### ISSUE TITLE
[BUG]生成的音频出现拼接问题

### ISSUE THREAD

**Issue by hzfei** [fishaudio/fish-speech#66]
python tools/llama/generate.py \
    --text "海鸥岛有哪些好玩的地方" \
    --prompt-text "打开晾衣架照明" \
    --prompt-tokens "fake.npy" \
    --checkpoint-path "results/text2semantic_400m_finetune_spk/checkpoints/step_000000400.ckpt" \
    --speaker "1" \
    --num-samples 2 \
    --compile
    
    用自己的语料微调了一下vqgan & llama
   prompt对应的音频是：打开晾衣架照明
   生成的音频内容是：哎。。。打开晾衣架照明，海鸥岛有哪些好玩的地方

**Comment by leng-yue** [comment]
一般是 fake.npy 和文本没对上, 你自己解码试试
