### ISSUE TITLE
Regarding model versions in PLAYGROUND and HUGGINGFACE

### ISSUE THREAD

**Issue by padmanabanSampath** [fishaudio/fish-speech#669]
### Self Checks

- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find any relevant information that meets my needs. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues [search for existing issues]([https://github.com/langgenius/dify/issues](https://github.com/fishaudio/fish-speech/issues)), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell us your story.

what is the version in huggingface and playground and fish.audio, because using the same reference audio in playground and hugging face, the huggingface model not perform well, but the model at playground performs well. is there any difference in the model?

### 2. What is your suggested solution?

if you mention the model version correctly at playground and huggingface, the we will be able to identify it and process according to it

### 4. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by PoTaTo-Mika** [comment]
We have done some dpo and sft to the Model in our playground, while the huggingface version only contains dpo.

**Comment by padmanabanSampath** [comment]
any plan for release the model? if no means any dataset for supervised fine tuning done? maybe a little example will do the trick, we can prepare it. One more thing, if you provide how to make the training for the new language addition it will be really helpful, The model will evolve so quickly.
