### ISSUE TITLE
ERROR:    Error loading ASGI app. Could not import module "tools.api".

### ISSUE THREAD

**Issue by sipie800** [fishaudio/fish-speech#672]
### Self Checks

- [X] This template is only for bug reports. For questions, please visit [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find information to solve my problem. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues, including closed ones. [Search issues](https://github.com/fishaudio/fish-speech/issues)
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template and fill in all required fields.

### Cloud or Self Hosted

Self Hosted (Source)

### Environment Details

following your instructions,
and run
python tools/api.py --llama-checkpoint-path checkpoints/fish-agent-v0.1-3b/ --mode agent.

and the error happens without more infomations about what the error exactly is.
If the error is catched, I can solve myself quite easily. IMO however you are using kui which just swallow the traceback of python, then makes it difficult to debug.
BTW I run python tools/webui.py without errors

### Steps to Reproduce

python tools/api.py --llama-checkpoint-path checkpoints/fish-agent-v0.1-3b/ --mode agent.

### ✔️ Expected Behavior

run api

### ❌ Actual Behavior

nothing

**Comment by PoTaTo-Mika** [comment]
please use
```bash
python -m tools.api --llama-checkpoint-path checkpoints/fish-agent-v0.1-3b/ --mode agent 
```
to run the api

**Comment by sipie800** [comment]
that's the line I run and fail before this. It throws an error says it can't find tools.api

---- Replied Message ----
| From | ***@***.***> |
| Date | 11/09/2024 16:00 |
| To | fishaudio/fish-speech ***@***.***> |
| Cc | neve33210 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [fishaudio/fish-speech] ERROR: Error loading ASGI app. Could not import module "tools.api". (Issue #672) |

please use

python -m tools.api --llama-checkpoint-path checkpoints/fish-agent-v0.1-3b/ --mode agent 

to run the api

**Comment by AnyaCoder** [comment]
export PYTHONPATH=$PWD
