### ISSUE TITLE
inference step python tools/vqgan/inference.py -i 009200.wav  generate wav quality not good 

### ISSUE THREAD

**Issue by lzuliuyu** [fishaudio/fish-speech#683]
### Self Checks

- [X] This template is only for bug reports. For questions, please visit [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find information to solve my problem. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues, including closed ones. [Search issues](https://github.com/fishaudio/fish-speech/issues)
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template and fill in all required fields.

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Environment Details

linux python 3.8

### Steps to Reproduce

python tools/vqgan/inference.py -i 009200.wav" --checkpoint-path checkpoints/fish-speech-1.4/firefly-gan-vq-fsq-8x1024-21hz-generator.pth"

### ✔️ Expected Behavior

expect the restore wav is similar to the enroll wav

### ❌ Actual Behavior

but the restore wav in bad quality and speaker not similar

**Comment by lzuliuyu** [comment]
There are enroll wav and restore wav

**Comment by lzuliuyu** [comment]
restore 的fake.wav音质较差、有噪声、声音还很哑

**Comment by Stardust-minus** [comment]
Please post your source audio, and reconstruct audio.

**Comment by lzuliuyu** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by lzuliuyu** [comment]
[source_audio_and_resonstruct_audio.zip](https://github.com/user-attachments/files/17928197/source_audio_and_resonstruct_audio.zip)

**Comment by Stardust-minus** [comment]
Did your vector_quantize_pytorch version == 1.14.24?

**Comment by lzuliuyu** [comment]
> Please post your source audio, and reconstruct audio.

- this is source wav and reconstruct [](url)

[source_audio_and_resonstruct_audio.zip](https://github.com/user-attachments/files/17928218/source_audio_and_resonstruct_audio.zip)

**Comment by lzuliuyu** [comment]
> Did your vector_quantize_pytorch version == 1.14.24?

my vector_quantize_pytorch  1.14.1

**Comment by lzuliuyu** [comment]
> Did your vector_quantize_pytorch version == 1.14.24?

vector-quantize-pytorch   1.20.9

**Comment by Stardust-minus** [comment]
> > Did your vector_quantize_pytorch version == 1.14.24?
> 
> vector-quantize-pytorch 1.20.9

Try to downgrade it to 1.14.24

**Comment by lzuliuyu** [comment]
> > > Did your vector_quantize_pytorch version == 1.14.24?
> > 
> > 
> > vector-quantize-pytorch 1.20.9
> 
> Try to downgrade it to 1.14.24

The problem has been solved by set vector-quantize-pytorch 1.14.24,thank you
