### ISSUE TITLE
我是 4090 显卡, 实在是太太太慢了... I have a 4090 graphics card, but my wife is too slow

### ISSUE THREAD

**Issue by femis** [fishaudio/fish-speech#684]
### Self Checks

- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find any relevant information that meets my needs. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues [search for existing issues]([https://github.com/langgenius/dify/issues](https://github.com/fishaudio/fish-speech/issues)), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell us your story.

我生成大概 400 个文字, 目前需要5分钟以上!
我机器配置, i9 4090 显存 24G
![ME1732674949033](https://github.com/user-attachments/assets/c797032b-cc49-42bb-9b62-790cb700f41d)

### 2. What is your suggested solution?

我启动的是 api.py 
使用默认配置启动

### 3. Additional context or comments

~

### 4. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by femis** [comment]
各位大佬, 我这个速度正常吗, 还是这个项目速度就是这样!
同样的文字 SoVITS 几秒钟就生成了;

**Comment by Stardust-minus** [comment]
Please use WSL, and add compile flags.
The issue was closed because it conflict our language policy.
