### ISSUE TITLE
[Feature] how to start many data_server at the same time?

### ISSUE THREAD

**Issue by Zth9730** [fishaudio/fish-speech#69]
The default ip for the data_server service is 127.0.0.1:50051, can this be changed? In other words I want to start two data_servers at the same time (each with different data), how can I do that?  Thank you!

**Comment by leng-yue** [comment]
We can probably add an option to specify data server port manually.

**Comment by leng-yue** [comment]
Supported in https://github.com/fishaudio/fish-speech/commit/61a8ab15c7bc15edb2edebbe4fd9881662818db2
