### ISSUE TITLE
我看到Speech to Text api 可以返回文本的start和end，请问一下Text to Speech api是否也可以返回start和end呢？

### ISSUE THREAD

**Issue by gubeils** [fishaudio/fish-speech#690]
### Self Checks

- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find any relevant information that meets my needs. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues [search for existing issues]([https://github.com/langgenius/dify/issues](https://github.com/fishaudio/fish-speech/issues)), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell us your story.

我看到Speech to Text api 可以返回start和end，请问一下Text to Speech 是否也可以返回呢
![image](https://github.com/user-attachments/assets/720bfa14-34a3-44fa-8303-7ca3c125e399)

### 2. What is your suggested solution?

Text to Speech 也可以返回start和end

### 4. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by xeoshow** [comment]
同问，这个挺重要，尤其是一些基础功能如标定口播字幕等

**Comment by gubeils** [comment]
火山引擎返回的json, 如果能返回类似结构,处理字幕时会很方便.

![image](https://github.com/user-attachments/assets/2e6d9298-2411-4e1d-9793-64c04e8b235f)
[FeHelper-20241203114555.json](https://github.com/user-attachments/files/17987057/FeHelper-20241203114555.json)

**Comment by Stardust-minus** [comment]
Currently we don't support this feature.
Beseides, the issue will be closed beacuse it conflict our language policy.

**Comment by DomoMKT** [comment]
you can achieve high-quality, low-latency text-to-speech conversion without creating an account at [www.nemesyslabs.com](https://www.nemesyslabs.com).
