### ISSUE TITLE
cmd，run start.bat，and begin download model...，but download end，error occur:FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/fish-speech-1.4/tokenizer.tiktoken'

### ISSUE THREAD

**Issue by zhudemiao** [fishaudio/fish-speech#704]
### Self Checks

- [X] This template is only for bug reports. For questions, please visit [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find information to solve my problem. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues, including closed ones. [Search issues](https://github.com/fishaudio/fish-speech/issues)
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template and fill in all required fields.

### Cloud or Self Hosted

Self Hosted (Source)

### Environment Details

conda create -n fish-speech python=3.12
conda activate fish-speech

pip3 install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu121

pip3 install -e .

pip install https://github.com/AnyaCoder/fish-speech/releases/download/v0.1.0/triton_windows-0.1.0-py3-none-any.whl

### Steps to Reproduce

start.sh

### ✔️ Expected Behavior

start 8080 webui service

### ❌ Actual Behavior

Start HTTP API...
Debug: flags = --listen 0.0.0.0:8080 --llama-checkpoint-path "checkpoints/fish-speech-1.4" --decoder-checkpoint-path "checkpoints/fish-speech-1.4/firefly-gan-vq-fsq-8x1024-21hz-generator.pth" --decoder-config-name firefly_gan_vq
INFO:     Started server process [49168]
INFO:     Waiting for application startup.
2024-12-04 21:30:02.618 | INFO     | tools.api:initialize_app:886 - Loading Llama model...
Exception in thread Thread-5 (worker):
Traceback (most recent call last):
  File "C:\soft\dmodel\anaconda3\envs\fish\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\soft\dmodel\anaconda3\envs\fish\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\soft\dmodel\source\cetcisx\ai\fish-speech\tools\llama\generate.py", line 912, in worker
    model, decode_one_token = load_model(
                              ^^^^^^^^^^^
  File "C:\soft\dmodel\source\cetcisx\ai\fish-speech\tools\llama\generate.py", line 677, in load_model
    model: Union[NaiveTransformer, DualARTransformer] = BaseTransformer.from_pretrained(
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\soft\dmodel\source\cetcisx\ai\fish-speech\fish_speech\models\text2semantic\llama.py", line 408, in from_pretrained
    tokenizer = FishTokenizer(tokenizer_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\soft\dmodel\source\cetcisx\ai\fish-speech\fish_speech\tokenizer.py", line 67, in __init__
    mergeable_ranks = self.load_tiktoken_bpe(model_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\soft\dmodel\source\cetcisx\ai\fish-speech\fish_speech\tokenizer.py", line 89, in load_tiktoken_bpe
    for line in open(tiktoken_bpe_file).read().splitlines():
                ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/fish-speech-1.4/tokenizer.tiktoken'

**Comment by digital-era** [comment]
I have also find the problem use python command mode: Error: Invalid value for '--input-path' / '-i': Path 'codes_0.npy' does not exist. But several days ago it runs well!
The python command :
!python tools/vqgan/inference.py \
    -i {src_A_audio} \
    --checkpoint-path "checkpoints/fish-speech-1.4/firefly-gan-vq-fsq-8x1024-21hz-generator.pth" \
    --output-path {reference_A_audio} \
    --device cpu #cuda

!python tools/llama/generate.py \
  --text {target_text} \
  --prompt-text "The text corresponding to reference audio" \
  --prompt-tokens {reference_A_token} \
  --checkpoint-path "checkpoints/fish-speech-1.4" \
  --num-samples 2  \
  --device cpu #cuda

**Comment by AnyaCoder** [comment]
don't use git clone , use git checkout tags/v1.4.3
