### ISSUE TITLE
Any plan of Gradio app for 

### ISSUE THREAD

**Issue by FurkanGozukara** [fishaudio/fish-speech#705]
Hi are you planning to make a gradio of inference, zero shot and premium training with 180 minutes speech data?

I mean a gradio demo app that has

Inference
0 shot voice clone that can take in multiple audio
Premium training that can train on 180 minutes of speech

Thank you so much

**Comment by Whale-Dolphin** [comment]
We havn't had a plan to support multiple audio ref in webui, you can put them together manully or use terminal infer. And we not have the plan to create a gradio for sft, we think if you need sft, you have the ability to use terminal yourself.

**Comment by FurkanGozukara** [comment]
thanks looks like this wont be a model for general public users

**Comment by Whale-Dolphin** [comment]
We think the zero shot function is enough for general public users. You can also go to our website to have more timbre. We think there is a certain threshold for sft, especially since we updated to version 1.5. Thanks for your comprehension!

**Comment by None1024Outlook** [comment]
> Hi are you planning to make a gradio of inference, zero shot and premium training with 180 minutes speech data?
> 
> I mean a gradio demo app that has
> 
> Inference
> 0 shot voice clone that can take in multiple audio
> Premium training that can train on 180 minutes of speech
> 
> 
> Thank you so much 

Although there is no gradio version, there is a colab version you can try
