### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/fish-speech-1.4/tokenizer.tiktoken'

### ISSUE THREAD

**Issue by digital-era** [fishaudio/fish-speech#710]
### Self Checks

- [X] This template is only for bug reports. For questions, please visit [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find information to solve my problem. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues, including closed ones. [Search issues](https://github.com/fishaudio/fish-speech/issues)
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template and fill in all required fields.

### Cloud or Self Hosted

Cloud

### Environment Details

Google Colab python 3.10

### Steps to Reproduce

!python tools/vqgan/inference.py
-i {src_A_audio}
--checkpoint-path "checkpoints/fish-speech-1.4/firefly-gan-vq-fsq-8x1024-21hz-generator.pth"
--output-path {reference_A_audio}
--device cpu #cuda

!python tools/llama/generate.py
--text {target_text}
--prompt-text "The text corresponding to reference audio"
--prompt-tokens {reference_A_token}
--checkpoint-path "checkpoints/fish-speech-1.4"
--num-samples 2
--device cpu #cuda

### ✔️ Expected Behavior

Run thgrouth and generat codes_0.npy

### ❌ Actual Behavior

Traceback (most recent call last):
  File "/content/fish-speech/tools/llama/generate.py", line 1115, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/content/fish-speech/tools/llama/generate.py", line 1057, in main
    model, decode_one_token = load_model(
  File "/content/fish-speech/tools/llama/generate.py", line 677, in load_model
    model: Union[NaiveTransformer, DualARTransformer] = BaseTransformer.from_pretrained(
  File "/content/fish-speech/fish_speech/models/text2semantic/llama.py", line 408, in from_pretrained
    tokenizer = FishTokenizer(tokenizer_path)
  File "/content/fish-speech/fish_speech/tokenizer.py", line 67, in __init__
    mergeable_ranks = self.load_tiktoken_bpe(model_path)
  File "/content/fish-speech/fish_speech/tokenizer.py", line 89, in load_tiktoken_bpe
    for line in open(tiktoken_bpe_file).read().splitlines():
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/fish-speech-1.4/tokenizer.tiktoken'
Usage: inference.py [OPTIONS]
Try 'inference.py --help' for help.

**Comment by Cvandia** [comment]
same the question

**Comment by None1024Outlook** [comment]
May I ask if there is a link to the Colab notebook?
This issue appears to be caused by the use of incompatible models or fish speech projects.
You can use `git checkout tags/v1.4.3` to switch to fish speech version 1.4, or download the fish speech v1.5 model for inference.
I hope it can help you. Wish peace with us.

**Comment by pbz134** [comment]
Getting the same error. I tried renaming tokenizer.json to tokenizer.tiktoken but that doesn't work either.

What somehow got the program working is this:
- Grab this tokenizer.tiktoken file https://drive.google.com/file/d/1FVVi180oc2SI6r8XPBkC_3-4DtexProI/view?usp=drive_link
I copied it from the old 1.4 model which I can't find anymore so I uploaded it here
- pip install vector_quantize_pytorch
- Launch fish-speech
- Go to "Inference configuration", tick "Open Inference server"
- Copy the IP address and open it in a new tab
- Wait 20 seconds, then reload and the page is there

Still getting an error here but that's at least something
![grafik](https://github.com/user-attachments/assets/3bfeae88-d954-42d3-8f40-ad1f3dfafc6e)

**Comment by None1024Outlook** [comment]
> Getting the same error. I tried renaming tokenizer.json to tokenizer.tiktoken but that doesn't work either.
> 
> What got the program working is this:
> - Grab this tokenizer.tiktoken file https://huggingface.co/fishaudio/fish-speech-1.5/blob/main/tokenizer.tiktoken
> - pip install vector_quantize_pytorch
> - Launch fish-speech
> - Go to "Inference configuration"
> - Select the 1.5 files from the several dropdown menus
> - Tick "Open Inference server"
> - Copy the IP address and open it in a new tab
> - Wait 20 seconds, then reload and the page is there
> 
> Make sure you download the new 1.5 model in /checkpoints with all the files from huggingface https://huggingface.co/fishaudio/fish-speech-1.5/tree/main
> 
> To avoid some errors in cmd, delete the old 1.4 folder if you have it
> 
> ![grafik](https://github.com/user-attachments/assets/ff86b824-143f-4c13-a5b2-ce2dd2c01320)
> 
> Good luck and have fun

Please do not rename tokenizer.json as tokenizer.tiktoken. Please download the tokenizer.tiktoken of the 1.5 version of the model. The code of the 1.5 version can only use the model of the 1.5 version.
Good luck.

**Comment by PoTaTo-Mika** [comment]
Please check file folder with patience.

**Comment by Cvandia** [comment]
> May I ask if there is a link to the Colab notebook?
> This issue appears to be caused by the use of incompatible models or fish speech projects.
> You can use `git checkout tags/v1.4.3` to switch to fish speech version 1.4, or download the fish speech v1.5 model for inference.
> I hope it can help you. Wish peace with us.

It actually works! Thank you!!
