### ISSUE TITLE
Inference slow

### ISSUE THREAD

**Issue by ChengsongLu** [fishaudio/fish-speech#734]
### Self Checks

- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find any relevant information that meets my needs. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues [search for existing issues]([https://github.com/langgenius/dify/issues](https://github.com/fishaudio/fish-speech/issues)), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell us your story.

python -m tools.run_webui \
    --llama-checkpoint-path "./ckpt/fish-speech-1.5" \
    --decoder-checkpoint-path "./ckpt/fish-speech-1.5/firefly-gan-vq-fsq-8x1024-21hz-generator.pth" \
    --decoder-config-name firefly_gan_vq
    
without "--compile", I got ~60 tokens/sec

with "--compile", I met error: "W1210 18:19:53.543000 139724024968768 torch/fx/experimental/symbolic_shapes.py:4449] [0/1] xindex is not in var_ranges, defaulting to unknown range."

And it raise the error when I am using:
python tools/llama/generate.py \
    --text "The text you want to convert" \
    --prompt-text "Your reference text" \
    --prompt-tokens "fake.npy" \
    --checkpoint-path "checkpoints/fish-speech-1.5" \
    --num-samples 2 \
    --compile
    
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Triton Error [CUDA]: device kernel image is invalid

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

### 2. What is your suggested solution?

None

### 4. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by ChengsongLu** [comment]
Fix by: https://github.com/pytorch/pytorch/issues/119054

and now I got <300 tokens/sec

**Comment by chaopengio** [comment]
> Fix by: [pytorch/pytorch#119054](https://github.com/pytorch/pytorch/issues/119054)
> 
> and now I got <300 tokens/sec on rtx4090, faster but still slower then the official announcement speed

how to get 300 tokens/sec, I only got 170 tokens/sec.
what's the start parameters?
