### ISSUE TITLE
【建议】不使用训练功能只使用文本合成语音功能情况下改进性能

### ISSUE THREAD

**Issue by bigsinger** [fishaudio/fish-speech#747]
### Self Checks

- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find any relevant information that meets my needs. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues [search for existing issues]([https://github.com/langgenius/dify/issues](https://github.com/fishaudio/fish-speech/issues)), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell us your story.

文本合成语音的速度太慢了

### 2. What is your suggested solution?

测试对比了几个TTS的项目，目前这个项目对电脑性能要求是最低的，没有显卡也能用，而且速度很快，效果也非常理想。希望项目开发者们可以参考：https://github.com/harry0703/MoneyPrinterTurbo

但是fish-speech有声音克隆的功能，MoneyPrinterTurbo没有，估计以后会添加。

### 4. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by Stardust-minus** [comment]
This issue will be closed because it conflict our language policy.
