### ISSUE TITLE
api_client can not finish whole words, because the stream is end too early

### ISSUE THREAD

**Issue by liaoweiguo** [fishaudio/fish-speech#755]
### Self Checks

- [X] This template is only for bug reports. For questions, please visit [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find information to solve my problem. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues, including closed ones. [Search issues](https://github.com/fishaudio/fish-speech/issues)
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template and fill in all required fields.

### Cloud or Self Hosted

Self Hosted (Source)

### Environment Details

macOS python 3.12

```python
            stream_stopped_flag = False

            try:
                for chunk in response.iter_content(chunk_size=1024):
                    if chunk:
                        stream.write(chunk)
                        wf.writeframesraw(chunk)
                    else:
                        if not stream_stopped_flag:
                            stream.stop_stream()
                            stream_stopped_flag = True
            finally:
                stream.close()
                p.terminate()
                wf.close()
```

### Steps to Reproduce

python -m tools.api_client -t '.......'

### ✔️ Expected Behavior

check stream status before close

### ❌ Actual Behavior

can not streaming all wav, close before end

**Comment by liaoweiguo** [comment]
just wait for stream finishing:

```python
                    finally:
                        while stream.is_active() or stream.get_output_latency() > 0.1:
                            time.sleep(0.1)  # Wait for the stream to finish playing
                        stream.close()
                        p.terminate()
                        wf.close()

```

**Comment by Stardust-minus** [comment]
> just wait for stream finishing:
> 
> ```python
>                     finally:
>                         while stream.is_active() or stream.get_output_latency() > 0.1:
>                             time.sleep(0.1)  # Wait for the stream to finish playing
>                         stream.close()
>                         p.terminate()
>                         wf.close()
> ```

Does this fix the problem?

**Comment by liaoweiguo** [comment]
> > just wait for stream finishing:
> > ```python
> >                     finally:
> >                         while stream.is_active() or stream.get_output_latency() > 0.1:
> >                             time.sleep(0.1)  # Wait for the stream to finish playing
> >                         stream.close()
> >                         p.terminate()
> >                         wf.close()
> > ```
> 
> Does this fix the problem?

Yes

**Comment by Stardust-minus** [comment]
You can open a pull request to fix this :)

**Comment by liaoweiguo** [comment]
done
