### ISSUE TITLE
Questions about how to finetune on ver1.5?

### ISSUE THREAD

**Issue by BangjianZhou** [fishaudio/fish-speech#764]
### Self Checks

- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find any relevant information that meets my needs. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues [search for existing issues]([https://github.com/langgenius/dify/issues](https://github.com/fishaudio/fish-speech/issues)), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell us your story.

Hi, I want to do some finetuning on the ver 1.5 model. seems that it changes the tokenizer. For the Fishtokenizer, I found that there are 1024 semantic tokens, like <semantic:1> and 4 types of placeholder tokens, but the dataset.py still only shows <semantic>.

Could you please explain the main idea about adding more semantic tokens, what is the advantage? it seems that it's from semantic part's sequence begin to the end, using different semantic token? 

And how I could train with the current dataset.py? I tried to modify the config file, the tokenizer _target_, but still facing issues about other files. Is there a way to convert the Fishtokenizer back to AutoTokenizer so that I could start finetuing?

Thanks a lot for your reply.

### 2. What is your suggested solution?

please help me to do the fine tuning on ver 1.5

### 4. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by BangjianZhou** [comment]
oh I read the code in from conversation.py, so different from previous concatenate the fixed <semantic> token with the text tokens in the first row, now the ver 1.5 uses the <semantic:i> i from 1 to 1024 to map the first row of the vq codes, and concatenate with the text tokens?

**Comment by Stardust-minus** [comment]
No we supported ft
