### ISSUE TITLE
V1.5 Finetune bug

### ISSUE THREAD

**Issue by Charles679** [fishaudio/fish-speech#769]
### Self Checks

- [X] This template is only for bug reports. For questions, please visit [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find information to solve my problem. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues, including closed ones. [Search issues](https://github.com/fishaudio/fish-speech/issues)
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template and fill in all required fields.

### Cloud or Self Hosted

Cloud

### Environment Details

Ubuntu 22.04.4 LTS , python 3.10.12 , torch 2.4.1 

### Steps to Reproduce

I tried to finetune fish-speech 1.5 according to the doc https://speech.fish.audio/finetune/ . Everything went well before the last step.
### 4. Finally, fine-tuning with LoRA

I downloaded LLAMA weights using the command
 `huggingface-cli download fishaudio/fish-speech-1.5 --local-dir checkpoints/fish-speech-1.5`

And then I started the fine-tuning by running the following command:
`python fish_speech/train.py --config-name text2semantic_finetune \
    project=$project \
    +lora@model.model.lora_config=r_8_alpha_16`

### ✔️ Expected Behavior

No bugs

### ❌ Actual Behavior

It is said that 
```requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/checkpoints/fish-speech-1.4/resolve/main/tokenizer_config.json```

![bug](https://github.com/user-attachments/assets/5e39504d-e08f-4e62-af91-ee70b39b2fb4)
But I was training using fish-speech-1.5 at that time. I don't know how to fix the bug.Could you give me a solution to complete the finetune?

**Comment by Charles679** [comment]
I found a similar issue and tried to replace all the 1.4 in the project to 1.5.The problem seems solved

**Comment by gokul-eloop** [comment]
@Charles679 how was the output after finetune? please share your experience.

**Comment by Charles679** [comment]
I gave up finetune on version 1.5. After I solved the problem I mentioned above ,I came across some other problems. I also found an issue similar to the new problem. It is said that finetune on 1.5 is not supported yet. So i'm currently trying finetune on 1.4.

**Comment by gokul-eloop** [comment]
Cool, thanks. Thats my understanding as well. Thanks for confirmation.
