### ISSUE TITLE
--output checkpoints/fish-speech-1.5-yth-lora/

### ISSUE THREAD

**Issue by rhfu** [fishaudio/fish-speech#780]
### Self Checks

- [X] This template is only for bug reports. For questions, please visit [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find information to solve my problem. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues, including closed ones. [Search issues](https://github.com/fishaudio/fish-speech/issues)
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template and fill in all required fields.

### Cloud or Self Hosted

Self Hosted (Source)

### Environment Details

macOS 13.5 python3.10 torch==2.4.1

### Steps to Reproduce

训练好

### ✔️ Expected Behavior

python tools/llama/merge_lora.py \
--lora-config r_8_alpha_16 \
--base-weight checkpoints/fish-speech-1.5 \
--lora-weight results/$project/checkpoints/step_000000010.ckpt \
--output checkpoints/fish-speech-1.5-yth-lora/
﻿
After fine-tuning, how is the directory generated by checkpoints/fish-speech-1.5-yth-lora used in inference? Do you want to specify it during inference?

### ❌ Actual Behavior

After fine-tuning, the generated sound is similar to that without fine-tuning. Is the method used wrong? In which step of reasoning is the model generated by fine-tuning used?

**Comment by PoTaTo-Mika** [comment]
The lora file can be merged into the main checkpoint, and then you can use the merged one to infer.

**Comment by rhfu** [comment]
> The lora file can be merged into the main checkpoint, and then you can use the merged one to infer.

When I merged the past and tried to reason again, the sound turned into noise. Thank you, I will try again.

**Comment by rhfu** [comment]
推荐是1个小时音频素材才去微调，如果只有几分钟音频，就换换推荐音频

**Comment by trackcan** [comment]
我这微调没效果（按步骤一步步操作的），结果都是噪音，有谁测验过微调吗？是不是哪里细节官方没说清楚？

**Comment by rhfu** [comment]
素材最好1个小时以上，训练时长估计得要8-9小时，
