### ISSUE TITLE
[Feature]LLAMA 微调所需数据集的格式

### ISSUE THREAD

**Issue by 12ben** [fishaudio/fish-speech#81]
.
├── SPK1
│   ├── 21.15-26.44.lab
│   ├── 21.15-26.44.mp3
│   ├── 27.51-29.98.lab
│   ├── 27.51-29.98.mp3
│   ├── 30.1-32.71.lab
│   └── 30.1-32.71.mp3
└── SPK2
    ├── 38.79-40.85.lab
    └── 38.79-40.85.mp3

这里面的"lab"文件，如果是使用"txt"文件，格式是什么样子的

**Comment by leng-yue** [comment]
就是单纯的文本.

**Comment by DoiiarX** [comment]
纯文本就行啊。mark一下。
