### ISSUE TITLE
[BUG]tone_sandhi相关

### ISSUE THREAD

**Issue by KamioRinn** [fishaudio/fish-speech#82]
https://github.com/RVC-Boss/GPT-SoVITS/commit/7fc216107baadebc6fd5ae4d9c6ad9e0f8bb5f7c
https://github.com/RVC-Boss/GPT-SoVITS/issues/475#issuecomment-1946284853

**Comment by leng-yue** [comment]
感谢提醒, 已在 dev 分支修复, 预计会和 1.0 一起发布.
