### ISSUE TITLE
[BUG]中文很惊艳，英文完全不行的感觉

### ISSUE THREAD

**Issue by jasonzhang761213** [fishaudio/fish-speech#83]
不知道英文该怎么设置才对
没感觉读英文，就是呃呃啊啊的，给了英文的音频来引导页不行。

中文确实不错

**Comment by Stardust-minus** [comment]
当前版本的基座模型英文含量非常少，请期待正式版

**Comment by gandolfxu** [comment]
@Stardust-minus 预计什么时候出正式版？

**Comment by Stardust-minus** [comment]
> @Stardust-minus 预计什么时候出正式版？

soon，计划今年Q1内

**Comment by prometheus-alien** [comment]
> > @Stardust-minus 预计什么时候出正式版？
> 
> soon，计划今年Q1内

期待，TTS同类开源项目翘楚
