### ISSUE TITLE
[BUG]合成效果和网页上的效果不一样

### ISSUE THREAD

**Issue by Zhou-Bolin** [fishaudio/fish-speech#87]
使用[fishaudio/speech-lm-v1](https://huggingface.co/fishaudio/speech-lm-v1) 下载的vqgan-v1.pth 和 text2semantic-400m-v0.2-4k.pth 进行前向计算。和网页 https://speech.fish.audio/samples 的示例效果差异较大。请问我使用的模型的版本对吗？

看到您这里面speaker本身作为提示送入了模型，会不会是这里speaker 我没有给的原因？

tools/llama/generate.py

if speaker is not None:
    string = f"[SPK: {speaker}] {string}"

string = f"[INST] {string} [/INST]"

tokens = tokenizer.encode(
        string,
        max_length=10**6,
        add_special_tokens=bos,
        truncation=False,
    )

效果：
[纳西妲.zip](https://github.com/fishaudio/fish-speech/files/14325557/default.zip)

**Comment by Stardust-minus** [comment]
是需要给模型输入spk的，在sft阶段有spk的嵌入prompt

**Comment by leng-yue** [comment]
原神需要使用这个模型: https://huggingface.co/fishaudio/speech-lm-v1/blob/main/text2semantic-400m-v0.2-4k-ft-spk-genshin.pth

必须使用 SPK + prompt
