### ISSUE TITLE
[BUG] Different code lead to different cloned audios. 

### ISSUE THREAD

**Issue by duj12** [fishaudio/fish-speech#89]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**
When I run 
`python tools/llama/generate.py` with option ` --num-samples 2`
I will get 2 codes(codes_0.npy, codes_1.npy). 
With this two codes, I get the following 2 cloned audios, respectively
[fake0.zip](https://github.com/fishaudio/fish-speech/files/14329031/fake0.zip)
[fake1.zip](https://github.com/fishaudio/fish-speech/files/14329035/fake1.zip)

I try to run `python tools/llama/generate.py` with option ` --num-samples 1`
And then only 1 codes_0.npy is generated. and the cloned audio is the same as fake0.zip.
The fake1.wav is more close to the reference audio I gave.

**To Reproduce**
```
python tools/vqgan/inference.py \
    -i "/data/megastore/Projects/DuJing/code/TTS/tts/ref_audios/dubbing.wav" \
    --checkpoint-path "checkpoints/vqgan-v1.pth"

HF_ENDPOINT=https://hf-mirror.com python tools/llama/generate.py \
    --text  "因为帮大家争取到的是一个一次性的那个吸水毛巾二十片装的一包，然后我们线上链接给大家好不好？" \
    --prompt-text  "梅姨她操劳家事这么多年，没有功劳也有苦劳，你不要责怪她呀。", \
    --prompt-tokens "fake.npy" \
    --checkpoint-path "checkpoints/text2semantic-400m-v0.2-4k.pth" \
    --num-samples 2 \
    --compile

python tools/vqgan/inference.py \
    -i "codes_0.npy" \
    --checkpoint-path "checkpoints/vqgan-v1.pth"

python tools/vqgan/inference.py \
    -i "codes_1.npy" \
    --checkpoint-path "checkpoints/vqgan-v1.pth"

```

**Expected behavior**
When using just one code, the cloned audio should be better. 
I expect the only one code will share the 2 codes' common information, so the cloned audio is more close to the reference audio.

**Additional context**
And now the inference pipeline is too complex, if there is a one step inference code, with text and reference audio input, the system may be better to use.

**Comment by leng-yue** [comment]
There is no technical difference between the generation process of codes 0 and 1, the only difference is the random seed. 
In the next version, we probably merge the two pipeline into one file.
