### ISSUE TITLE
LLAMA训练时长

### ISSUE THREAD

**Issue by qiuyuzhao** [fishaudio/fish-speech#92]
请问LLAMA大概训练多少个epoch，loss应该到多少可以停

**Comment by Stardust-minus** [comment]
pretrain/finetune？

**Comment by qiuyuzhao** [comment]
> pretrain/finetune

微调， 执行的python fish_speech/train.py --config-name text2semantic_finetune

**Comment by Stardust-minus** [comment]
> > pretrain/finetune
> 
> 微调， 执行的python fish_speech/train.py --config-name text2semantic_finetune

微调的话看数据量，一般情况下一两千步
