### ISSUE TITLE
When to release vqgan-v2

### ISSUE THREAD

**Issue by HaiFengZeng** [fishaudio/fish-speech#94]
is there any pre-trained model to release, can't wait to see the performance

**Comment by Stardust-minus** [comment]
We propose an other vq Enc-Dec,I'd like to call it Firefly(流萤)GAN.
And there is the generate sample.
[a3c8266cc84028d5.zip](https://github.com/fishaudio/fish-speech/files/14364041/a3c8266cc84028d5.zip)

**Comment by HaiFengZeng** [comment]
@Stardust-minus quality is very good? when will we are able to access this model can't wait to play with it
