### ISSUE TITLE
合成音频内容与text不同，且内容无意义

### ISSUE THREAD

**Issue by WangGewu** [fishaudio/fish-speech#99]
我用aishell1+aishell3重新训练了lamma，top5准确率在90%以上。但在推理时，合成音频的内容与text完全不同，且内容是没有意义的

**Comment by WangGewu** [comment]
生成的音频质量还可以，也没有噪音。音色和prompt wav也比较像。就是读的内容很奇怪，没有按照text读，像是在读一段乱码。请问，是不是g2p这里的问题？

**Comment by leng-yue** [comment]
数据太少过拟合了

**Comment by WangGewu** [comment]
训练到300多个iter，top_5_accuracy就到1了。可以提供一些排查思路？

**Comment by hdmjdp** [comment]
> 数据太少过拟合了

集内合成也不对啊，确认是过拟合吗
